### ISSUE TITLE
a标签自动添加向右图标问题

### ISSUE THREAD

**Issue by mnotw** [sdc-alibaba/SUI-Mobile#1]
请问如何去掉a标签自动添加向右图标？

如果想自定义这个图标，该怎么办？

这个图标出现的位置是什么规则控制的？

你们官网的列表视图卡片，添加a标签后，出现的位置不是期望的

![qq 20150702140743](https://cloud.githubusercontent.com/assets/4019254/8470817/cfb46f64-20c3-11e5-9084-e3a986708576.jpg)

另外，有没有一个系统的api？目前官网只有一些demo，最好能有一个详细的api说明每个类是做什么的

**Comment by lihongxun945** [comment]
官网不会太多的介绍每一个 class 怎么用，因为我们假设用户都是会写css的，这些基本看一下就知道了。比如三角箭头这个，你打开debug看一下就知道是 item-link 这个类
