### ISSUE TITLE
页面切换时，有拖影现象

### ISSUE THREAD

**Issue by runtoad** [sdc-alibaba/SUI-Mobile#10]
微信webview里，页面切换时，有拖影现象 手机：魅族mx5 android：5.0.1 微信版本：6.2.4

**Comment by lihongxun945** [comment]
暂时不知道怎么解决，我使用css3动画的，有的手机对css动画支持就是有问题

**Comment by runtoad** [comment]
这个应该是微信的浏览器内核导致的问题，手机系统的浏览器没有这问题。
