### ISSUE TITLE
安卓下出现页面右侧有滚动条

### ISSUE THREAD

**Issue by mingxing** [sdc-alibaba/SUI-Mobile#101]
![6 pic](https://cloud.githubusercontent.com/assets/797557/11291167/2b0c249c-8f78-11e5-8e14-b26528b2629f.jpg)

小米、锤子等手机均出现该情况

**Comment by Mickey-** [comment]
ios下在上下滑动时也有滚动条，这个在预期中，如果业务里有需要隐藏，可以自行在业务的base级样式里控制
