### ISSUE TITLE
官网打不开了

### ISSUE THREAD

**Issue by Dooy** [sdc-alibaba/SUI-Mobile#1056]
sui.taobao.org 
m.sui.taobao.org
都打不开

**Comment by lsxm** [comment]
试试这个,停更后由个人维护的
https://sui.ctolog.com

**Comment by chenedu888** [comment]
PC 端的 sui.taobao.org 也访问不了了，目前项目还基于该框架维护的，怎么办？

**Comment by JSoon** [comment]
这都2020年了（大清都亡了），弃坑吧，早就不维护了。

**Comment by Dooy** [comment]
> 试试这个,停更后由个人维护的
> https://sui.ctolog.com

只恢复了 m.sui.taobao.org  
sui.taobao.org 没恢复啊？
