### ISSUE TITLE
关于“工具栏”中的路由使用

### ISSUE THREAD

**Issue by WriterLuo** [sdc-alibaba/SUI-Mobile#108]
在使用工具栏时，在href添加了路径，来回切换效果并没问题。但DOM中之前切换出来的page并没有remove掉，若切换数次DOM中会有一堆的id="page-xxxxxxxxxxxxx"。请问如何解决没有remove掉之前切换页面的page？还是工具栏并不适合用路由来完成的？谢谢

**Comment by Mickey-** [comment]
是的，工具栏里透出的四五个入口互相跳转，可以不用Router，采用浏览器直接跳转的形式（即加给工具栏链接加`external`的class）

不过出现一堆同模块DOM是不对的，你需要给每个页面设置一个pageid，

``` html
<div class="page" id='router3'>
```

类似这样，之所以出现`id="page-xxxxxxxxxxxxx"`就是因为你没有设置page的id，所以库自动帮你生成了，但因为时间戳不同，每次生成的都是不同的ID
