### ISSUE TITLE
省市区picker插件当设置了默认值的时候，市和区的数据定位有bug

### ISSUE THREAD

**Issue by nancy09** [sdc-alibaba/SUI-Mobile#109]
<input type="text" id='city-picker' value="广东 珠海 斗门区" />
默认值设置为“广东 珠海 斗门区”，
定位在广东 广州 越秀区

**Comment by Claralll** [comment]
嗯，我也遇到了这个问题，无论默认值是什么，定位都是默认设置的省的第一个市和第一个区

**Comment by nancy09** [comment]
发现问题在省市区的onChange调用的是col.replaceValues方法，而col.replaceValues定义的col.setValue(col.values[0], 0, true);根据省变化，市和区取的都是第一值col.values[0]，故设置了默认值，对应的市与区都是第一个值。

于是投机取巧稍微修改了sm-city-picker.js文件，改动如下：
1、在外面加了两个变量标记：
var initCityFlage = true;
var initDistrictFlage = true;

2、对onChange事件进行判断执行：
onChange: function (picker, values, displayValues) {
      var newProvince = picker.cols[0].value;
      var newCity;
      if(newProvince !== currentProvince) {
        var newCities = getCities(newProvince);
        newCity = newCities[0];
        var newDistricts = getDistricts(newProvince, newCity);
        if (initCityFlage) {
            picker.cols[1].setValue(newCities);
            picker.cols[2].setValue(newDistricts);
        } else {
            initCityFlage = true;
            picker.cols[1].replaceValues(newCities);
            picker.cols[2].replaceValues(newDistricts);
        }

```
    currentProvince = newProvince;
    currentCity = newCity;
    picker.updateValue();
    return;
  } else {
    initCityFlage = false;
  }
  newCity = picker.cols[1].value;
  if(newCity !== currentCity) {
    if (initDistrictFlage) {
        picker.cols[2].setValue(getDistricts(newProvince, newCity));
    } else {
        initDistrictFlage = true;
        picker.cols[2].replaceValues(getDistricts(newProvince, newCity));
    }
    currentCity = newCity;
    picker.updateValue();
  } else {
    initDistrictFlage = false;
  }
},
```

希望有高人有更好的方法。

**Comment by Mickey-** [comment]
不仅是省市区选择器，普通的picker添加默认 value 属性时也有这个问题，mark

**Comment by Tongym162** [comment]
动态设置value，定位都是默认设置的省的第一个市和第一个区，有什么好的解决方案没有？

**Comment by nancy09** [comment]
@Tongym162   这个bug 大神不是已经解决，关闭了吗
