### ISSUE TITLE
$.alert 在有滚动条的时候不能全部揭盖页面

### ISSUE THREAD

**Issue by ThomasLiu** [sdc-alibaba/SUI-Mobile#111]
$.alert(text, [callbackOk])

![Image of alert bug](http://7xoktu.com1.z0.glb.clouddn.com/1125.png)

**Comment by Mickey-** [comment]
贴下你的Demo地址，还有系统、浏览器型号。这边测试均没有复现

**Comment by ThomasLiu** [comment]
目前我只是在 本地 和 微信测试，mac 下使用火狐，iphone 6s下使用 微信公众号测试，我不确定我的调用方式是否正确，也贴上html 结构

![Image of alert bug](http://7xoktu.com1.z0.glb.clouddn.com/2015-11-25-14.28.17.png)

**Comment by ThomasLiu** [comment]
如果您是现在 调试的话，我可以暂时开个访问链接给您 http://fteapt1pxx.proxy.qqbrowser.cc/api/wechat/activity/5604b326432dc8b903590535

**Comment by Mickey-** [comment]
页面地址挂了..

**Comment by ThomasLiu** [comment]
QQ:553785815  现在开了，如果又挂了，你再跟我说吧

**Comment by ThomasLiu** [comment]
请问，这个问题我需要怎样解决

**Comment by Mickey-** [comment]
有没有稳定可打开的链接，issue查看不及时，临时链接经常会失效。本地测试没问题

**Comment by ThomasLiu** [comment]
在了，开启了

**Comment by Mickey-** [comment]
还是跪的。。。

![image](https://cloud.githubusercontent.com/assets/2062355/11462808/0a15a20c-9754-11e5-94bd-f995882dbae5.png)
