### ISSUE TITLE
请问router里是否有refreshPreviousPage这个方法的实现？

### ISSUE THREAD

**Issue by zhengnz** [sdc-alibaba/SUI-Mobile#118]
如题，文档中似乎没看到，请问是否能实现这个方法呢？或者是有其他方法可以实现

**Comment by Mickey-** [comment]
没有，听起来就是刷新之前页面的DOM吧，可以自己在业务逻辑触发时通过pageid自己更新DOM，也可以考虑使用`pageReinit`事件，在回到那个页面的时候更新其视图。
