### ISSUE TITLE
使用表单中的select下拉在ios下会出现弹出滚轮后自动失去焦点的问题

### ISSUE THREAD

**Issue by mnotw** [sdc-alibaba/SUI-Mobile#119]
点击select元素后，滚轮正常弹出，有时select元素会自动失去焦点，导致滚轮消失，无法进行选择内容。

相同的代码，偶尔出现。

ios7及以上版本均出现过此问题，安卓无此问题

**Comment by liunian** [comment]
@mnotw 这边暂时没有在 [demo](http://m.sui.taobao.org/demos/form/layout) 上重现。能否给下你那边可以重现该问题的页面地址或相应代码片段呢？浏览器是 safari 还是别的呢？

**Comment by mnotw** [comment]
``` html
<div class="page">
    <div class=content>
        <div class="list-block media-list" style="margin-top: 0; margin-bottom: 1.5rem;">
            <ul>
                <li class="item-content">
                    <div class="item-inner" >
                        <div class="row no-gutter" style="height: 1.5rem;">
                            <div class="col-25" style="margin-top:.4rem; width: 25%">发货方式</div>
                            <div class="col-75" style="margin-left: .5rem; width: 75%">
                                <select id="ship_together_type">
                                    <option value="offline">自己联系</option>
                                    <option value="online">在线下单</option>
                                    <option value="no_need">无需物流</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
```

@liunian 代码如上，打开环境是千牛ios端，这个问题偶尔重现

**Comment by Mickey-** [comment]
偶尔重现。。。能否协助发现、给出他必然重新的规律。 否则问题解决成本太大，会优先解决其他问题

**Comment by liunian** [comment]
@mnotw 我用你给的代码片段做了一个测试页面（稍微修改了一下 marginLeft，因为原片段中使用的 media-list 和 col-25 等会导致 select 换行看不到），同时用列表组件的推荐结构也做了一份，测试页面地址是 http://output.jsbin.com/cabikiqanu （下方有对应二维码）。

在最新版千牛 app 中，iPhone5 iOS 9.1 环境里暂时没有重现。麻烦你看看是否可以在这个 demo 中重现？

不知道会否是你那边更复杂的页面结构或功能中有了干扰，不知道你那边是否可以提供一份剥离了业务信息的可重现的 demo？

![jsbin_qr](https://cloud.githubusercontent.com/assets/646129/11490484/0baccdfa-9814-11e5-8198-52ce1f50ea25.png)
