### ISSUE TITLE
微信里，Picker组件的省市区选择，会调出系统软键盘

### ISSUE THREAD

**Issue by runtoad** [sdc-alibaba/SUI-Mobile#12]
微信里，省市区选择，会调出系统软键盘 手机：魅族mx5 android：5.0.1 微信：6.2.4

**Comment by lihongxun945** [comment]
有一个可行的解决方法，就是用一个透明的div把输入框遮住，然后调用js弹出地址选择

**Comment by runtoad** [comment]
发现整个系统的选择框都会出现这个问题，js的问题。

**Comment by osReilly** [comment]
这确实是个问题，用readonly没用

**Comment by Mickey-** [comment]
这的确会影响，直接优化下代码提个pull request吧
@osReilly @runtoad
