### ISSUE TITLE
$.init()后幻灯片配置改不了,添加了lazyload插件后,浏览器拉不到最后

### ISSUE THREAD

**Issue by jy0529** [sdc-alibaba/SUI-Mobile#125]
require(['zepto','sm','smextend','lazyload'],function($){

```
$(function(){
    'use strict';

    $.init();
});
$(".swiper-container").swiper({
    slidesPerView:1,
    centerdSlides:true,
    autoplay:3000,
    autoplayDisableOnInteraction:false,
    loop:true
});
$("img.lazy").lazyload();
```

});

这样设置后,幻灯片并不能按照我的配置来弄，例如用户拖动下一张幻灯片的时候下面的点没对应,，loop这个选项也没有实现。.加载了lazyload插件后,滑动不到最下面,。。
求帮助,目前在[我现在的项目](http://www.renren1.com)出现这样的情况,在线等,不论哪个浏览器都是这样。。

**Comment by jy0529** [comment]
是移动端的,不是PC端

**Comment by jy0529** [comment]
require(['zepto','sm','smextend','lazyload'],function($){

```
$(function(){
    'use strict';
    $(".swiper-container").swiper({
        slidesPerView:1,
        centerdSlides:true,
        autoplay:3000,
        autoplayDisableOnInteraction:false,
        loop:true
    });

});
$("img.lazy").lazyload();
```

});
去掉$.init()后,lazyload插件就没效了,求帮助

**Comment by Mickey-** [comment]
参数可以以data-*的方式放在DOM的自定义属性里。

另外在[我们Demo](http://localhost:8000/demos/swiper/) 里，在`$.init()`后再执行`$(".swiper-container").swiper({autoplay:500});`是可以生效的，你可以试一下。

所以最后还是检查下自己的代码吧

**Comment by LuoPQ** [comment]
init里面怎么配置幻灯片的回调呢
