### ISSUE TITLE
SUI 框架的 CSS 和JS 文件在哪里没找到

### ISSUE THREAD

**Issue by zacharydigital** [sdc-alibaba/SUI-Mobile#127]
SUI 框架的 CSS 和JS 文件在哪里没找到

从github的源码里没找到

http://m.sui.taobao.org/dist/css/sm.css  这个文件 

github的源码需要重新编译才能生成吗？

**Comment by liunian** [comment]
是的，源码里需要构建才会有。

如果需要直接引用，可以引用[网站](http://m.sui.taobao.org/getting-started/)上提供的 CDN 地址（https://g.alicdn.com/msui/sm/0.5.4/css/sm.min.css）
