### ISSUE TITLE
使用hash定位后，刷新页面变空白

### ISSUE THREAD

**Issue by pengliang159** [sdc-alibaba/SUI-Mobile#129]
使用hash 定位后，刷新页面变空白。

**Comment by liunian** [comment]
@pengliang159 看下结构上，以 hash 为 id 的 dom 元素的父或组级元素是否有着 page 的 class。如果是，把 hash 关联的结构移出去，可以和那个 .page 的同级或直接放到 body 下。

比如把

``` html
<body>
    <div class="page">
        ....
        <div class="page" id="related-to-hash">
            another page
        </div>
    </div>
</body>
```

改为 

``` html
<body>
    <div class="page">
        ....

    </div>
    <div class="page" id="related-to-hash">
        another page
    </div>
</body>
```

**Comment by pengliang159** [comment]
我的是  
&lt;div class="page page-current" id="page"&gt;
    &lt;header class="bar bar-nav">
        &lt;h1 class="title">无限滚动&lt;/h1>
    &lt;/header>
    &lt;div class="content infinite-scroll">
        &lt;div class="content-padded">
            content
        &lt;/div>
        &lt;div id="related-to-hash"></div>
    &lt;/div&gt;
&lt;/div&gt;
&lt;script&gt; $(dom).click(function(){location.hash='related-to-hash'})&lt;/script&gt;
总共只有一个page的class

**Comment by liunian** [comment]
@pengliang159 你的意思是，页面点击把 #related-to-hash 这个结构切换显示出来，然后刷新页面，这个时候显示空白吗？

#related-to-hash 这个是一个 page，给它加上 class="page" 看看。

或者，贴个简单的 demo 页面地址？

**Comment by pengliang159** [comment]
http://3mix8pvmg5.proxy.qqbrowser.cc/wxcar/jsp/technician/tQuestionChat.jsp?answerId=1&cn=hello&customerId=1
点击一下面的 输入框 ，然后刷新页面
