### ISSUE TITLE
0.5.4 去掉导航，下拉刷新失效

### ISSUE THREAD

**Issue by tmeme** [sdc-alibaba/SUI-Mobile#130]
导航去掉后，下拉刷新失效
![image](https://cloud.githubusercontent.com/assets/7479046/11552162/71d1de32-99bc-11e5-84da-63ddf424bba6.png)
给pull-to-refresh-content加上margin-top 至看到箭头，下拉刷新又好了
![image](https://cloud.githubusercontent.com/assets/7479046/11552183/b24392b2-99bc-11e5-9b28-b2b8cd401ab7.png)

**Comment by tmeme** [comment]
出现在chrome F12模拟器中。在手机上目前没有发现问题。

**Comment by tmeme** [comment]
![image](https://cloud.githubusercontent.com/assets/7479046/11555529/d5709ff4-99db-11e5-83a6-5e8f3c630043.png)
![image](https://cloud.githubusercontent.com/assets/7479046/11555562/17dd0012-99dc-11e5-8962-18ae24d0604b.png)
在上图结构中，随着工具栏每次切换到绑定了下拉刷新的页面，当前的页面的refresh事件 绑定+1  。

**Comment by Mickey-** [comment]
http://m.sui.taobao.org/demos/pull-to-refresh/  这个Demo能解决你的疑问吗，我断点看事件句柄并没有执行多次

**Comment by tmeme** [comment]
并不能，http://121.43.150.219:81/repo/tangli/sui/home.html  这个是我的demo。它出现了3个bug：
1.去掉导航，chrome模拟器中iphone4下拉刷新失效，手机端暂时没发现问题
2.每次切换到绑定了下拉刷新的页面，当前的页面的refresh事件 绑定+1。模拟器和手机都这样。
3.工具栏的选中样式active并不能随着工具栏切换更改，页面刷新时也不能根据hash值选中子栏。需自己额外处理。
事实上，我也没有发现绑定事件执行了多次，但一次下拉刷新触发的事件是随着切换到此页面的次数增加的

**Comment by Mickey-** [comment]
1. 手机上无问题忽略。2. 我们正在看，后面回复

关于第三点这里说下， 工具栏本身只是UI，并没有脚本逻辑。另外我们在工具栏http://m.sui.taobao.org/components/#toolbar  设计的初衷是：不同工具栏的icon链接通常代表形态完全不同的业务模块、范畴， **不要做成一个SPA应用** 。 

就是说，假如你工具栏有3个入口，那么这3个工具icon对应的链接最好是`.external`的。也就是刷新页面进入新url的形式，而不是以路由单页的形式滑页进入。可以说这3个icon对应了3个SPA链路的入口。

**Comment by xiaran113** [comment]
1.去掉导航，chrome模拟器中iphone4下拉刷新失效，手机端暂时没发现问题
这是js滚动模式下的一个bug，下个版本会修复
2.每次切换到绑定了下拉刷新的页面，当前的页面的refresh事件 绑定+1。模拟器和手机都这样。
重复触发refresh,优化，下个版本会有。你可以自己设置一个标志位控制setTimeout不会被同时触发两次，或者等下个版本
3.工具栏的选中样式active并不能随着工具栏切换更改，页面刷新时也不能根据hash值选中子栏。需自己额外处理。
这个看上面mickey的回复
