### ISSUE TITLE
字体文件的问题

### ISSUE THREAD

**Issue by jzlxiaohei** [sdc-alibaba/SUI-Mobile#134]
线上的sui.min.css，引用的字体文件的地址是`//at.alicdn.com/t/font_1433401008_2229297.eot`(以及其他格式)和工程中fonts目录下文件，是一致的吗？

我clone下来，替换成本地的fonts，全是乱码！

能不能提供一个本地构建的guide

**Comment by Mickey-** [comment]
那两者是不同的，at.alicdn.com/t/font_1433401008_2229297.eot 这些才是实际使用的

你用这些cdn的字体是不应该乱码的。

本地构建跑grunt就好了，调试的话还需要jekyll
