### ISSUE TITLE
关于`hidePreloader`行为的改变

### ISSUE THREAD

**Issue by jzlxiaohei** [sdc-alibaba/SUI-Mobile#135]
我现在线上还使用的是0.5.0的版本，今天尝试升级到0.5.4。发现`hidePreloader`的行为改变了，

之前是 把所有弹出的`preloader`关掉，现在是只关一个。导致有些界面一直有`loader`..

这个是有重大影响的改变，我看了下文档，并没见到提及，所以询问一下

**Comment by Mickey-** [comment]
造成困扰不好意思，解释一下：

首先我们并没有限定`hidePreloader`关闭的preloader的个数，依然是 **关闭所有打开的preloader** ，而是因为之前将所有`modal`类（alert,confirm,prompt,preloader等等都属于modal的继承扩展）改为独占式的了  
就是说，如果上一个modal没关闭，那么下一个modal被调用时会被排在队列里，等待上一个modal确认关闭后才会被接着打开。

所以现在已经 **不可能同时出现多个preloader** 了，如果调用了多次，后调用的会排在队列里了，这时如果接着调用`$.hidePreloader`,其实还是 **会关闭页面上打开的所有preloader** ,只不过关闭后，排在队列里的下一个preloader被展示出来，看起来好像是关闭了一个

**Comment by jzlxiaohei** [comment]
ok.理解这样方式了，但是实际使用，这样感觉很怪。。如果已经有preloader，那么新的直接丢掉感觉就比放到队列里更符合使用要求。这种一般都是全局的，有排他的性质。

这种加入队列里的方式，个人觉得用起来会造成不便和疑惑。明明全关了，却还在那里

**Comment by Mickey-** [comment]
的确，preloader不像其他modal，多个preloader本质上是没有意义的。

可否方便提交个PR给我们合并？preloader存在时再调用，判断后return掉即可

**Comment by jzlxiaohei** [comment]
不好意思，搭建本地调试环境，跑各种test，现在有点烦。

对我来说，目前完成项目最简单方式，就是把 $.openModal 这个方法覆盖掉。。后续会考虑更多加入社区，而不是只提`issue`

另外对于新的`preloader`，应该是替换，而不是把新的丢弃，这个我上面的想法有点问题。

感谢您的耐心
