### ISSUE TITLE
无限滚动问题

### ISSUE THREAD

**Issue by stuxt** [sdc-alibaba/SUI-Mobile#142]
无限滚动在iPhone4和iPad mini 上的时候有如下图的问题，导致页面不能正常滚动加载：
在滚动容器infinite-scroll上出现的是javascript-scroll。
正常的情况下是这样的：
正常的时候是native-scroll。

**Comment by Mickey-** [comment]
没看到图片，麻烦更新下

**Comment by xiaran113** [comment]
js会判断，ios6.0以下用js滚动条
