### ISSUE TITLE
没有jquery版本？

### ISSUE THREAD

**Issue by travellerwjoe** [sdc-alibaba/SUI-Mobile#143]
这让使用jquery为框架的网站额外又的引入zepto框架，就没有jquery版本的吗

**Comment by Mickey-** [comment]
zepto或jquery都只是个方便开发的工具库而已。没有严格的“是否支持”之说。

jQuery性能的确好，但体积过大，同时不完全适合移动端开发。如果是因为历史原因，那可以hack一下：

引用jQuery后，在引入sui-mobile之前，加上

```
<script>var Zepto = jQuery</script>
```

这样应该可以使用，但可能会有其他小问题

**Comment by dongfo** [comment]
http://www.wtoutiao.com/p/C62fOy.html
zepto的速度比jquery慢啊，如果说用zepto是为了体积小，那么对于性能低下的移动端来说，一个性能较低的zepto其实得不偿失。相反jquery2更适合移动端。jquery2抛弃了对IE的兼容，文件也相对较小。

**Comment by Mickey-** [comment]
@dongfo 这个问题我们也有调研过，不过权衡利弊吧。后面可能会放开工具库选型

**Comment by mxq00812314** [comment]
啥时候换可以兼容Jquery 的

**Comment by xyqfer** [comment]
可以试下 [Light7](http://light7.cn/)，兼容 `jQuery`

**Comment by twesix** [comment]
jQuery有一个防止和其他框架冲突的方法
yourName=$.noConflict();
这样依然可以使用jQuery，不过就是没有那么方便了而已

**Comment by sndwow** [comment]
建议加入JQUERY，毕竟因为几十KB的大小，让程序员修改陈旧的代码是不值得的，而且速度上JQUERY也有优势。现在都是4G网络，加载上来说也不会很慢。而且目前主流的PHP MVC框架用的都是JQUERY，要转移到zepto上肯定会有一些未知的问题。

以上，是个人目前不使用SUI的原因，持观望态度，希望能继续发展，支持！

**Comment by cwl19870312** [comment]
从以前的pc到移动 一直用jquery。。。搞个jquery 好些吧。

**Comment by haiziyhf** [comment]
picker是否可以支持地区自定义三级联动

**Comment by tyaqing** [comment]
优化一张图片就可以了。。。

**Comment by ablikim915** [comment]
为什么不用jQuery Mobile来写呢？这样多方便啊。

**Comment by 80Arrow** [comment]
$.toast 怎样多行显示

**Comment by EzekR** [comment]
不兼容jquery确实带来了很多问题

**Comment by mqhe2007** [comment]
本来还想用呢，不支持jQuery？性能和体积，我选择性能，如今网络环境下，体积算个毛。

**Comment by hechuanhua** [comment]
这年代还用zepto,从各方面来说为了一点体积用zepto都是得不偿失，而且现在大部分项目都是基于jquery，你这样的框架基本否定了很多项目

**Comment by shaoing** [comment]
支持Jquery的顶起！！

**Comment by joker-danta** [comment]
jq 在很大程度上是很多前端都离不开的东西，毕竟在前端的发展历程上jq有很大推动作用。所以我觉得这个不应该去限制是zepto还是jq，而且虽然jq大了十几kb，但是性能方面比zepto好了很多，在一定程度上如果选用zepto反而会有损失，希望阿里可以放开这点，建议使用jq2.x或者3.x版本的

**Comment by Jeasonweb** [comment]
我刚才想做一个系统，发现zepto.js请求一直报错，什么情况，zepto.js不是因为没人维护给弃掉了吗？

**Comment by luo-jy** [comment]
还没JQ版本咩？？

**Comment by ablikim915** [comment]
用微信的ui框架好，兼容性高 稳。大家可以试试weui

**Comment by lvsuming** [comment]
有vue、react版本的吗，以后可以支持不

**Comment by chengqinghuanyu** [comment]
如果使用jquery可以考虑light7，之前遇到一个问题是引入省市县级联不兼容pc的老代码，加入jquery防止冲突后又出现，路由跳转错误，费了一个下午换成light7问题解决。

**Comment by Zshiyi** [comment]
还好吧，虽然界面不算太好看，功能不算太完善，但是做些小项目足够了，<script>var Zepto = jQuery</script>？楼上的大神酱紫真的可以吗？我去试试

**Comment by 15201969086** [comment]
用zepto  ajax请求就报错，如果不用就能获取数据是为什么。。。

**Comment by boolean111000** [comment]
什么破东西，ajax请求一堆的报错

**Comment by mtsee** [comment]
gzip后，和zepto大小差距就10多KB。一个icon大小差不多，真不知道用zepto的意义在哪里？

**Comment by TPzQ** [comment]
这个ui应该已经是没有人运维了的吧

**Comment by BeHappyWsz** [comment]
刷新页面，pageInit时里面的方法怎么调用了3次？下拉刷新动作里的方法调用的次数更多都16次了？哪里没设置好呢

**Comment by BeHappyWsz** [comment]
> jQuery有一个防止和其他框架冲突的方法
> yourName=$.noConflict();
> 这样依然可以使用jQuery，不过就是没有那么方便了而已

遇到的问题：zepto.js的$.init()和引入拖拽返回按钮的jquery-ui.min.js冲突，
解决：引用zepto.js之前加入jquery.js和<script>var jq= $.noConflict()</script>，然后使用jq("#**").draggable()正常使用了。冲突的根源是$/jQuery
