### ISSUE TITLE
是否可以添加input的validate功能？

### ISSUE THREAD

**Issue by njleonzhang** [sdc-alibaba/SUI-Mobile#146]
可以检测客户的输入是否正确，并给予相应的提示。考虑提交的时候自动focus到第一个错误的input，并跳一个toast，提示是什么错误。
我之前写过一个angular的版本，仅供参考。

https://github.com/njleonzhang/angular-validate-with-toast

**Comment by Mickey-** [comment]
暂时还不会提供校验支持，目前的重心还在做好轻便精美的移动UI库上。感谢建议，未来会考虑的。
