### ISSUE TITLE
为什么没有dist文件？

### ISSUE THREAD

**Issue by YaoJingJing** [sdc-alibaba/SUI-Mobile#148]
为什么源码中没有dist文件？

**Comment by hands3dlabs** [comment]
先安装nodejs
管理员运行`cmd`，进入到项目目录
输入命令: `npm install`，等待安装完成
输入命令: `grunt`，会显示编译dist相关文件目录

回到目录下可看到dist目录就出现啦！！不谢

**Comment by Mickey-** [comment]
dist在 `.gitignore` 里，所以不会被git管理、同步到github上，执行grunt后会在本地生成dist/

原因是，开发维护时 dist/ 里的 diff 包括那些.min文件，内容太多，导致diff缓慢
