### ISSUE TITLE
v0.5.6: iphone上input type为number或email等时，点击input，FastClick报异常

### ISSUE THREAD

**Issue by kandole** [sdc-alibaba/SUI-Mobile#152]
之所以指定input type为number，是为了移动端弹出的键盘直接是数字输入界面，体验更友好。

在Chrome Console中打出的error信息：
Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
FastClick.focus @ sm.js:774
FastClick.onTouchEnd @ sm.js:1022
methods @ sm.js:536

修改方法，是不是在 sm.js 772行的if判断中加入下面的条件就可以了？
targetElement.type !== 'number' && targetElement.type !== 'email'

**Comment by Mickey-** [comment]
https://github.com/ftlabs/fastclick/issues/358

我们下个版本会修复这个报错。

**Comment by kandole** [comment]
非常感谢！

**Comment by Pakepeng** [comment]
修复了嘛？
