### ISSUE TITLE
【BUG】当选择了一个其他颜色（非默认蓝色）的主题之后，点击图标时（:active伪类）显示的颜色仍然是默认的蓝色

### ISSUE THREAD

**Issue by yyxx9988** [sdc-alibaba/SUI-Mobile#153]
http://m.sui.taobao.org/components/#colors
请选择其中一个主题，然后点击下面小图标可复现问题。

**Comment by Mickey-** [comment]
主题色切换功能马上会被删掉，用处不是很大，这个功能就不要用了吧，有需要的可以在自己的产品里定制

**Comment by yyxx9988** [comment]
嗯，不过这个我觉得挺重要的，不同的APP或网站的主题色肯定不同，还是尽量可以灵活控制吧。

**Comment by Mickey-** [comment]
对。100个app、网站可能有66种样式风格，我们之前提供的那寥寥几种主题根本无法满足需求，通常每个app自己还是得去定制一套theme.css重置MSUI的部分视觉风格。

所以干脆我们不插手这个事情，完全交给产品自己定制

额外的，压缩后的CSS体积减少了17K，很可观了。感谢支持~

**Comment by yyxx9988** [comment]
有道理，赞一个！
