### ISSUE TITLE
Firefox控制台警告

### ISSUE THREAD

**Issue by taadis** [sdc-alibaba/SUI-Mobile#155]
按官方文档加载javascript相关资源，在Firefox控制台出现如下警告：
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create zepto.min.js:2:3556

**Comment by Mickey-** [comment]
这是Zepto的源码，如果有担心，可以到Zepto官方github提个issue
