### ISSUE TITLE
$.router.loadPage('#router2'); 出现错误。

### ISSUE THREAD

**Issue by realspark** [sdc-alibaba/SUI-Mobile#162]
Uncaught TypeError: Cannot read property 'loadPage' of undefined

**Comment by liunian** [comment]
不知会否是你在载入了 msui 后又加载了类似 jQuery 这些库呢？
或者，是否给个 demo 看看？

**Comment by JSoon** [comment]
问题是这样的，如图：
![image](https://cloud.githubusercontent.com/assets/7589350/14451187/995cb154-00b7-11e6-81fb-de7407828278.png)
此时爆红：
![image](https://cloud.githubusercontent.com/assets/7589350/14451198/b0a7cbd2-00b7-11e6-8b25-338d4c2c3a66.png)

来看源码：
![image](https://cloud.githubusercontent.com/assets/7589350/14451218/d07d0972-00b7-11e6-903b-016f10b0fb8f.png)
意思就是Router的实例化是在DOM ready之后进行的，如果想要使用$.router的方法，请也要在DOM ready之后进行。

使用下图形式进行调用即可：
![image](https://cloud.githubusercontent.com/assets/7589350/14451311/b784e97a-00b8-11e6-9116-67d3f376ced4.png)
