### ISSUE TITLE
增强日历控件功能

### ISSUE THREAD

**Issue by liniu** [sdc-alibaba/SUI-Mobile#163]
日历控件可以增加一些常用功能，比如年份可以下拉选择，加一个今天按钮，设置初始化日期等

**Comment by Mickey-** [comment]
下拉选择的模式可以用[日期Picker组件](http://m.sui.taobao.org/components/#datetime-picker)

设置初始化日期功能现在就支持的：https://github.com/sdc-alibaba/SUI-Mobile/issues/123

今天按钮会高亮。
