### ISSUE TITLE
使用的一些问题反馈

### ISSUE THREAD

**Issue by xuexb** [sdc-alibaba/SUI-Mobile#164]
## 1. swipePanelOnlyClose配置值问题

看文档里是：

| 参数名 | 默认值 | 说明 |
| --- | --- | --- |
| swipePanelOnlyClose | true | 只允许滑动关闭侧栏，不允许滑动打开。 |

然后在`http://g.alicdn.com/msui/sm/0.5.6/js/sm.js`里发现默认值不是额。并且发布我明明设置了`true`页面中还可以滑动打开`侧别栏`呢

[查看代码](https://github.com/xuexb/blog/blob/master/www/static/src/wise/xuexb.js#L98-L102)
## 2. 无限滚动初始时

第一屏是后端渲染的，而当第一屏高度不够一屏时，没有触发加载下一页呢，页面显示个`loading`，必须人为的滚动下，如：[滚动问题](https://xuexb.com/?key=%E6%88%91%E6%98%AF) （请使用模拟器或者真机查看）
## 3. 页面change问题

当前页面`/1.html`，通过链接跳转到`/2.html`（有转场动画），这时：
1. 如果直接后退，会正常转场动画到`/1.html`
2. **如果刷新再退，则页面`url`更新了，页面内容没更新或者为空～**
3. **如果直接后退转场动画返回`/1.html`后再主动刷新下页面，这时再`前进`进入`/2.html`时同`#2`问题一样**

总之只要一刷新，前进、后退事件很不帅了～

---

最后赞下，真心不错。但以上不知是使用问题还是别的情况，谢谢～

[线上环境 - 请用手机模式](https://xuexb.com/)

> pc chrome和iphone6 safari

**Comment by Mickey-** [comment]
感谢使用！
1. 我们已经修正笔误，下个版本会发布。另外你设置不生效是因为，你需要在sm.js加载之前定义$.config
2. 无限滚动的页面HTML文档本身不需要把`.infinite-scroll-preloader`这个元素写到HTML里，你写进去了。并且这个组件是需要用户滚动屏幕后才触发的。
3. router的问题正在解决中 @liunian

**Comment by xuexb** [comment]
@Mickey- 至于你说的 `1.` 已经搞定了～  而 `2.` 不太明白，你说 `.infinite-scroll-preloader` 元素不在`html`里，但我发现这样的话页面就没有`loading`小标标额。还有 [无限滚动demo](http://m.sui.taobao.org/components/#infinitescroll) 里也是，如果说页面高度不够时为啥非要用户主动触发下才能加载呢～ 我试图`trigger`下`scroll`也没有触发～， `3.` 很期待～

感谢～

**Comment by Mickey-** [comment]
可以再试试看

**Comment by xuexb** [comment]
@Mickey- `3.`的问题还存在~ 并且发现后退成功后不能再前进？

扫我查看：
![image](https://cloud.githubusercontent.com/assets/3872051/11895711/d890eef0-a5bb-11e5-95ce-054eefaebba2.png)

**Comment by xuexb** [comment]
那个后退在前进在qq浏览器确实不可以，safari却可以，iphone6

**Comment by wenweih** [comment]
@xuexb 我也遇到你反馈的第一个问题：

> 1. swipePanelOnlyClose配置值问题  

然后我参考你的commit [修复侧边栏配置问题](https://github.com/xuexb/blog/commit/9e10f9bfed4c0a669bf999acba18a407ae152c28)  
但是还是报这个错误呢：`sm.self-aba9607….js?body=1:6490 Uncaught TypeError: Cannot read property 'transform' of undefined`  
错误的对应代码是 `panelOverlay.css({display: ''}).transform('');`  
麻烦帮忙解决一下，感谢。 🍺
