### ISSUE TITLE
v0.5.6: 对Router的back方法的修改建议

### ISSUE THREAD

**Issue by kandole** [sdc-alibaba/SUI-Mobile#165]
背景：
有如下页面跳转，且要求，这三个页面都可以作为入口进入。
PA -> PB -> PC

如果从PC进入，history.back()会返回进入前的页面（假设存在），所以需要在页面上增加一个返回上一页的按钮，点击后能进入PB（location.href = url）。

对于从PA一路进入到PC的情况，也希望通过点击页面上返回按钮，触发history.back()。

需求：
统一调用$.router.back(url)或在返回按钮上加入“back”class，就能达到上述效果。

修改建议：
只有stack.length > 1 时，才进行history.back()。
    Router.prototype.back = function(url) {
        var stack = JSON.parse(this.stack.getItem("back"));
        if (stack && stack.length > 1) {
            history.back();
        } else if (url) {
            location.href = url;
        } else {
            console.warn('[router.back]: can not back')
        }
    };

**Comment by liunian** [comment]
谢谢建议，[新版本的 router](http://m.sui.taobao.org/components/#router) 做了一些变更
