### ISSUE TITLE
Edge浏览器下报错

### ISSUE THREAD

**Issue by taadis** [sdc-alibaba/SUI-Mobile#166]
按照官网默认javascript cdn配置，在Firefox浏览器正常，在Edge浏览器下控制台报错如下：
SCRIPT5007: Unable to get property 'setItem' of undefined or null reference sm.min.js (10,1029)

**Comment by Mickey-** [comment]
感谢在ME的试用！

目前sui-mobile只针对 **移动端** 市场的 **主流浏览器** ，MicrosoftEdge 作为新产品目前可能还不稳定，所以短期暂不在ME上进行兼容性测试，将精力主要投入在现有问题的优化上

后期ME普及后会及时支持的
