### ISSUE TITLE
刷新后，回退停留在原页面

### ISSUE THREAD

**Issue by tmeme** [sdc-alibaba/SUI-Mobile#167]
通过router加载外部页面后，刷新当前页。回退失败
比如按以下指示。在第三个页面刷新后。回退不到首页了 。
![image](https://cloud.githubusercontent.com/assets/7479046/11716589/dcc2d0b0-9f85-11e5-8e77-2ecf24eea9b4.png)
|
![image](https://cloud.githubusercontent.com/assets/7479046/11716604/f06a49c2-9f85-11e5-9de8-99b9484d7434.png)
|
![image](https://cloud.githubusercontent.com/assets/7479046/11716627/1711052a-9f86-11e5-9c2e-c621ce14a450.png)

**Comment by tk796299** [comment]
demo 里面给.back 加上 href 是有效果的，好像只适用静态页面？
