### ISSUE TITLE
js滚动模式下，顶部无线滚动没有触发事件

### ISSUE THREAD

**Issue by noonewill** [sdc-alibaba/SUI-Mobile#168]
【首先，很好用的UI，太感谢你们了。】

提个Bug，js滚动模式，顶部无限滚动没有触发事件，auto模式可以
【HMTL代码是这样的】

<div id="page-chat-panel-content" className="content infinite-scroll-top">
    <div className="content-inner">
        <div className="infinite-scroll-preloader">加载中...</div>
    </div>
</div>

【JS事件是这样的】
$("#elementId").scroller({ type: 'js' });
$.initInfiniteScroll("#elementId");
$(document).on('infinite', "#elementId", function(){console.log("trigger");});

【然后就出问题了，而且这个时候，如果跳转到其他page的auto 下拉刷新时也会出问题，报错信息：】
Uncaught TypeError: Cannot read property 'on' of undefined          sm-extend.js:6533

**Comment by Mickey-** [comment]
可否提供一个Demo线上地址方便我们定位？另外机型、系统、版本也麻烦补充一下。

**Comment by noonewill** [comment]
Demo没有线上的，测试机是iphone6,iOS9.1。

**Comment by xiaran113** [comment]
底部无限滚动有问题么？只有顶部有问题么

**Comment by xiaran113** [comment]
我试了下$("#elementId").scroller({ type: 'js' });
$.initInfiniteScroll("#elementId");
$(document).on('infinite', "#elementId", function(){console.log("trigger");});
这样可以触发infinite事件，能否写个简单的demo呢？

**Comment by xiaran113** [comment]
@noonewill 顶部的无限滚动下个版本会发一个demo，你可以对比看看调用方式是否正确。我测试了是可以触发事件的，如果你希望帮你定位问题，希望可以发出你绑定事件那段代码～
