### ISSUE TITLE
 grunt error

### ISSUE THREAD

**Issue by scalaview** [sdc-alibaba/SUI-Mobile#169]
你好，我在运行 grunt build的时候出现下面的error，导致不能运行成功

SUI-Mobile[dev] apple$ grunt 
Loading "less.js" tasks...ERROR

> > Error: Cannot find module 'lodash'
> > Loading "autoprefixer.js" tasks...ERROR
> > Error: Cannot find module 'browserslist'
> > Loading "connect.js" tasks...ERROR
> > Error: Cannot find module 'statuses'

npm -v
2.11.3
grunt-cli v0.1.13
grunt v0.4.5

os mac 10.10.2 (14C1514)

**Comment by Mickey-** [comment]
我这边运行不会出现那些错误，看起来是一些node模块依赖问题。你试试重新npm install？

**Comment by scalaview** [comment]
我想请问一下，你的node npm 和 grunt 的版本是多好，我好重新安装环境

**Comment by Mickey-** [comment]
![image](https://cloud.githubusercontent.com/assets/2062355/11804093/de432264-a33b-11e5-87a6-8306bb3ebe88.png)

**Comment by scalaview** [comment]
好的，谢谢，是版本的问题
