### ISSUE TITLE
手动初始化顶部的无限滚动，应该怎么写？

### ISSUE THREAD

**Issue by zhang943366739** [sdc-alibaba/SUI-Mobile#170]
我用的React，所有的页面都是用自定义方式动态载入的，目前没有办法使用initPage来初始化，所以遇到了这个问题。
问题出现在初始化时，下拉刷新使用没有问题，无限滚动出了问题，提示on和off方法的调用对象未定义。
下面是初始化代码：
$.initInfiniteScroll(“#elementId”);
$(document).on('infinite', "#elementId", function(){console.log("trigger");});

这个问题用下面这个方法好像可以解决，就是在之前插入一句:
$(“#elementId”).scroller({ type: 'auto' });
但是这样，又出现了一个新问题：在使用顶部的无限滚动，并且用js滚动时，能看到滚动条，但是没有触发事件（使用auto模式没有问题，但是情况特殊，只能用js滚动）。

其实是在做一个IM聊天窗口，所以需要向上滚动加载历史聊天信息，但是auto滚动总是自动滚动到最上边，所以想着用js滚动，将位置使用bottom来定位，这样加载历史消息后 页面不会突然跳到开始位置。不知道SUI有没有其他方案可以解决这个问题。

**Comment by Mickey-** [comment]
下个版本会解决。    #168

**Comment by xiaran113** [comment]
下个版本会写一个顶部的无限滚动demo

**Comment by zhang943366739** [comment]
好的，很期待，实在太喜欢你们这套UI。
顶部的无限滚动比较简单，不过有个问题应该要注意：大部分顶部滚动加载的场景，加载内容后要定位到滚动前的位置。

**Comment by xiaran113** [comment]
会模拟微信聊天里的那种加载效果
