### ISSUE TITLE
<input type='date'>  在安卓手机微信内置浏览器中无法正确弹出日期选择框。

### ISSUE THREAD

**Issue by qizhanyu** [sdc-alibaba/SUI-Mobile#171]
测试条件：安卓版本4.3， 微信版本 6.3.8。
1、在sui框架中使用 `<input type='date'>` 标签编辑时，无法正确弹出日期选择框，而是弹出系统输入法。
在ios中或者在安卓UC浏览器测试都没有问题，只有在微信内置浏览器测试有问题。
2、在不引入sui框架的情况下直接使用最基本的`<input type='date'>`标签时，在微信内置浏览器测试也没有问题，所以排除了微信浏览器的影响。
![Uploading bug.png…]()

**Comment by liniu** [comment]
也曾经遇见过，然后把页面头部这样写就没问题，

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="format-detection" content="telephone=no">
```

**Comment by dami2933** [comment]
![Uploading QQ图片20151211145009.png…]()
我的页面头部是这样的，但还是不行

**Comment by qizhanyu** [comment]
我的页面头部是这样写的，但是还是有问题

**Comment by qizhanyu** [comment]
表单中点击日期选择框弹出系统输入法！官网示例显示都有问题。截图传不上去...
