### ISSUE TITLE
点击链接可以写data-transition效果 ,那自动跳转如何带效果

### ISSUE THREAD

**Issue by ketle** [sdc-alibaba/SUI-Mobile#172]
难道要模拟 $('#ele').click() ?

**Comment by Mickey-** [comment]
data-transition ? 我们目前并没有这个参数了吧

**Comment by ketle** [comment]
就是在window.location.href="xxx.html" 这种跳转时 有右到左滑动的效果 (类似demo里的某个链接点击后)
