### ISSUE TITLE
刷新当前页面之后返回 back 历史记录返回但是页面没有刷新，问大神模版是咋解决的

### ISSUE THREAD

**Issue by mingyili** [sdc-alibaba/SUI-Mobile#175]
我是做了一次强制刷新，SUI 示例给人的感觉也是，返回之后刷新  

```
// 刷新再后退导致无法取到state
        if (!state) return
        if (this.newLoaded) {
            this.newLoaded = false;
            location.reload();
            return;
        }
```

**Comment by Mickey-** [comment]
#167

**Comment by zhuyifang** [comment]
这是我的修改，修改的原因是：在chrome模拟器中在新页面刷新后，点击返回时，url已经变化，但内容没有加载的bug。

Router.prototype.back = function(url) {
        var stack = JSON.parse(this.stack.getItem("back"));
        if (stack.length>1) {
            history.back();
        } else if (url) {
            location.href = url;
        } else {
            console.warn('[router.back]: can not back')
        }
    };
