### ISSUE TITLE
想要实现，如果单独访问某个子页面，按返回的时候可以访问上一级，而不是浏览器历史回退

### ISSUE THREAD

**Issue by mingyili** [sdc-alibaba/SUI-Mobile#176]

**Comment by Mickey-** [comment]
浏览器上原生的返回按钮不能这么实现，会在其他情况下造成比较严重的路由混乱。

如果是你的H5 页面里的“返回”链接，你可以在业务逻辑里给他赋值一个特定url并删掉`.back`的class。条件判断处理
