### ISSUE TITLE
版本更新0.5.0后 出现几个问题

### ISSUE THREAD

**Issue by qq51755095** [sdc-alibaba/SUI-Mobile#18]
在第一个页面显示输入框，提交跳转后，输入框没有隐藏，
更新0.5.0后 iphone6plus 切换感觉很卡顿  iphone6 上没问题，

**Comment by Mickey-** [comment]
这周版本会升级到0.5.3

如果没有额外逻辑控制，已经存在的输入框的确不会隐藏。

另外这边6P测试也并没有卡顿=，= 如果后续有具体问题欢迎反馈或共建
