### ISSUE TITLE
0.4.1版本，如何实现下拉选择框，不是选日期的，需要后年带一个小三角的那种

### ISSUE THREAD

**Issue by whyhaiyan** [sdc-alibaba/SUI-Mobile#181]
如果不用框架，其实这个效果很好实现

**Comment by Mickey-** [comment]
你是说原生select吗？移动端的原生select都没有小三角那种类型，ios和android有各自的形态

**Comment by whyhaiyan** [comment]
ios和android有各自的形态？

**Comment by whyhaiyan** [comment]
是什么意思

**Comment by xiaran113** [comment]
移动端的交互中极少用下拉选择框，那是pc端的效果，ios和安卓原生的select都有各自的形态，你可以自己写个不带样式的html测试下，sui-m的select选择器并未使用自定义的样式，而是用的系统原生的

**Comment by whyhaiyan** [comment]
明白，谢谢
