### ISSUE TITLE
是否支持jquery?

### ISSUE THREAD

**Issue by kocokolo** [sdc-alibaba/SUI-Mobile#183]
项目中用到了jquery（主要是用到了amazeui），打算引入sui，在jquery or zepto有冲突，现在 amazeui是不支持zepto的。请问咱们这个以后有打算支持jquery吗？

**Comment by Mickey-** [comment]
zepto或jquery都只是个方便开发的工具库而已。没有严格的“是否支持”之说。

因为jQuery太过庞大不适合移动端开发。如果你真的想用，可以参考这个issue：https://github.com/sdc-alibaba/SUI-Mobile/issues/143
