### ISSUE TITLE
还有两个地方拖动头部或者尾部的bug

### ISSUE THREAD

**Issue by justQing00** [sdc-alibaba/SUI-Mobile#190]
在0.5.7版本中，.bar.bar-nav已经阻止了touchmove事件，下面两个
 1、.bar.bar-header-secondary
 2、.bar.bar-tab
仍然可以拖动，导致整个页面滚动的问题

["nav", "footer"].forEach这个判定不是很完整哦

**Comment by xiaran113** [comment]
下版本修复，谢谢～
