### ISSUE TITLE
能否给modal 添加个自定义的class？

### ISSUE THREAD

**Issue by IssaTan1990** [sdc-alibaba/SUI-Mobile#194]
如题，很多时候，我需要的modal 长这样
![qq 20151217175736](https://cloud.githubusercontent.com/assets/10755797/11866708/c618f59e-a4e7-11e5-8f35-96156768c42a.png)
而 alert 长这样
![image](https://cloud.githubusercontent.com/assets/10755797/11866734/f1c708ac-a4e7-11e5-806e-6b6bcee9a975.png)
可是现在modal 无法自定义，让我非常痛苦
另外请问官网上说的自定义modal 模板如何使用？
![image](https://cloud.githubusercontent.com/assets/10755797/11866752/1362b394-a4e8-11e5-91d7-3a308ec6cf3e.png)
我看了下modal.js ，貌似并没有跟template 有关
主要我现在使用的是CDN

**Comment by IssaTan1990** [comment]
主要是我现在用的cdn

**Comment by mingyili** [comment]
modal不是能自定义么，你截图上面就是
http://m.sui.taobao.org/components/#modal

**Comment by Mickey-** [comment]
@IssaTan1990 下个版本会支持在modal的跟节点上自定义添加class，本周会发布。

届时你可以根据自己的class命名空间为不同的modal追加、重置不同的样式了

P.S. 文档后面会更新。也推荐使用CDN资源。

**Comment by Mickey-** [comment]
下个版本通过`extraClass` 追加自定义class

`$.modal({extraClass:'red bg-blue',title:'test red',text:'adasdf'})`
