### ISSUE TITLE
无限滚动问题

### ISSUE THREAD

**Issue by mnotw** [sdc-alibaba/SUI-Mobile#2]
有如下场景：
html是由模板引擎生成的，将此html内容（包含<div class="content infinite-scroll">元素）放进页面正常显示，但是并不会触发infinite事件

 使用$.attachInfiniteScroll('.content')处理报错（Uncaught TypeError: Cannot read property 'on' of undefined）

先调用 $.refreshScroller()然后调用上述函数也会出现这个问题。

是因为content没有经过页面初始化的处理导致的吗？

如果是，msui有提供相关api进行处理这个问题吗？

是否有相关js api来手动初始化各个组件？

**Comment by mnotw** [comment]
@lihongxun945 help please

**Comment by lihongxun945** [comment]
我试了是可以的，你加我旺旺吧，旺旺名 任行

**Comment by shenjianhua1985** [comment]
遇到相同的问题，使用demo都无法滚动

**Comment by bihongbin3027** [comment]
我的也无法滚动 后面我自己写了其它的js解决了 谁遇到这个问题：我使用了两个侧栏，按照文档的方法使用了data-panel='{panel的选择}'来指定具体打开哪一个侧栏，但是不起作用啊，根本不出来指定的侧栏，认识出现同一个侧栏。
