### ISSUE TITLE
ajax加载页面请求头问题

### ISSUE THREAD

**Issue by linuxjcq** [sdc-alibaba/SUI-Mobile#20]
您好：
      我使用sui加载新页面的时候，get请求的头部竟然是application/json，而不是text/html，我在路由的getPage函数里$.ajax直接设置contentType也是无效，有什么办法可以解决这个问题么？
     这边我测试地址：http://mall.jcq.tbapps.cn/mall/user/test

谢谢！

**Comment by Mickey-** [comment]
地址不可访问，可以截图说明一下吗。

另外，因为MSUI的路由在ajax加载新页面的时候，并不是以HTML的形式使用新页面资源，而是将新页面当做一个普通的字符串文档，截取其`.page`部分里的字符串，添加到主页面的内容区。所以没觉的这造成了什么问题
