### ISSUE TITLE
站外链接无法打开

### ISSUE THREAD

**Issue by xialu** [sdc-alibaba/SUI-Mobile#200]
无法打开页面中a标签对应的站外链接~
javascript报错信息为不能跨域。

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Mickey-** [comment]
跳外链的链接需要加个自定义属性`external`

文档里有写的 http://m.sui.taobao.org/components/#router

**Comment by xuexb** [comment]
我感觉只添加`class`不好解决问题，因为内容里的链接是不可控的，我想的是这么干：

``` js
// 委托body,由于sm委托的是document，我们要比她早点
$('body').on('click', 'a', function(event){
    var url = $(this).attr('href');

    // 我认为这样是外链接
    if (url.substr(0, 4) === 'http') {
        event.stopPropagation();
    }
});
```

仅供参考～
