### ISSUE TITLE
page样式不显示

### ISSUE THREAD

**Issue by qinaichen** [sdc-alibaba/SUI-Mobile#203]
<div class="page">
....
</div>

定义了上面的内容，div中的内容不显示
取掉page样式类就显示了，浏览器控制台报错
Uncaught Error: can't find .page element

**Comment by anyone-yuren** [comment]
注意看官网的文档。

**Comment by Mickey-** [comment]
请先阅读文档再自己写Demo。同时参考官方Demo：http://m.sui.taobao.org/demos/
