### ISSUE TITLE
无限刷新解除绑定方法无效

### ISSUE THREAD

**Issue by lujunwei** [sdc-alibaba/SUI-Mobile#206]
解除方法直接remove是callback，而绑定方法用的是function() {
                    callback.call(this.wrapper);
                });无法对应起来

**Comment by xiaran113** [comment]
有demo吗，形容的太抽象没法复现。。

**Comment by lujunwei** [comment]
场景是使用$.detachInfiniteScroll解除无限刷新的事件不起效@xiaran113

**Comment by xiaran113** [comment]
可以的，你可以参考文档里的demo，http://m.sui.taobao.org/components/#infinitescroll

**Comment by lujunwei** [comment]
当系统版本的小于4.4.0的安卓设备和系统版本小于6.0.0的ios设备，启用js版的iscoll，因为启动了iscroll，然后你们的方法就无法对应起来，请确认在iscroll启动的情况下是否有效~我反复确认是无效的，官方的demo也是无法解绑的~@xiaran113

**Comment by xiaran113** [comment]
@lujunwei 你好，已经测试了，data-type为js的时候，有效的，你再定位下你的代码，看看是哪里出问题了～

**Comment by xiaran113** [comment]
@lujunwei 你好，已经测试了，data-type为js的时候，有效的，麻烦你再定位下你的代码，看看是哪里出问题了～

**Comment by lujunwei** [comment]
我只在demos中的无限滚动部分的addItems加了点东西去解绑，结果发现在iscroll的状态下一直没成功
function addItems(number, lastIndex) {
        // 生成新条目的HTML
        var html = '';
        for (var i = 0; i < 20; i++) {
          html += '<li class="item-content"><div class="item-inner"><div class="item-title">新条目</div></div></li>';
        }
       //这段添加的代码，请帮忙看看这段代码是否出了问题？
        var li = $(".item-content");
        if(li.length >= 20) {
          $.detachInfiniteScroll($(".infinite-scroll"));
          console.log("detachInfiniteScroll");
        }
        // 添加新条目
        $('.infinite-scroll .list-container').append(html);
      }

**Comment by xiaran113** [comment]
你这样当然不行。。。解绑事件只是off你在容器上绑定的事件，你这样，每次还是会执行addItem，里面的append还是会执行。最起码，你detach以后应该return一下～docs里的写的很清楚了![](http://gtms03.alicdn.com/tps/i3/TB1.nuXLXXXXXbmXpXXx626RFXX-829-591.png)

**Comment by lujunwei** [comment]
那我想请问，如何解绑不再执行addItem，我还是没找到文档哪里有说，请指明下，谢谢@xiaran113
