### ISSUE TITLE
picker touch穿透问题

### ISSUE THREAD

**Issue by mnotw** [sdc-alibaba/SUI-Mobile#21]
版本为0.5.0

picker调出后，触摸滑动picker的非文字部分，picker后面的内容响应了拖动，进行了滑动响应

测试环境：ios 8.4 iPhone5

**Comment by zhaorong** [comment]
版本为0.5.0

相同问题,弹出picker之后,可以上下拉动页面
只要选择了一个picker选项之后,一切表现正常

测试环境：android 4.2.2 和 海马玩模拟器
