### ISSUE TITLE
Android手机上软键盘遮盖输入框

### ISSUE THREAD

**Issue by BrainstorM1983** [sdc-alibaba/SUI-Mobile#210]
用Android(720P)手机上打开http://m.sui.taobao.org/demos/form/icon-input ，点击最后的输入框，弹出键盘，键盘此时遮盖了输入框，输入框并没有向上弹，ios则没有此问题，查了一下css，是body的overflow: hidden;造成的？

**Comment by xyqfer** [comment]
我这边用iOS 9.2 和红米（Android 4.4）的原生浏览器测试输入框均被键盘遮盖了，页面不会自动往上滚。

**Comment by xiaran113** [comment]
这个跟ios和安卓的操作系统有关，安卓下默认就是遮盖不会上滚的，sui-m并没有处理这一块逻辑

**Comment by Mickey-** [comment]
是有这种现象，系统原生特性，且并不影响功能，看了下其他app，如豆瓣等都是如此，所以先不调整
