### ISSUE TITLE
require加载$为undefined

### ISSUE THREAD

**Issue by anyone-yuren** [sdc-alibaba/SUI-Mobile#211]
![image](https://cloud.githubusercontent.com/assets/14817820/11950944/0d8bb522-a8c8-11e5-8c31-09a0f7e2dc67.png)
require加载zepto和sui为什么会出现$为undefined？

**Comment by anyone-yuren** [comment]
已解决，不好意思。我的问题。

**Comment by Amos-tanke** [comment]
你这个是啥原因？
