### ISSUE TITLE
路由-内联的新页面-示例本地不能演示

### ISSUE THREAD

**Issue by lann1986** [sdc-alibaba/SUI-Mobile#212]
有没有小白一点的演示，求指点。。Popup 也不会用.....

**Comment by Mickey-** [comment]
给出具体问题点吧，你问的这么抽象我们也不知道怎么回答你。。

**Comment by lann1986** [comment]
[demo.txt](https://github.com/sdc-alibaba/SUI-Mobile/files/70365/demo.txt)

示例里这个-路由-内联的新页面-复制到本地不能用，想知道怎么用路由内联的新页面功能。或者是Popup功能的用法，示例的代码复制到本地都不能用。是不是js初始化什么的问题？我下载了demo.js也不行。看不太懂示例，想问问怎么用。。

**Comment by Mickey-** [comment]
想在本地跑的话，参考 https://github.com/sdc-alibaba/SUI-Mobile/blob/dev/develop.md#环境 

还是比较方便的，示例其实就依赖一个demos.js ，你也可以直接参考。

路由内联页面的例子参考 http://m.sui.taobao.org/components/#router
