### ISSUE TITLE
在微信内置浏览器无法显示，如果将两个meta标签前面加上双斜杠就可以。很奇怪

### ISSUE THREAD

**Issue by McqueenLe** [sdc-alibaba/SUI-Mobile#214]
我用微信扫描二维码发现页面无法显示，但使用外置浏览器可以打开。如果在两个meta标签前面加双斜杠就可以显示。但是每次初始化的时候会先显示双斜杠，俨然这样做不科学。我的做法是在apple-mobile-web-app-capable和apple-mobile-web-app-status-bar-style这两个meta标签前面加了双斜杠(//)。
想请问为什么？怎么处理在微信无法显示的问题？

**Comment by Mickey-** [comment]
我们测试并没有这个问题，请检查代码吧还是，参考官网Demo一点点排查。

或者也可以放个链接我们看下

**Comment by web5** [comment]
我测试也是这样的

**Comment by McqueenLe** [comment]
已经解决了，其实就是js的先后顺序问题。把zepto.js放到head标签里面，把sm相关的js放到body的底部就ok了。但是我仍然对加双斜杠就可以显示感到迷惑

**Comment by web5** [comment]
@McqueenLe  既然是JS放到body后面，应该跟DOM的渲染有关，我也看了是JS报的错误，说有个layer对象为null,求官方解释

**Comment by Mickey-** [comment]
js引用都放body标签结束前，规范布局
![image](https://cloud.githubusercontent.com/assets/2062355/12089383/2c8759fc-b31f-11e5-8a05-f78f54b39e9d.png)
