### ISSUE TITLE
 $("#city-picker").cityPicker({})使用省市区选择器，如何获取选择后的省市区数据？

### ISSUE THREAD

**Issue by zxc35765441** [sdc-alibaba/SUI-Mobile#215]
<input type="text" id='city-picker'/>

<script>
  $("#city-picker").cityPicker({
    toolbarTemplate: '<header class="bar bar-nav">\
    <button class="button button-link pull-right close-picker">确定</button>\
    <h1 class="title">选择收货地址</h1>\
    </header>‘
//在这里面，有没有获取选择省市区后的数据方法；我需要将选择后的省市区数据，传回到数据库；
  });
</script>

**Comment by openks** [comment]
有两种方法 方法一：从选择器里取
$(".picker-item.picker-selected")[0].getAttribute("data-picker-value");//"四川"
$(".picker-item.picker-selected")[1].getAttribute("data-picker-value");//"成都"
$(".picker-item.picker-selected")[2].getAttribute("data-picker-value");//"青羊区"
方法二：从选后的值里取 然后用空格截取
$("#city-picker").val();//"四川 成都 青羊区" 以空格分开的

**Comment by zxc35765441** [comment]
好的，谢谢了，我先去试一试

**Comment by zxc35765441** [comment]
我使用了第一种方法：报错不支持getAttribute这个方法，打印查了一下，发现支持attr的方法。
现在的问题是，这两种方法都需要一个前提，我要在选择后，触发去调用这两个方法；

开始我给确定按钮加了“click”，实际上，没有走我的click事件；
$("#city-picker").cityPicker({
			 toolbarTemplate: '<header class="bar bar-nav"><button class="button button-link pull-right close-picker" id="yes">确定</button><h1 class="title">选择地区</h1></header>'
		  });
		 $("#yes").on('click',function(){//程序根本不走我加的这个事件
			 console.log($("#city-picker").val());
			 console.log($(".picker-item.picker-selected").attr("data-picker-value"));
		  });
我不知道在哪里加查询的前提；

**Comment by Mickey-** [comment]
多谢 @openks ！的确选后的值就在对应的input里，直接读就可以了@zxc35765441
