### ISSUE TITLE
安卓4.1.1下横向滚动条问题

### ISSUE THREAD

**Issue by 7528065** [sdc-alibaba/SUI-Mobile#219]
安卓4.1.1下，在content里，如果还有容器有横向滚动条的话，无法滚动。但是把content设置为overflow:hidden的话，就可以滚动了……能破吗？

**Comment by xiaran113** [comment]
因为4.1.1下使用的是js滚动条，iscroll默认是禁用横向滚动条的，初始化滚动条的时候加个参数就好了scrollX: true，你可以自己先加，也可以等下个版本我们会加上～

**Comment by xiaran113** [comment]
不过要注意，即使iscroll支持了横向滚动条，也满足滚动容器的宽度大于屏幕宽度这个条件，才能触发横向滚动。可能需要手动设置下容器宽度，可参考http://lab.cubiq.org/iscroll5/demos/horizontal/

**Comment by 7528065** [comment]
再请教一下，那在安卓4.4.0以下的时候，是不是没办法开启原生滚动条？试过，好像不行，一直被强制js了

**Comment by 7528065** [comment]
还有就是，content容器横向滚动条开启我是知道的，我的目的是想在，content容器里的某个容器再开启横向滚动，这时候好像就有问题了。

**Comment by xiaran113** [comment]
安卓4.4.0以下的时候，是不是没办法开启原生滚动条？试过，好像不行，一直被强制js了——是的这是bug，非常感谢，下面会更正~至于局部横向滚动，这个需要自己布局自己写，js模式下你可以参考下http://lab.cubiq.org/iscroll5/demos/event-passthrough/ 这个demo，需要new一个局部的滚动条。
