### ISSUE TITLE
0.5.0版本在UC浏览器上的问题

### ISSUE THREAD

**Issue by walli1990** [sdc-alibaba/SUI-Mobile#22]
测试发现在UC浏览器下，写一个最简单的页面，引入的是0.5.0的css与js，但是引入min的css 列表的样式不对， 向右箭头在左边，但是引入完整版的css 就不会有问题。其次是列表的 <a>标签连接失效，点击完全没反应

**Comment by Mickey-** [comment]
请提供一下截图说明，并尝试0.5.2版本是否有问题。
