### ISSUE TITLE
popup 与 $.showPreloader() 冲突

### ISSUE THREAD

**Issue by jxf114208** [sdc-alibaba/SUI-Mobile#220]
当在popup里面使用$.showPreloader()时，当首次open popup时，popup打开的同时，Preloader和popup都是闪一下就关闭了，随后再次打开就正常了。

使用Chrome Version 47.0.2526.106 (64-bit), ubuntu 14.04,使用SUI的0.5.8

**Comment by xiaran113** [comment]
请问有demo吗
