### ISSUE TITLE
safari隐私模式下抛错

### ISSUE THREAD

**Issue by wormcc** [sdc-alibaba/SUI-Mobile#222]
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

setItemjs:9:1506
bjs:9:1506
（匿名函数）js:9:6940
（匿名函数）zepto.min.js:1:5785

**Comment by Mickey-** [comment]
浏览器隐私模式下禁止了本地存储的操作导致的。这种情况不用太在意

**Comment by wormcc** [comment]
但是会造成页面无法渲染的问题，在safari下，只能显示空白页面。

**Comment by Mickey-** [comment]
恩。。是应该有问题，因为路由功能完全挂了。不过目前不考虑支持隐私模式的访问，否则很多事儿做不了了

**Comment by wormcc** [comment]
谢谢！:）
