### ISSUE TITLE
用datetime-picker，在安卓上会弹出默认输入法，如何阻止？

### ISSUE THREAD

**Issue by mengtingluo** [sdc-alibaba/SUI-Mobile#226]

**Comment by xiaran113** [comment]
这个bug之前应该修复了，但是在label和input之间的交界线，点击的话还是会弹出输入法。只在微信中会有这个问题。#12  #60 如果还有别的问题请留下你的测试机型和操作系统版本号，谢谢～

**Comment by mengtingluo** [comment]
就是微信中。。设置了readonly也没用

**Comment by mengtingluo** [comment]
我是努比亚z9max， 安卓5.0.2,点击输入框就会弹出输入法

**Comment by xiaran113** [comment]
你好，请确认你使用的是最新版本的sm.js，然后这个问题应该没有的。。我测试了nubia z9mini 安卓5.0.2，没有这个问题
