### ISSUE TITLE
0.5.0 无限滚动问题

### ISSUE THREAD

**Issue by walli1990** [sdc-alibaba/SUI-Mobile#23]
完全从官网copy的例子，但是 $(document).on('infinite', '.infinite-scroll', function () {})并不触发事件

**Comment by senro** [comment]
我也遇到此问题，求解决啊！

**Comment by senro** [comment]
官网demo的都不行啊，并且有些demo还有报错啊！

**Comment by wenzhixin** [comment]
需要跟 `content` 一起使用才能触发该事件。

**Comment by Mickey-** [comment]
这边测试是可以的，注意你们的页面有没有`$.init()` 初始化。

官网Demo http://m.sui.taobao.org/demos/infinite-scroll/ 也是正常的，如果还不正常请贴Demo在线地址

**Comment by yunnian** [comment]
我也遇到这样的问题 原来 多了个content 标签

**Comment by linheqin** [comment]
我也是这个问题啊，咋解决啊http://demo.cjqyj.com:1194/sp/cn/index.html
