### ISSUE TITLE
sui mobile 移动端无法使用sui里js方法 $.alert()

### ISSUE THREAD

**Issue by jaryun** [sdc-alibaba/SUI-Mobile#231]
引了如下css和js文件。但一直无法用$.alert()和$.showPreloader()方法。一直报错：Uncaught TypeError:$.alert is not a function。
请问是不是少引了什么文件啊。希望哪位好心人能帮忙解答一下。谢谢
g.alicdn.com/msui/sm/0.5.8/css/sm.min.css
g.alicdn.com/msui/sm/0.5.8/css/sm-extend.css
cdn.bootcss.com/jquery/2.1.4/jquery.js
g.alicdn.com/sj/lib/zepto/zepto.js
g.alicdn.com/msui/sm/0.5.8/js/sm.js
g.alicdn.com/msui/sm/0.5.8/js/sm-extend.js

**Comment by xiaran113** [comment]
#143 不要引jquery试试，会不会两个冲突了

**Comment by xiaran113** [comment]
http://www.css88.com/doc/zeptojs_api/#modules 可以看看这些模块有没有你需要的，引入就好了

**Comment by Mickey-** [comment]
浏览器是否有报错，参照Demo 编写 http://m.sui.taobao.org/demos/modal

**Comment by maoyuanchen** [comment]
sm.js 的引用顺序导致$.alert()无效，不要放在`<head>`中引用，应放在`<body>`结束前引用

**Comment by zxgiot2014** [comment]
楼上说的对！感谢 @maoyuanchen
