### ISSUE TITLE
提供一个针对于移动端的sku toolkit

### ISSUE THREAD

**Issue by qinerg** [sdc-alibaba/SUI-Mobile#233]
能否提供一个针对于移动端的toolkit，直接使用可视化拖拽来构造页面，降低使用成本？

**Comment by jaryun** [comment]
你好，sui mobile 移动端无法使用sui里js方法$.alert()。sm.min.css，zepto.min.js，sm.min.js都引了，你知道是怎么回事吗。谢谢你了

**Comment by Mickey-** [comment]
移动端暂时官方不会出toolkit，不好意思。
