### ISSUE TITLE
多次通过ajax加载同一个页面会出现重复的html节点

### ISSUE THREAD

**Issue by rolandzhang** [sdc-alibaba/SUI-Mobile#235]
如果两个页面，都有<a href="/a"> Page A </a> 和<a href="/b"> Page B</a> 的页面导航，在这两个按钮之间反复点击，页面上的.page节点在不断增加，建议用url做个索引判断吧。
额外说明：发生在没有使用back和external的情况下，不使用back的目的是为了让两个页面都可作为入口点。

**Comment by rolandzhang** [comment]
额外说明：在没有使用back和external的情况下，不使用back的目的是为了让两个页面都可作为入口点。

**Comment by xiaran113** [comment]
这个是旧版路由机制引起的，新版路由机制会解决这个问题。近期内会发布

**Comment by huge18** [comment]
此问题比较影响使用，之前也提过，坐等新版本哈，辛苦！

**Comment by jinjingmail** [comment]
我也发现这个问题了，准备上来发issue呢。
新版本是什么时候？可能等不了了，有什么方法快速解决吗？

**Comment by liunian** [comment]
changed in ce7339724a1bb486c508a885f06ab354f36cc8b9
