### ISSUE TITLE
工具栏多次点击之后页面不加载

### ISSUE THREAD

**Issue by Liu-xu-dong** [sdc-alibaba/SUI-Mobile#237]
我工具栏有两个选择，分别在a标签href给的不同路径，开始时候，可以跳转页面，多次点击之后，不跳转且还显示加载成功页面

**Comment by xiaran113** [comment]
请给个demo吧

**Comment by Liu-xu-dong** [comment]
@xiaran113 这，，，它也不是第一次点击就不行，是多点几次以后，就出问题。我需要提供什么？截图还是源码？

**Comment by Liu-xu-dong** [comment]
@xiaran113 在其他浏览器的测试没有这个问题，我在微信浏览器测试有问题。谢谢了

**Comment by xiaran113** [comment]
http://m.sui.taobao.org/faq/#bar-tab 你试试加个external这个类，还会有这个问题吗？

**Comment by Liu-xu-dong** [comment]
@xiaran113 这个类本来就有，这个问题是我多次快速点击会出现，我试着换种思路做，真心感谢

**Comment by Liu-xu-dong** [comment]
![image](https://cloud.githubusercontent.com/assets/16459556/12017222/11879454-ad8f-11e5-9177-1ea490343a0c.png)
![image](https://cloud.githubusercontent.com/assets/16459556/12017232/1e3be286-ad8f-11e5-96aa-fb2d35a421bd.png)
这两个页面的代码，active分别在不同的class里，在pc端chrome模拟器和手机端的其他浏览器都没事，但是在微信自带的浏览器里，连续点击五六次（交替点击），就会出现不动的情况，此时浏览器的加载进度仍然显示加载完成，刷新以后就会好。有时候点击三次都不行

**Comment by Mickey-** [comment]
点击工具栏只是普通的链接跳转，之后页面也刷新了，sui-mobile并没有介入做什么，可能是微信内置webview的问题

**Comment by Liu-xu-dong** [comment]
@Mickey- 问一个特别小白的问题，工具栏按钮我没有给active类，href属性给#,此时按住按钮，按钮还是会变蓝，松开就变回正常。我没有写关于工具栏的js。只在手机端有这个问题，pc模拟器没有。点击变色是不是内置的js就有？

**Comment by Mickey-** [comment]
点击变色不是js的影响，而是css，你按住后触发了样式的active态。。松开后就没了，因为href是‘#’，相当于进入了一个锚点，页面也就没有刷新了

**Comment by Liu-xu-dong** [comment]
@Mickey- 我找到关于微信里面多次点击不能正常跳转的问题了，我把所有的代码都屏蔽，只留两个A标签，然后一行一行解开测试。当解开<meta name="viewport" content="initial-scale=1, maximum-scale=1">这行代码的时候，微信浏览器就不能正常工作了。
![image](https://cloud.githubusercontent.com/assets/16459556/12028588/70169dfa-ae14-11e5-961e-fe6f14fa8f2c.png)

**Comment by Mickey-** [comment]
是说你之前的代码里漏了这行meta？

**Comment by Liu-xu-dong** [comment]
@Mickey- 不是，加上这行meta，就不能正常跳转（点击多次），当我把这行屏蔽以后，微信浏览器就可以正常工作。这个问题只出现在微信浏览器中。

**Comment by Mickey-** [comment]
我们依然没在微信里发现这个问题。

另外显然viewport是移动开发非常重要的meta，不可能直接去掉，不知是不是微信webview触发了什么策略导致的问题。

**Comment by Liu-xu-dong** [comment]
@Mickey- 非常感谢您的耐心帮助，刚刚查阅一些资料，这个问题是QQ浏览器不兼容viewport导致。微信内核也是QQ浏览器。
![image](https://cloud.githubusercontent.com/assets/16459556/12028685/3a62d15e-ae16-11e5-8497-f79e62cfce4e.png)
再次感谢您的帮助。

**Comment by Mickey-** [comment]
应该的，也感谢支持，后面也期望能一起维护更新：）

**Comment by terminatorheart** [comment]
@Liu-xu-dong 我也碰到了这个问题，但是查阅的资料很少讲到这个问题，不知道您有没有合适的方案

**Comment by terminatorheart** [comment]
@Liu-xu-dong 而且我使用的时候，测试并不是跟meta中的viewport那一句设置相关

**Comment by Liu-xu-dong** [comment]
@terminatorheart 我后来解决了这个问题，我在进入的时候，使用重定向，多了一层，我不知道是什么原因导致没有这个问题，但确实解决了。我的QQ ： 864292285 ，方便的话，可以QQ聊这个问题

**Comment by terminatorheart** [comment]
@Liu-xu-dong 好的，昨天多次测试后，基本可以肯定是微信浏览器自身问题，我实验过不使用sui框架，简单的两个页面链接之间互相跳转，在第二次进入一个页面的时候，就重现出来问题了，
至少有两位童鞋应该也碰到了这个问题，相关问题资料如下： 
[http://www.foreverpx.cn/2016/02/03/android-location/](http://www.foreverpx.cn/2016/02/03/android-location/) 
[http://www.w3cfuns.com/notes/24830/9ff682972fd3fdfaf94a698815d6d6b5.html](http://www.w3cfuns.com/notes/24830/9ff682972fd3fdfaf94a698815d6d6b5.html)
根据第一个链接中童鞋提供的资料，我实验性的修改了7840-7846行代码（0.6.2版本）如下 ： 
`

```
if (!filterResult) {                                                                         
    window.location.href = e.currentTarget.href + '?v=' + new Date().getTime();     
    return;                             
} 

if (isInRouterBlackList($target)) {      
    window.location.href = e.currentTarget.href + '?v=' + new Date().getTime();     
    return;                                                                                  
} 
```

`
然后解决了这个问题，但是目前我手头设备有限，测试还不够充分，不敢贸然提交pull request，如果还有更多人测试出现这个问题，欢迎补充在下面，目前已知出现了这个问题的设备有：
mx4，HTC D816v，华为P8青春版，红米note3，sony Z2
