### ISSUE TITLE
关于基础组件日历部分收起体验问题

### ISSUE THREAD

**Issue by Liu-xu-dong** [sdc-alibaba/SUI-Mobile#238]
我的网页是一个表单，有不少input标签，日历部分点开以后，想关闭只有点击空白和点其他日期，因为我的表单比较长，空白的地方比较少，而且日期我不想改成其他时间，可不可以加一个关闭日历组件的按钮？

**Comment by Mickey-** [comment]
额，这是个优化点，不过目前的设计方式没有地方加入关闭按钮了。

另外用户可以通过点击header bar或其他空白区域关闭日历。或者你们增加表单行间距也可以绕过这个问题。
