### ISSUE TITLE
有没有推荐的表单验证插件

### ISSUE THREAD

**Issue by longjianghu** [sdc-alibaba/SUI-Mobile#239]
前端功底弱，能不能推荐一个可用的表单验证插件？

**Comment by Liu-xu-dong** [comment]
validate jquery，我以前在pc端用这个，不知道移动端合不合适。

**Comment by Mickey-** [comment]
表单验证sui-mobile并没有涉足，自选即可。你在社区里搜索，找个star高的基本不会太差。

纯逻辑验证我觉得PC\移动不会有太大冲突
