### ISSUE TITLE
日期时间控件，第一次无法确认，第二次变成1950年

### ISSUE THREAD

**Issue by linzziy** [sdc-alibaba/SUI-Mobile#24]
日期时间控件问题。
第一次无法确认，text框没有值.
第二次变成1950年01月01

**Comment by linzziy** [comment]
光标在其他text，不自动隐藏系统键盘。

**Comment by Mickey-** [comment]
你可以发一个PR贡献进去：D

**Comment by smanor** [comment]
同问

**Comment by Mickey-** [comment]
0.5.2 这个问题还有吗，另外确认下是日期时间的picker组件，不是日历组件是吧？

我们这边没有复现这个问题，麻烦补充下，或者贴上问题Demo地址

**Comment by smanor** [comment]
http://web.cnvp.com.cn/cbd/2015/sui/leave-new.html

点击请假时间、结束时间

**Comment by Mickey-** [comment]
尝试了这边的ios和android，都没有复现这个问题
