### ISSUE TITLE
把sui mobile的案例下载下来不能正常显示

### ISSUE THREAD

**Issue by jaryun** [sdc-alibaba/SUI-Mobile#240]
我在https://github.com/sdc-alibaba/SUI-Mobile/tree/dev 这里面下载了案例，但打开后页面完全就乱了，页面上的事件也不能触发。请问该怎样正确下载完整的案例呢。谢谢了！！！！

**Comment by Mickey-** [comment]
https://github.com/sdc-alibaba/SUI-Mobile/blob/dev/develop.md

安装好jekyll和依赖，grunt server就可以了

**Comment by jaryun** [comment]
谢谢
