### ISSUE TITLE
使用基础组件中的路由功能有一些问题

### ISSUE THREAD

**Issue by Liu-xu-dong** [sdc-alibaba/SUI-Mobile#243]
我在使用路由功能（ajax)的时候，加载的页面需要怎么的格式？一个完整html页面，还是一个.page的div？我想做成的效果是相当于修改了旧page中的header部分和content部分。工具栏部分保持不变。这个可以用路由功能实现吗？

**Comment by Liu-xu-dong** [comment]
这是ajax之前，有一个page
![image](https://cloud.githubusercontent.com/assets/16459556/12030912/9ca2f536-ae40-11e5-9624-32f4326812ec.png)
然后，
![image](https://cloud.githubusercontent.com/assets/16459556/12030924/be827366-ae40-11e5-8b0c-4396f116ad9d.png)
加载ajax，导致
![image](https://cloud.githubusercontent.com/assets/16459556/12030929/defc7772-ae40-11e5-9f19-81c2a8fb15db.png)
出现三个page，其中第三个是仅有工具栏，但是覆盖了页面，第二个是我期望的div。
这是我ajax加载页的代码。
![image](https://cloud.githubusercontent.com/assets/16459556/12030944/1a738aac-ae41-11e5-8ded-088a13c67808.png)

**Comment by Mickey-** [comment]
router本周会放出一个alpha版更新，到时可以关注下

**Comment by Liu-xu-dong** [comment]
好，我不知道href该怎么写，看文档是这种类型这样的写法，
![image](https://cloud.githubusercontent.com/assets/16459556/12031434/dd9e8d92-ae46-11e5-86ba-63ea452885b3.png)
这个是按照文件相对路径和文件名设置的吗？我用的后端是laravel框架，也有自己的路由系统，有点懵了。

**Comment by Mickey-** [comment]
href 可以就按照相对路径写，能找到对应的模板文件即可，sui-mobile的路由会去ajax加载页面

**Comment by liuyatao** [comment]
@Mickey-  模板文件是什么  java 中jsp做为模板文件  但是加载失败 只有html

**Comment by Liu-xu-dong** [comment]
@liuyatao 这个还是用跳转吧，现在我放弃路由功能了

**Comment by liuyatao** [comment]
@Liu-xu-dong  谢谢提醒  我这块路由也出现了一下问题  很纠结很谈的蛋疼
