### ISSUE TITLE
ajax router 刷新当前这个ajax加载 的router

### ISSUE THREAD

**Issue by hawx01** [sdc-alibaba/SUI-Mobile#254]
请问下我想刷新 下当前ajax加载 的router界面 ，就是重新加载 ，有相关api吗，比如$router.reload(url)这样的。。
我目前 的做法 是记住这个url,在某些操作之后先调用 $.router.back()，然后$.router.loadPage(myurl);
这样的效果就是页面上看到一次返回，然后打开这个router,而不是当前刷新 ，体验不太好。

**Comment by MaZhaolin** [comment]
我也遇到了同样的问题，请问你是怎么解决的？
