### ISSUE TITLE
工具栏遮住content底部

### ISSUE THREAD

**Issue by hawx01** [sdc-alibaba/SUI-Mobile#260]
工具栏遮住content和滚动条底部，在下拉滚动载时就遮住了加载动画，要怎么设置滚动条才可以 防止这样，用了refeshscroller好像也没有用。安卓5.1，chrome浏览器。

**Comment by xiaran113** [comment]
贴下你的html代码吧，看下你的代码结构，或者给一个demo

**Comment by hawx01** [comment]
问题好像暂时解决 我把工具栏代码放在header之后 ，把content放在工具栏之后 就好 了。。我还以为工具栏和content没有顺序的，只要是同级就行了。。。

**Comment by xiaran113** [comment]
你的工具栏是放在底部还是顶部？遮住的是顶部还是底部的加载动画来着？

**Comment by hawx01** [comment]
之前 工具栏标签代码放在<div class='content'>的后面，工具栏在底部，肯定就遮住了底下的加载动画，就是滚动 条滚动到工具栏里边屏幕最下边去了

**Comment by hawx01** [comment]
放在div class='content'的后面，现在按<header> <nav><content>的顺序好像就没问题了

**Comment by hawx01** [comment]
按header nav  content的顺序就没问题了
