### ISSUE TITLE
$.router.loadPage(''); 出现错误

### ISSUE THREAD

**Issue by jaryun** [sdc-alibaba/SUI-Mobile#266]
Uncaught TypeError: Cannot read property 'loadPage' of undefined
没有引其它类似jquery的库。谢谢

**Comment by liunian** [comment]
麻烦确认一下是否像[示例代码](http://m.sui.taobao.org/getting-started/)中那样引入了 zepto 和 sui 的 js

**Comment by JSoon** [comment]
见 [#162](https://github.com/sdc-alibaba/SUI-Mobile/issues/162)
