### ISSUE TITLE
浏览器回退需要点击两次

### ISSUE THREAD

**Issue by Mrlilili** [sdc-alibaba/SUI-Mobile#27]
RT，点击两次才能完成回退操作

**Comment by wmz0806** [comment]
我也遇到这个问题， 修改了下源码， 目前还没有遇到什么问题

【update in 2015.10.27】**以下方法已被证实有问题**
1. 首先：（大概7252行）

``` javascript
    var state = history.state;
    if(!state) {
      var id = this.genStateID();

       // 此部分注释
      //this.pushState(location.href, id);
      //this.pushBack({
        //url: location.href,
        //pageid: "#" + currentPage[0].id,
        //id: id
      //});

      this.setCurrentStateID(id);
    }
```
1. 大概7351行 修改为

``` javascript
  Router.prototype.back = function(url) {
      var stack = JSON.parse(this.stack.getItem("back"));
      if(stack.length) {
        history.back();
      } else if(url) { //判断了下url的值
        location.href = url;
     }
  };
```
1. 大概 7387 行 修改为

``` javascript
Router.prototype.onpopstate = function(d) {
    var state = d.state;

    if(!state) {//刷新再后退导致无法取到state
      this._back(); //主要添加这句代码
      return;
    }

  //......
}
```

**Comment by Mrlilili** [comment]
thx,快过1个月了终于有人回答，感动哭，我最后的解决方案也是把整个router给注释掉了

**Comment by wmz0806** [comment]
我也最近 用到这个框架玩玩 发现这个坑

**Comment by Mickey-** [comment]
任何场景都要点两次才能后退吗？是不是需要满足某种情况？我的场景点一次就可以的

**Comment by Mrlilili** [comment]
你做的是单页应用不？  单页应用返回不会出现两侧后退的问题，其它都会出现

**Comment by wmz0806** [comment]
就是 第一 进入页面会 pushState 一个当前浏览器的 地址进history  意思就是 第一次进入 就能后退 如果这时候用户点了后退 后面所有的 后退都会失效

**Comment by Mickey-** [comment]
是的，这边SPA应用都OK，添加external展开成多页后出现了这个问题。  
 @w353284782  这样改后单页应用的history机制会受影响吗,建议也测试一下。  

都OK的话连着注释发一个PR共建吧，回归确认后我们merge进来：）

**Comment by djfly** [comment]
这bug都没人管吗？我也遇到这个问题，用了楼主的代码也不管用

**Comment by openks** [comment]
@djfly 直接使用 location.href 算了

**Comment by djfly** [comment]
location.href 必须要先存下上一页url吧？

**Comment by Mickey-** [comment]
近期会修复，方法可能不尽完善，有时间的也请协助一起review。欢迎提供建议或PR
#52 

P.S. @w353284782 你的方法会导致SPA应用的路由问题

**Comment by Mickey-** [comment]
修复了有一阵了。。忘了关联issue，这里补一下，请使用0.5.2版本，还有问题欢迎提出
