### ISSUE TITLE
router:ajax加载新页面再返回，之前页面可能刷不出来

### ISSUE THREAD

**Issue by 52fhy** [sdc-alibaba/SUI-Mobile#271]
ajax请求子页面，子页面更新重新加载后，再点击返回，发现原来的父页面加载可能会出问题：例如url已经返回正确了，还是显示子页面的内容。

版本：0.5.8

**Comment by shenfusheng** [comment]
点击返回之前页面是空白页的概率还挺大的，经常碰到，希望SUI团队能尽快修复这个BUG

**Comment by 52fhy** [comment]
类似的问题在[#66](https://github.com/sdc-alibaba/SUI-Mobile/pull/66)、[#52](https://github.com/sdc-alibaba/SUI-Mobile/pull/52)也有网友反映。与网友`zhengnz`和 `jzlxiaohei`说的问题相似。

**Comment by Mickey-** [comment]
0.6.1还有这个问题吗

**Comment by shenfusheng** [comment]
最近更新到0.6.1，暂时没发现点击返回出现空白页的现象，还有这个问题的看看是不是已经更新为最新版本

**Comment by Mickey-** [comment]
0.6.x着重更新了路由体系，所以有少许非向下兼容，还请升级体验
