### ISSUE TITLE
0.6.1 getting-started 不能正常运行

### ISSUE THREAD

**Issue by jununx** [sdc-alibaba/SUI-Mobile#278]
http://m.sui.taobao.org/examples/getting-started/

**Comment by hisune** [comment]
+10086

**Comment by Mickey-** [comment]
恩，只更新了 http://m.sui.taobao.org/demos/ 的HTML结构

http://m.sui.taobao.org/examples/getting-started/ 的还没全部同步完，参考先看Demo吧，这几天更新掉

**Comment by jununx** [comment]
感谢 - -

**Comment by Mickey-** [comment]
同步完成
