### ISSUE TITLE
picker 

### ISSUE THREAD

**Issue by zhangjian8652** [sdc-alibaba/SUI-Mobile#279]
picker如果能改成自定义取值就好了，就是我可以随意open，close，不需要绑定在某个input上，然后取值放到任意表单元素。说白了就是有个回调onconfirm 类似这样。

**Comment by zhangjian8652** [comment]
还有就是$("#xxx").click(function(){
    $("#picker-name“).picker("open");
})；
会在回调方法执行完后close掉。

**Comment by Mickey-** [comment]
你可以通过

```
$("#picker-name").picker("open");
$("#picker-name").picker("close");
$("#picker-name").picker("setValue", ["2012", "12", "12"]);
```

来人工操控Picker，在不同的时间执行自有的业务逻辑

其余你反应的改良功能后续精力允许后会加上，如果你的思路比较清楚的话，建议提交PR参与共建，非常欢迎哈
