### ISSUE TITLE
数字都出现toast提醒，还是乱码？

### ISSUE THREAD

**Issue by jay0199312** [sdc-alibaba/SUI-Mobile#280]
数字都出现toast提醒，还是乱码？是没有初始化吗

**Comment by Mickey-** [comment]
数字被识别为可拨打的电话号码变成链接，但链接被路由劫持。

禁用数字自动识别为电话号码：http://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari
