### ISSUE TITLE
请问SUI对微信内置浏览器的支持怎么样？

### ISSUE THREAD

**Issue by njleonzhang** [sdc-alibaba/SUI-Mobile#282]
看了一些移动前段框架，SUI即轻巧又功能齐全，同时自身还包含了自适应和点击延迟等一些问题的解决方案。想使用SUI来个公众微信号的SPA，请问是否有先驱者？坑大不大。。。

**Comment by Mickey-** [comment]
安卓微信本身的webview是个坑，之前修复过几个安卓微信的问题，也有其他团队用来做微信公众号应用。

大问题没有，你也可以在微信里扫码看Demo，小问题不敢保证完全没有。

框架思路上是支持微信的

**Comment by njleonzhang** [comment]
感谢回答，微信webview确实是个大坑。。。。
