### ISSUE TITLE
手机百度安卓版本，版本号:7.0，picker弹出后不能滑动！！

### ISSUE THREAD

**Issue by shenfusheng** [sdc-alibaba/SUI-Mobile#283]

**Comment by Mickey-** [comment]
官网示例是可以的，先仔细阅读文档，也给一下问题页面的链接

**Comment by shenfusheng** [comment]
用你们官网实例在手机百度上还是不能滑动，手机为魅族MX4，手机百度版本号:7.0，其他手机浏览器则没有问题，你可以自己测试一下

**Comment by Tongym162** [comment]
我也是，在安卓4.2的手机，不能滑动，有什么解决方案没有

**Comment by hzhla** [comment]
我也是啊，不能滑动，还有关闭后，会刷新页面，很奇怪

**Comment by hzhla** [comment]
是不是浏览器版本的问题？！

**Comment by hzhla** [comment]
是不是跟
浏览器是否支持
transform: translate3d  这个有关系？
我下载了个新的chorme，我发现是可以的

**Comment by hzhla** [comment]
Internet Explorer 10、Firefox、Opera 支持 transform 属性。
Internet Explorer 9 支持替代的 -ms-transform 属性（仅适用于 2D 转换）。
Safari 和 Chrome 支持替代的 -webkit-transform 属性（3D 和 2D 转换）。
Opera 只支持 2D 转换。

**Comment by hzhla** [comment]
百度浏览器升级到 7.2就好了，应该是css3的新特性问题，大家可以试试

**Comment by xiefangzhenz** [comment]
酷派带的浏览器不可以滑动。。。

**Comment by xiefangzhenz** [comment]
还有什么解决办法吗。。。。安卓webview是不能升级的，不能滑动
