### ISSUE TITLE
back后记不住滚动条的位置

### ISSUE THREAD

**Issue by elvizlai** [sdc-alibaba/SUI-Mobile#285]
按照demo中的实例，返回后，记忆不住滚动条的位置

**Comment by xiaran113** [comment]
你好，请问有demo嘛？我这边尝试了下，能记住，你测试的机型和操作系统是？

**Comment by alex1987214** [comment]
这是因为 0.6.1 的更改，清空了dom
我的解决方案是 ajax加载 通过内联的方式切换场景
实际效果来看还可以

**Comment by Mickey-** [comment]
下个版本会支持后退记住位置

**Comment by alex1987214** [comment]
https://github.com/sdc-alibaba/SUI-Mobile/issues/320

那我这个问题 可以解决了 ，不用再 写那么多 代码了

**Comment by xiaran113** [comment]
@alex1987214 下版本所有使用路由的页面都支持后退记住位置，不局限于内联页面

**Comment by alex1987214** [comment]
@xiaran113  知道了 谢谢。。其实我天天都在看  他啥时候发布 新版本  - -
