### ISSUE TITLE
在suimobile里使用tel:拨号会报错

### ISSUE THREAD

**Issue by hawk140** [sdc-alibaba/SUI-Mobile#291]
在suimobile里使用tel:拨号会报错，提示跨域了，但是如果不用tel，里面的一键拨号要怎么做呢
XMLHttpRequest cannot load tel:40****20. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by liunian** [comment]
链接 class 添加 `external` 值，参考 #75
