### ISSUE TITLE
scroll-fix.js中scrollTop = 1导致页面抖动

### ISSUE THREAD

**Issue by dqmmpb** [sdc-alibaba/SUI-Mobile#293]
scroll-fix.js中为什么当startTopScroll <= 0时要将scrollTop设置为1，而不是0？

设置为1好像导致鼠标点击时，页面向上抖动一下的问题，demo中列表中这个现象比较明显
http://m.sui.taobao.org/demos/infinite-scroll/bottom-infinite-scroll

如果设置设置为0，就不会出现抖动现象

**Comment by xiaran113** [comment]
这个抖动并不明显，这也是一种取舍，因为滚动区域顶部如果低于或者等于视窗位置，浏览器就会触发弹簧效果，底部同理，这段js就是为了去除浏览器的弹性效果，以避免弹性效果带来的滚动问题。精髓就在elem.scrollTop = 1;以及elem.scrollTop = elem.scrollHeight - elem.offsetHeight - 1;把这两个1改成0，则该段js失效
