### ISSUE TITLE
页面的过渡效果能不能在精致一些？

### ISSUE THREAD

**Issue by Eivs** [sdc-alibaba/SUI-Mobile#297]
首先，SUI很强大！感谢SDC团队的各位开发兄弟们

不知道您们是从安卓兼容性方面考虑，发现SUI的视图过渡效果没有Framework7那么华丽

主要表现在标题栏的那部分动画效果

也可以参考
http://code.kik.com/app/3/demo/?_app_platform=ios

还有个小问题，就是图片浏览器中双击放大图片，放大的中心不是刚才点击的那个地方，而是直接将整个图片居中缩放

可以参考(需要FQ，不然搜索不到结果)
http://image-search.kik.com/

可以试试这个图片浏览中点击图片的不同位置会根据点击的位置进行居中定位

**Comment by Mickey-** [comment]
感谢建议，后面有时间后会开始优化这部分动效。现在如果你有好得想法可以提交PR协助共建
