### ISSUE TITLE
【需求】能否在 [标签页] 新增滑动切换标签页？

### ISSUE THREAD

**Issue by Ahoo-Wang** [sdc-alibaba/SUI-Mobile#298]
【需求】能否在 [标签页] 新增滑动切换标签页？

**Comment by xyqfer** [comment]
[framework7](http://www.idangero.us/framework7/kitchen-sink-ios/) 有提供这个功能，点 Tabs -> Swipeable Tabs，如果急用的话可以先参考它的实现：[https://github.com/nolimits4web/Framework7/blob/master/src/js/tabs.js](https://github.com/nolimits4web/Framework7/blob/master/src/js/tabs.js)

**Comment by Mickey-** [comment]
感谢答复。另外不好意思，精力原因，这个动效类型暂时不会主动添加

如果性能体积成本不大的话，欢迎提交PR贡献，我们会review后merge
