### ISSUE TITLE
pageInit的时候，怎么获取url参数了？

### ISSUE THREAD

**Issue by boboxiao** [sdc-alibaba/SUI-Mobile#3]
pageInit的时候，怎么获取url参数了？

**Comment by lihongxun945** [comment]
pageInit事件触发的时候，页面的url已经被改变了，可以直接通过 location.href 来取

**Comment by boboxiao** [comment]
框架没有像F7一样，自带一个获取参数的属性么？

**Comment by boboxiao** [comment]
感觉不错，昨天改造成require加载了，兼容性还不错！就是有一点，没搞明白：在tab切换的时候，为什么会出现一个loading的东西了？

**Comment by Mickey-** [comment]
涉及加载等待的情况，会自动出现改善体验

**Comment by QzhouZ** [comment]
@lingtalCom 请问你现在用什么方法来获取地址栏的参数？
