### ISSUE TITLE
city-picker 默认值为两个值时，如"北京 海淀区"，初始化后存在问题，"广东 珠海 斗门区"就不存在问题

### ISSUE THREAD

**Issue by wormcc** [sdc-alibaba/SUI-Mobile#300]
![snip20160114_3](https://cloud.githubusercontent.com/assets/9067547/12325510/b00542ec-bb05-11e5-8f7f-24800f003b3e.png)
![snip20160114_2](https://cloud.githubusercontent.com/assets/9067547/12325514/b1448596-bb05-11e5-895b-6f6656da1670.png)

**Comment by Mickey-** [comment]
感谢！
