### ISSUE TITLE
popup组件调用后弹出层被灰色遮罩层罩住，无法进行任何操作。

### ISSUE THREAD

**Issue by yyba** [sdc-alibaba/SUI-Mobile#303]
需要移除popup-overlay或modal-overlay-visible这个类才能操作popup界面。请问如何设置默认popup不会被遮罩？能解释下overlay在这里的作用吗？谢谢了。

**Comment by leonlau81** [comment]
我也发现了这个问题，文档里也没有提到怎么解决，为啥没人回应这个问题呢？0.6.2

**Comment by Mickey-** [comment]
先popup，再调modal的问题是吗

**Comment by JackPu** [comment]
可以尝试先修改sm.js 不开启遮罩，这个样式需要调整吧

**Comment by Answerme** [comment]
这应该是因为你的popup放在了.page容器里面，而官方的demo中，popup是放在.page容器外面，如果要放在.page容器里面，注意Reset一下popup-overlay类的z-index属性就行了。
