### ISSUE TITLE
带有日历控件的页面进入内联页面在返回，再点击日历会多次触发

### ISSUE THREAD

**Issue by Eivs** [sdc-alibaba/SUI-Mobile#308]
具体测试是这样的
http://m.sui.taobao.org/demos/calendar/

在控制台执行
$.router.load("#page-bar");
$.router.back();

在点击日历控件，然后选择一个日期

**Comment by JSoon** [comment]
确实存在这个问题。
每返回一次，再进入内联页，日历控件生成数量就会+1。

**Comment by JSoon** [comment]
已修复，晚些时候提交一个PR。

**Comment by zeybar** [comment]
现在是已经好了吗，我还是碰到这个问问题
