### ISSUE TITLE
请问无限滚动和ajax结合起来使用该怎么写呢？

### ISSUE THREAD

**Issue by mengtingluo** [sdc-alibaba/SUI-Mobile#312]
有点搞不明白，麻烦帮我一下，谢谢

**Comment by dqmmpb** [comment]
demo中的
http://m.sui.taobao.org/demos/infinite-scroll/bottom-infinite-scroll
还是比较清晰的
只需要把demo.js中setTimeout换成ajax的请求应该就可以了

**Comment by Mickey-** [comment]
thx答复~
