### ISSUE TITLE
能不能整一套完整本地的纯html的框架，演示上还可以，复制点代码下来各种不行

### ISSUE THREAD

**Issue by meaningnet** [sdc-alibaba/SUI-Mobile#317]
例子里又是ruby，include什么什么的，框架跟服务器环境没关系吧，关注好久了，老是这不行，那不行的。哎

**Comment by dqmmpb** [comment]
最近在项目中用了下，可以看下我git上的xmdd-web，也没有按照套路规范什么的，楼主可以参考下吧，毕竟自己水平有限。用的yeoman的webapp框架，仅供参考吧

**Comment by Mickey-** [comment]
感谢 楼上的案例~

另外可以参考 http://m.sui.taobao.org/faq/#offline
