### ISSUE TITLE
菜鸟求助

### ISSUE THREAD

**Issue by yeshuangdong** [sdc-alibaba/SUI-Mobile#32]
使用sui的时候，点击一个链接进入下个页面的时候，在第一个页面上载入了自己的css文件，下个页面消失

**Comment by Mickey-** [comment]
SUI-Mobile 的自动链接劫持路由模式，旨在于帮助我们快速的搭建贴近原生应用体验的SPA应用。

各个页面的css你可以
- 根据pageid的命名空间在入口页的css里import进去。
- 或者在各个其他页面的`.page`元素里引用静态资源

或者考虑[CSS Module](http://glenmaddern.com/articles/css-modules)等方案
