### ISSUE TITLE
关于0.6.1路由问题

### ISSUE THREAD

**Issue by alex1987214** [sdc-alibaba/SUI-Mobile#320]
页面切换后移除前一个页面的 dom 而不是像之前那样保留（内联页面切换不会做移除操作）

如果我从 文章列表页 （已经ajax加载到了 第二页以后），进入 明细页 （之前是 路由外链）。。

0.6.1 没更新前，dom不移除的话，我从明细页回到 列表页，，状态还在

现在dom直接移除。。。等于又重新刷新了列表页 （其实不是  “刷新页面”，而是 滚动条位置 直接回到了顶端，而不是  进入明细页 时的位置）。。。这 逼得只能用回0.5.9了啊。。

否则这种业务情景 改用 内联的话。。那改动太大太大了

**Comment by 52cik** [comment]
嗯，今天升级被坑，，希望早日修复。

**Comment by guyong1018** [comment]
可以使用内联页面吧
