### ISSUE TITLE
Picker不够通用

### ISSUE THREAD

**Issue by whforit** [sdc-alibaba/SUI-Mobile#321]
我看到了之前作者的回复：<blockquote>这是特性如此。
picker展示时用displayValues，选择完后将value值置入input，而input组件的值和展示是相同的，所以有这种情况。
你的需求可能需要在业务里封装一下，将input隐藏，弄个div覆盖上去，在onchange的时候更新input值后，改变div上的内容</blockquote>，
但实际上，应用的数据库里很少会直接存储picker显示的value，就像省市区级联的例子，我不信淘宝数据库存储城市是直接存储城市名字，而不是符合规范的编码Id。所以设计picker的时候就应该像select一样，option value为picker value，option 的innerText为displayValue吧。

我还没有尝试 作者回复的做法，想了下貌似还是会有问题。比如<code>values:[7,8,9]</code>,<code>displayValues:[iphone4,iphone5,iphone6]</code>，我选择了<code>iphone5</code>，hidden input的value为<code>8</code>，我通过onchange获取了<code>8</code>，但是无法通过<code>8</code> 直接获取<code>iphone5</code>去更新那个覆盖在上面的div。
因为values和displayValues并没有直接的一对一关系。所以，设计picker组件的时候应该就需要两个input，value也应该用对象数组的形式，而不是纯字符串数组。

**Comment by whforit** [comment]
还有那个官网demo，我在微信浏览器里访问表单页面，性别和生日是相邻的两行，我点击性别，先弹出原生的select，紧接着又弹出日历组件。是因为点透的原因？

**Comment by wormcc** [comment]
可以在picker初始化的时候自定义一个formatValue参数，这个文档里面没有体现出来，例如：

```
$("#picker-name").picker({
  toolbarTemplate: '<header class="bar bar-nav">\
  <button class="button button-link pull-right close-picker">确定</button>\
  <h1 class="title">请选择称呼</h1>\
  </header>',
  cols: [
    {
      textAlign: 'center',
      values: ['赵', '钱', '孙', '李', '周', '吴', '郑', '王']
      //如果你希望显示文案和实际值不同，可以在这里加一个displayValues: [.....]
    },
    {
      textAlign: 'center',
      values: ['杰伦', '磊', '明', '小鹏', '燕姿', '菲菲', 'Baby']
    },
    {
      textAlign: 'center',
      values: ['先生', '小姐']
    }
  ],
  formatValue: function (picker, value, displayValue){
      //value 和 displayValue都是数组，长度为你的cols的长度，值为当前选中值
  }
});
```

不知道是不是你想要的 @whforit

**Comment by whforit** [comment]
@wormcc 用你提示的方法可以实现，需要自己加个hidden input，在formatValue中：更改hidden input 的值为value，最后return displayValue，更新displayed input 的值。

**Comment by xshiny** [comment]
看不明白，formatValue: function (picker, value, displayValue){
      //value 和 displayValue都是数组，长度为你的cols的长度，值为当前选中值
  }有几天的实例吗？

**Comment by edwinwow** [comment]
同问，有实例？

**Comment by whforit** [comment]
@xshiny @edwinwow value就是option的value，displayValue就是option 的text值。比如，你期望的下拉框key-value对：1-男，2-女。那么value就是[1,2]，displayValue就是['男','女']。

**Comment by franktam** [comment]
@whforit

> 需要自己加个hidden input，在formatValue中：更改hidden input 的值为value，最后return displayValue，更新displayed input 的值。

请问这个有实例参考么
谢谢

<input type="text"  id='picker' />
<input type="hidden"  id='picker1' />

怎么把value写到 picker1里面去，displayValue写到picker呢
