### ISSUE TITLE
picker的功能建议

### ISSUE THREAD

**Issue by wormcc** [sdc-alibaba/SUI-Mobile#323]
picker目前是直接将选择的值赋给了input的value显示出来，是否可以创建另外一个包裹显示层，用显示层来展示displayValue，这样是不是能更灵活些，现在为了分开value和displayValue还得创建一个隐藏域。

**Comment by whforit** [comment]
就像你说的一样，创建隐藏域，然后用formatValue，这样更灵活啊！建议文档里面要补充这个！

**Comment by wormcc** [comment]
@whforit 文档已经提交了pull request

**Comment by wormcc** [comment]
@whforit  嗯，忘记考虑分开获取cols各项值的需求了，还是使用formatValue设置隐藏域吧
