### ISSUE TITLE
Popup 的显示bug

### ISSUE THREAD

**Issue by hisune** [sdc-alibaba/SUI-Mobile#328]
现象：打开popup，往下拉，会出现下面2个图中的灰色背景区域，PC的最新chrome是没问题的

UA: Mozilla/5.0 (Linux; Android 4.4.2;  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

Android: 4.4.2

chrome内核版本号：30.0.0.0

![image](https://cloud.githubusercontent.com/assets/7941669/12388481/1a8cc288-be0e-11e5-81fe-af028c9e29fe.png)

![image](https://cloud.githubusercontent.com/assets/7941669/12388492/2987ad2a-be0e-11e5-814f-0a8ee6263561.png)

**Comment by carr123** [comment]
我也出现这个情况， 就是popup 页面滚动条往下滚动时，有一块多余的空白区域， 我的是IOS9.2 微信里面。
请问这个问题解决了么？

**Comment by hisune** [comment]
![image](https://cloud.githubusercontent.com/assets/7941669/12442692/0f74d6bc-bf8d-11e5-85a1-9e4b29feddf5.png)
给popup的上一层div增加属性：

``` css
overflow: hidden;
```

**Comment by hisune** [comment]
@carr123

**Comment by Mickey-** [comment]
手机端是只有 安卓有这个问题吗，？

问题明确、解决方案明确的话，可否提交一个PR贡献？ @hisune

**Comment by angusjiang** [comment]
我遇到一种情况就是将popup关闭后，整个页面往上拉，会将关闭的pupup拉出来，咋回事啊
