### ISSUE TITLE
picker 的values和displayValues的问题

### ISSUE THREAD

**Issue by roczyl** [sdc-alibaba/SUI-Mobile#329]
比如 字段 id:1;name:DELL,id:2;name:Lenovo，
如果能显示都是用name，id隐藏起来就好了。
现在，如果用 values和displayValues设置的话，下面弹出的是 name ，但是上面文本框里却还是id，用户能够看到1,2这样的数字，会感到很奇怪。

**Comment by wormcc** [comment]
@roczyl 参考#321

**Comment by Mickey-** [comment]
thx
