### ISSUE TITLE
data-no-cache的问题

### ISSUE THREAD

**Issue by alex1987214** [sdc-alibaba/SUI-Mobile#330]
官方demo data-no-cache 没问题
但是引用发布本的 0.6.1   无效
//g.alicdn.com/msui/sm/0.6.1/js/sm.min.js

里面搜索 连 data-no-cache 的关键字都没有啊！！！！
里面少了
   var ignoreCache = $target.attr('data-no-cache') === 'true';
判定啊

0.6.1 问题太多了

**Comment by roczyl** [comment]
怪不得，我也正奇怪怎么官方可以，我不可以呢。谢谢啦！

**Comment by Mickey-** [comment]
github上dev分支是最新代码， data-no-cache 的措施也已经处理了，目前尚未发布，发布后cdn上会更新一个版本号资源。
