### ISSUE TITLE
关于route加载新页面时，新页面中的js没有加载的问题

### ISSUE THREAD

**Issue by joneqian** [sdc-alibaba/SUI-Mobile#331]
我有A，B两个页面，A页面中加载了js-1和js-2，B页面中加载了js-1、js-2、js-3，当我从A页面路由到B页面时，B页面只加载了js-1和js-2，js-3没有加载，也没有去服务器get js-3文件，我重新刷新一下页面后就又正常了！！

我用的web框架是express，当我用external禁用了sui自带的路由后，一切又都正常了！

请问这是怎么回事？难道sui mobile的路由会和express的路由冲突吗？

**Comment by alex1987214** [comment]
切换到的新页面中的 js 不执行
由于浏览器安全性考虑的限制以及可能的 js 重复执行或覆盖的问题，目前是不支持运行 ajax 载入的页面里面的 js 的，参考 #120。

解决方法：所有页面都引用相同的 js，而这个 js 里面包含了所有的逻辑，事件部分使用委托来绑定。

http://m.sui.taobao.org/faq/

**Comment by joneqian** [comment]
谢谢，明白了！！！

**Comment by ijry** [comment]
可以这样执行B页面的JS
这是我在framework7下使用的办法，SUI应该差不多吧。

此方法可以执行ajax页面的js
步骤一：添加事件
app.onPageAfterAnimation('', function (page) {
executeScript(page.view.activePage.view.xhr.response);
});
步骤一：添加executeScript函数
function executeScript(html) {
var reg = /<div class=“block_sccipt”>\n.\n.<script[^>]>([^\x00]+)$/i;
//对整段HTML片段按<\/script>拆分
var htmlBlock = html.split(“<\/script>”);
for ( var i in htmlBlock) {
var blocks;//匹配正则表达式的内容数组，blocks[1]就是真正的一段脚本内容，因为前面reg定义我们用了括号进行了捕获分组
if (blocks = htmlBlock[i].match(reg)) {
//清除可能存在的注释标记，对于注释结尾—>可以忽略处理，eval一样能正常工作
var code = blocks[1].replace(/<!—/, '');
var code = code.replace(/<div class=“blocksccipt”>/, '');
console.log(code);
try {
//evalr(code) //执行脚本
if (!!(window.attachEvent && !window.opera)) {
//ie
execScript(code);
} else {
//not ie
window.eval(code);
}
} catch (e) {}
}
}
}
