### ISSUE TITLE
单页控制多侧栏的问题

### ISSUE THREAD

**Issue by bihongbin3027** [sdc-alibaba/SUI-Mobile#34]
在任何元素上增加 .open-panel 类都可以使它能点击打开侧栏。如果有多个侧栏，你可以通过 data-panel='{panel的选择}'来指定具体打开哪一个侧栏。我写了两个侧栏，两个分别用不同的data-panel='{panel的选择}来控制，但是不起作用，加了这个和不加的一样，一直都是显示同一个侧栏。

**Comment by Mickey-** [comment]
@lihongxun945

**Comment by bihongbin3027** [comment]
还有我页面的js，我写在script里面的js，页面切换以后，在切换回来，js就不见了

**Comment by bihongbin3027** [comment]
页面跳转一次，就会在dom里面多生成一个.page容器，是不是我写的哪里不对呢？

**Comment by bihongbin3027** [comment]
js不见的问题解决了，是要把js包到.page容器里面，就可以了。

**Comment by Mickey-** [comment]
涨姿势了

**Comment by bihongbin3027** [comment]
嘿嘿，现在主要这个会跳转一次链接就会生成一个.page，这让人很难受啊，页面都有问题了。还有这个侧栏的问题... @lihongxun945 应该帮我看看啊~

**Comment by Mickey-** [comment]
第一次进入新页面时，router会插入一个.page，不过按规范写不同页面时，每个页面主体部分都应该包含在`.page`里，我到时觉得没什么问题。

关于JS脚本执行的事儿

如果期望每次进入对应视图都执行，就在

``` javascript
$(document).on('pageInit',  fn)
```

如果`fn`里的逻辑是后面页面里才需要执行的，[加上对应page的pageid](http://m.sui.taobao.org/components/#router)即可：

``` javascript
$(document).on('pageInit',  '#pageid', fn)
```

对那些只执行一次的逻辑，不写在`pageInit`事件里就好了

**Comment by smanor** [comment]
我也遇到这个问题，自己改了下sm.js
leftPage.animationEnd(function() {
        leftPage.removeClass(removeClasses);
        leftPage.remove();
});
但返回出了问题
