### ISSUE TITLE
网页 省市区选择器 给的链接错误

### ISSUE THREAD

**Issue by whyliam** [sdc-alibaba/SUI-Mobile#35]
在 http://m.sui.taobao.org/extends/#city-picker 中，

> 使用省市区选择器，你需要在 sm.js 和 sm.css 之后额外引入如下JS文件:
> `<link rel="stylesheet" href="//g.alicdn.com/sui-mobile/sm/0.5.0/css/sm-city-picker.min.css">`

js文件应该为
`<script type="text/javascript" src="//g.alicdn.com/sui-mobile/sm/0.5.0/js/sm-city-picker.min.js" charset="utf-8"></script>`

**Comment by Mickey-** [comment]
感谢指正！
