### ISSUE TITLE
微信 报错：Uncaught TypeError: Cannot read property 'style' of null 

### ISSUE THREAD

**Issue by JackFish** [sdc-alibaba/SUI-Mobile#351]
![image](https://cloud.githubusercontent.com/assets/1689611/12473014/2684e326-c049-11e5-8182-10131bbe696e.png)
用微信打开后310行报错：Uncaught TypeError: Cannot read property 'style' of null

**Comment by JackFish** [comment]
需要将script放到最后。。。，坑啊
已经解决

**Comment by Mickey-** [comment]
Uncaught TypeError: Cannot read property 'style' of null

这个关键词信息可以在issue里搜索，之前已经有人提出并答复了。这个信息我们也会加入到官网FAQ里
