### ISSUE TITLE
pager的display为什么默认设置display: none

### ISSUE THREAD

**Issue by hxchen** [sdc-alibaba/SUI-Mobile#354]
打开http://g.alicdn.com/msui/sm/0.6.1/css/sm.css
搜索.page-group。发现.page,
.page-group和设置了display为none，显示出来不是更好吗？否则使用pager的时候，都不显示了啊。
还有怎么没有table组件，展示多列的。是在移动端table不适合展示么

**Comment by roczyl** [comment]
1. 当然要这样啦。所有.page一同隐藏，然后需要显示的再用js显示出来，整个系统就是这么设计的呀。
2. 同问一下，有table组件吗？

**Comment by Mickey-** [comment]
同意楼上

.page 都是 display none的
.page-current 才是 显示的

你注意看官网Demo，切换页面时都是.page-current 这个类名在不同的page间切换，.page-current 是唯一的，保证只有一个page是活动状态

PS,没有提供table组件，这个在移动端不常用，需要的话业务里封装吧

**Comment by ahfychangbb** [comment]
怎么样从B页面跳转到A页面的page2 啊
