### ISSUE TITLE
popup里的无限滚动无法触发infinite事件

### ISSUE THREAD

**Issue by TomGraph** [sdc-alibaba/SUI-Mobile#356]
.popup>.bar+.content.inifite-scroll>.infinite-scroll-preloader

**Comment by cipchk** [comment]
我这里的一种做法：
1. popup打开时，初始化 `$.initInfiniteScroll('.popup');`；因为默认调用该方法的参数是当前 page。
2. 监听Popup下content区域的`infinite` 事件，例： `$('.popup .content').on('infinite', function(){});` 事件。

**Comment by TomGraph** [comment]
@cipchk  成功解决谢谢,但是有个小bug,下拉时会有个卡顿,不知道是不是我这里单方面的问题
