### ISSUE TITLE
cdn上的v0.5.0在手机Safari浏览器中空白页面

### ISSUE THREAD

**Issue by chenjingchun** [sdc-alibaba/SUI-Mobile#36]
cdn上的v0.5.0在手机Safari浏览器中空白页面，0.4及以下版本是正常的
http://183.56.152.213:45/index04.html //v0.4正常
http://183.56.152.213:45/index05.html //v0.5手机Safari浏览器异常

**Comment by Mickey-** [comment]
具体是哪个页面是空白页面，链接贴一下吧？

**Comment by chenjingchun** [comment]
@Mickey- 
http://183.56.152.213:45/index04.html //v0.4正常
http://183.56.152.213:45/index05.html //v0.5手机Safari浏览器异常

**Comment by Mickey-** [comment]
0.5.1发布，有时间更新一下吧，空白页面一般是因为没有按照HTML布局规范写，http://m.sui.taobao.org/components/#layout
