### ISSUE TITLE
一个链接走浏览器原生跳转而不使用router，使用$.router.load跳转怎么拦截

### ISSUE THREAD

**Issue by f2443454001** [sdc-alibaba/SUI-Mobile#363]
如果使用Click事件 触发  $.router.load 跳转 ，
$.config = {
        // 路由功能开关过滤器，返回 false 表示当前点击链接不使用路由
        routerFilter: function($link) {
            // 某个区域的 a 链接不想使用路由功能
            if ($link.is('.disable-router a')) {
                return false;
            }

```
        return true;
    }
};
```

该怎么使用。。。

**Comment by Mickey-** [comment]
都已经是 `$.router.load`的，那么一定会用路由体系。

你可以在调用他之前判断，希望用浏览器原生跳转的，用location.href，否则再load
