### ISSUE TITLE
使用$.router.load加载页面时，是否能指定页面加载方向？

### ISSUE THREAD

**Issue by rennai** [sdc-alibaba/SUI-Mobile#365]
目前加载页面都是从右往左，但是有时候会是两个页面来回切换，这样体验不太好。

**Comment by qinbingfeng** [comment]
顶这个,

**Comment by Mickey-** [comment]
目前不支持自定义方向，但是左右或右左模式都是可以的。

如果是两个页面来回切换，切回去时请用 **返回** 的功能形式。

如果是因为前一个页面需要数据更新，我们有参数配置可以不使用缓存，保证数据重新更新

![image](https://cloud.githubusercontent.com/assets/2062355/12570906/d19beb3a-c416-11e5-8089-daabe1ce6931.png)

**Comment by rennai** [comment]
好的，明白了！但是还是有个能指定方向的设置比较方便。
