### ISSUE TITLE
0.6.1后退无效

### ISSUE THREAD

**Issue by cipchk** [sdc-alibaba/SUI-Mobile#366]
手机：魅族
浏览器：chrome 47.0.2526.83
操作系统：android 4.4.4
SUI-Mobile：0.6.1

用Chrome直接打开 http://m.sui.taobao.org/demos/datetime-picker 点后退，直接跳到上一个页面，而非： http://m.sui.taobao.org/demos

**Comment by Mickey-** [comment]
当然是跳到之前的页面了。。。“返回”返回的是历史栈里之前访问的页面。

举个例子，你访问 https://www.tmall.com
然后在浏览器里直接访问 [https://err.taobao.com/error1.html](https://err.taobao.com/error1.html)

这个时候点返回，当然是返回到 https://www.tmall.com ，而不是https://err.taobao.com/ 了
