### ISSUE TITLE
滚动条里的checkbox不能点击啊

### ISSUE THREAD

**Issue by senro** [sdc-alibaba/SUI-Mobile#37]

**Comment by Mickey-** [comment]
```
滚动条里的checkbox
```

什么意思？可以截图上传看下吗

**Comment by senro** [comment]
找到原因了，是因为sm.js引用的fastclick对ios6-7做了检测，需要单独处理。但是又发现新问题了，好像sui做出来的页面在ios8的safari里有问题啊，和chrome里的表现不一样啊，路由不起作用了！

**Comment by senro** [comment]
进入页面乱了，返回按钮也不起作用了，我是iphone4s升级的ios8，求解答，demo地址：http://zx.yearn.cc/kaola-app-delivery/index.html

**Comment by Mickey-** [comment]
你的这个Demo有用sm吗？我看代码咋没找到 @senro

**Comment by Mickey-** [comment]
#38
