### ISSUE TITLE
大家开发SUI都使用什么工具？

### ISSUE THREAD

**Issue by NanjingCHoujianli** [sdc-alibaba/SUI-Mobile#371]
我是小菜鸟，请教大家，开发SUI用什么工具？deamwerver可以吗？我写好，代码直接用浏览器浏览怎么没反应啊？是不是还有配置其他服务啥的？初学者，请给予指点，谢谢，谢谢

**Comment by Mickey-** [comment]
不要用deamwerver，建议用sublime最新版本或Atom、webstorm之类的。

真实Demo可以参考 http://m.sui.taobao.org/demos/  仔细阅读文档前几节，注意$.init()
