### ISSUE TITLE
页面切换问题

### ISSUE THREAD

**Issue by jsjoyy** [sdc-alibaba/SUI-Mobile#372]
我有一个搜索框要在A\B\C三个不同的页面使用。应该如何绑定这个JS事件。
$(document).on("pageInit", "#A,#B,#C", function(e, id, page){});这样写返回的时候有问题。
有没有什么好的方式？谢谢

**Comment by jsjoyy** [comment]
我在搜索列表页再搜索的时候如何切换当前页

**Comment by Mickey-** [comment]
建议不要同时委托多个页面id，分成3段写，同时每段里可以写不用页面的其他逻辑，也方便未来维护
