### ISSUE TITLE
路由缓存问题（ignoreCache 设为 true，仍然使用了缓存）

### ISSUE THREAD

**Issue by leonlau81** [sdc-alibaba/SUI-Mobile#373]
桌面和移动端均重现该问题。桌面端：win10，chrome 48.0.2564.82（64bit）；移动端：华为，安卓6.0，原生浏览器，uc浏览器，微信内置浏览器。使用router.load("orderDetail.do?orderId=XXX"),true)，实现ajax页面载入（后台会根据订单id查询订单信息），在第二次点击该订单后，直接加载了页面，服务端没有执行查询方法，很明显是使用了缓存，而没有强制重新请求。

**Comment by Mickey-** [comment]
使用的是0.6.2版本吗

可以在这个页面测试：http://m.sui.taobao.org/demos/routers/cache/  打开开发者工具的网络面板观察请求

**Comment by leonlau81** [comment]
嗯，试了下0.6.2版本（之前是0.6.1），这个bug已经修复了，thx。
