### ISSUE TITLE
请问你们的ajax路由是不是要环境支持的

### ISSUE THREAD

**Issue by ghost** [sdc-alibaba/SUI-Mobile#374]
我用浏览器点内联的可以跳转 但点ajax就出错 出现找不到页面错误

**Comment by Mickey-** [comment]
不需要，官网Demo就是非内联的页面，可以参考 http://m.sui.taobao.org/demos/

**Comment by ghost** [comment]
<li><a href="/html/page-picker">ajax加载新页面</a></li>
我目录下有html文件夹 里头有page-picker.html文件 但它访问不了 我操作哪里出问题了？

**Comment by Mickey-** [comment]
你这是什么链接，怎么是跳到404的

**Comment by ghost** [comment]
git 自动解析了... href="/html/page-picker" 我是这样写的

**Comment by Mickey-** [comment]
那需要你对照官网Demo 分析自己的代码了，官网Demo的href也是这种相对根路径地址，然而是正常的

**Comment by ghost** [comment]
刚试了下在连接下加.html 它就成功跳转了
