### ISSUE TITLE
请问FastClick需要吗？

### ISSUE THREAD

**Issue by zhang943366739** [sdc-alibaba/SUI-Mobile#376]
UI有集成类似Fastclick的插件功能吗？感觉点击有些延迟，不知道是不是心里作用。

**Comment by Mickey-** [comment]
心里作用。。

有集成，并且fastclick已经有很久没更新了，有些bug修复一直没被合入主干，我们已经解决了这些bug。

所以不要用官方的fastclick，sui-mobile集成的更完善

**Comment by zhang943366739** [comment]
@Mickey- 好的，非常感谢！
