### ISSUE TITLE
官方demo，内联路由在iphone4s的ios8 safari浏览器里不起作用啊！

### ISSUE THREAD

**Issue by senro** [sdc-alibaba/SUI-Mobile#38]
这个官方路由demo在iphone4s的ios8 safari浏览器里不起作用啊！
地址：
http://m.sui.taobao.org/docs-demos/router/
求测试解答啊！

**Comment by Mickey-** [comment]
我这边在非iphone4s的ios8的safari是没问题的，回头试下4s，暂时手头没机器

**Comment by Mickey-** [comment]
尝试过4S里（但不是ios8）的safari，也没有问题。

现在4s已经是作为老爷机了，4S还敢升级IOS8基本很难跑的顺畅吧，建议不要考虑这种少数情况了。
