### ISSUE TITLE
popup弹出窗口默认模态？

### ISSUE THREAD

**Issue by leonlau81** [sdc-alibaba/SUI-Mobile#383]
跟了一下代码，sm.js(0.6.2版本)第1587行，`if (!isLoginScreen && !isPickerModal && !isToast) overlay.addClass('modal-overlay-visible');`；这个逻辑是说popup的class里必须有'login-screen'、'toast'、'picker-modal'这三个样式中的一个，弹出窗口才不是模态的。非常不理解这个逻辑。因为一般的popup都是这么写的`<div class="popup popup-XXX">`，那么这个popup一定是模态的。

**Comment by Mickey-** [comment]
popup因为占满屏幕，所以都是模态的
