### ISSUE TITLE
sui Mobile有左滑删除功能么？

### ISSUE THREAD

**Issue by openks** [sdc-alibaba/SUI-Mobile#39]
sui Mobile有左滑删除功能么？

**Comment by Mickey-** [comment]
SM里删去了这个功能，该功能在我们的姊妹版，F7-plus里有：http://framework7.taobao.org/docs/swipeout.html

后续可能会考虑合并，目前业务中需要的话可以从 https://github.com/sdc-fe/Framework7-Plus/blob/dev/src/js/swipeout.js 借鉴代码复用

**Comment by openks** [comment]
@Mickey-  谢谢哈

**Comment by Mickey-** [comment]
https://github.com/sdc-alibaba/SUI-Mobile/issues/242

**Comment by capqueen** [comment]
求推荐滑动删除插件，自己集成不了额

**Comment by ArcRain** [comment]
可以参考Light7的集成：http://light7.cn/extends/#swipeout

**Comment by capqueen** [comment]
集成参考：
1. 直接copy light7中的swipout.js,需要修改的地方是23行：
  改成：
 `swipeoutOpenedEl[0] == target[0] ||
target.parents('.swipeout')[0] == swipeoutOpenedEl[0] ||`
原因是 zepto不支持对象的is()方法比较，light7使用的是jquery。
其他地方没有发现要修改的。
2.swiper 添加禁用局部class的参数：
`noSwiping:true,`
 `noSwipingClass: 'swiper-no-swiping'`
 目的是防止swipout和swiper冲突， swiper-no-swiping加到swipeout的父dom上
