### ISSUE TITLE
标签页和工具栏

### ISSUE THREAD

**Issue by ironbob** [sdc-alibaba/SUI-Mobile#396]
1.放在底部的标签页，但是样式要和工具栏一样，请问怎么实现。
2.概念有些混淆，看了demo,但是工具栏的按钮都是点不动的，能不能给个demo是可以链接到其它页的

**Comment by guoshanche** [comment]
工具栏本身只是UI，并没有脚本逻辑。另外我们在工具栏 设计的初衷是：不同工具栏的icon链接通常代表形态完全不同的业务模块、范畴， 不要做成一个SPA应用 。
就是说，假如你工具栏有3个入口，那么这3个工具icon对应的链接最好是.external的。也就是刷新页面进入新url的形式，而不是以路由单页的形式滑页进入。可以说这3个icon对应了3个SPA链路的入口。

https://github.com/sdc-alibaba/SUI-Mobile/issues/130#issuecomment-163520628

**Comment by Mickey-** [comment]
作为a标签，就是普通的链接，加个href属性就可以跳转了
