### ISSUE TITLE
加入搜索框后页面不正常显示附解决方法

### ISSUE THREAD

**Issue by openks** [sdc-alibaba/SUI-Mobile#40]
在searchbar类上加overflow:hidden即可
![Uploading 2015-10-14_17-26-27.png…]()

**Comment by Mickey-** [comment]
图片格式错了。。请附图描述下具体页面不正常情况吧

![image](https://cloud.githubusercontent.com/assets/2062355/10502322/68db8b54-731d-11e5-8e96-b276d66e6579.png)

**Comment by openks** [comment]
http://ww4.sinaimg.cn/bmiddle/92d188bbjw1ex1q23prxoj20cr0grmyn.jpg 
图片上传不上去 用新浪图床弄了下

**Comment by openks** [comment]
http://demo.zhuyangxing.cn/demo/login.html 可以去这个demo里用移动设备访问下就能看到效果了

**Comment by Mickey-** [comment]
尝试了chrome模拟器里是有问题的，在ios真机里正常，但Android 4.4开始的真机浏览器里都有这个问题。

“取消”的布局溢出，非常感谢指正！

也请你 **发一个Pull Request关联这个Issue** 吧，我们review后会merge，也记录你的贡献~ @openks

**Comment by openks** [comment]
@Mickey-  第一次Pull Request代码，不知道弄得对不对，如有不对还望见谅

**Comment by Mickey-** [comment]
nice，thx~
