### ISSUE TITLE
列表头尾两块灰色区域不好看

### ISSUE THREAD

**Issue by liniu** [sdc-alibaba/SUI-Mobile#404]
列表头尾留有两块灰色区域，个人觉得不是很好看。

**Comment by xyqfer** [comment]
![qq20160215-0](https://cloud.githubusercontent.com/assets/5186792/13042850/bd26733a-d3fe-11e5-9f1b-40442987a4ae.png)

![qq20160215-1](https://cloud.githubusercontent.com/assets/5186792/13042851/bd2a74da-d3fe-11e5-94a6-b96e2635f825.png)
- 呃你说的是上图箭头所指的部分吗？列表头尾都有 `margin` ，这个可以直接在业务层面的样式里重写掉的~

**Comment by liniu** [comment]
@xyqfer  是的，我觉得默认margin设置小一点，需要边距大点的再重写比较合理。

**Comment by liniu** [comment]
同时表单的样式也可以再美化一下，特别是边界线（如中间分隔线）不是很明显，可以看frozenui或weui 样式不管是背景还是分隔线就相对比较清晰。

**Comment by xyqfer** [comment]
@liniu 你可以比较下面两张图（设备iPhone 6S），我自己的理解 SUI 这边默认列表的 `margin` 值是跟 iOS一致的，框架设计的时候估计是按照这个来的
![img_0668](https://cloud.githubusercontent.com/assets/5186792/13103571/4ada05b8-d592-11e5-838d-4ddd9721c2eb.PNG)
![img_0669](https://cloud.githubusercontent.com/assets/5186792/13103572/4ae3f168-d592-11e5-8311-f6f78f649b1c.PNG)

**Comment by liniu** [comment]
@xyqfer 好的,谢谢你热心的解释
