### ISSUE TITLE
infinite refresh 事件在 小米3 微信里面 监听不到

### ISSUE THREAD

**Issue by yjj5855** [sdc-alibaba/SUI-Mobile#407]
# 问题
1. infinite refresh 这2个事件 在小米3微信里监听不到
2. 无限滚动 和 下拉刷新 一起用会有BUG 滚下去之后，通过手势操作是滚不上来的
3. buttons-tab 标签页使用的flex布局 不兼容 安卓浏览器

SUI-Moblie 版本 0.6.2

**Comment by a-la-shen-ding** [comment]
关于2，LZ是怎么解决的啊，跪求

**Comment by a-la-shen-ding** [comment]
@yjj5855
