### ISSUE TITLE
window的scroll事件

### ISSUE THREAD

**Issue by wcccode** [sdc-alibaba/SUI-Mobile#409]
$(window).on("scroll", function(){})这个监听失败。请问是sui引起的吗？sui有禁用window的scroll事件吗？请帮忙看下，O(∩_∩)O谢谢

**Comment by xyqfer** [comment]
- 给个大概的思路，这是由于 SUI 本身布局所导致的
- 目前 SUI 的滚动是通过在 `.content` 里设置 `-webkit-overflow-scrolling: touch;` 实现的，即在外围包了个框，里边的内容可以滚动但是外框没超出页面的，也就是页面其实是没滚动的所以不会触发  `window` 下的 `scroll` 事件。。（说的有点啰嗦了别介意= =。。开浏览器看下布局就大概能明白的了~
- 然后解决办法的话可以试试下面的：

```
$(".content").on("scroll", function () {
       alert(1);
});
```
- 大概是这么写，不过注意要区分下是哪个 `page` 下的 `.content`

**Comment by wcccode** [comment]
thanks! 问题解决了

**Comment by 52fhy** [comment]
@xyqfer 谢谢！正为了sui改写了zepto的scroll事件头疼呢！用了图片懒加载插件https://github.com/jieyou/lazyload后，始终加载有问题，后来发现是scroll事件问题。现在改成这样：

```
$(function() {
              $(".lazy").lazyload({         
                    effect : "fadeIn",
                    data_attribute : 'src',
                    event: 'scroll',
                    container: $(".content")
                });
            });
```

```
<img class="lazy" data-src="img/example.jpg" width="765" height="574">
```

需要指定容器`.content`。
