### ISSUE TITLE
请问如何返回首页

### ISSUE THREAD

**Issue by QzhouZ** [sdc-alibaba/SUI-Mobile#41]
页面从A->B->C，请问在C页面怎么back到A页面，F7可以通过

```
homeView.router.back({
    url: 'index.html',
     force: true
});
```

返回

**Comment by Mickey-** [comment]
http://m.sui.taobao.org/components/#router

看下这里 
![image](https://cloud.githubusercontent.com/assets/2062355/10507473/3c601b72-7353-11e5-96ca-bb0a27b3f4b0.png)

**Comment by QzhouZ** [comment]
@Mickey- 
在C页面用
`$.router.back('/A');`只能返回B页面
用
`$.router.loadPage('/A');`是前进到A页面，相当于又重新加载了A页面，document就存在两个A页面结构了

**Comment by Mickey-** [comment]
明白你的意思了，目前我们在**设计上**不支持这种 **越级 back** ，如果有这种越级back的场景，那么我们会采用再 **前进** 一步的思路,也就是再pushState一个历史记录，也符合history的设计理念。

希望能给你一些参考哈

**Comment by QzhouZ** [comment]
@Mickey- 
有个常见的场景，就是点个人中心—》登陆－》注册－》注册成功直接返回个人中心，跳过登录页，
不知道这样的场景，基于sui有什么其他的设计方案吗？
