### ISSUE TITLE
当一个页面有多个datetime-picker时间输入框时只有第一个有效

### ISSUE THREAD

**Issue by liuwu0720** [sdc-alibaba/SUI-Mobile#416]
当一个页面有多个datetime-picker时间输入框时只有第一个有效（不同id），试个用class也没有用

$("#datetime-picker1").datetimePicker({
    value: ['1985', '12', '04', '9', '34']
  });

$("#datetime-picker2").datetimePicker({
    value: ['1985', '12', '04', '9', '34']
  });

如上示例，只有ID为datetime-picker1的输入框可以出现时间选择插件，第二个没有出现

**Comment by wormcc** [comment]
参考我的pr的中修改，临时性修复 #421 方案 @liuwu0720
