### ISSUE TITLE
求科普：github上怎么生成和cdn上一样的css和js

### ISSUE THREAD

**Issue by chenjingchun** [sdc-alibaba/SUI-Mobile#44]

**Comment by Mickey-** [comment]
你想自己编译生成一份最终文件吗，可以参考https://github.com/sdc-alibaba/SUI-Mobile/blob/dev/develop.md    

之后基本就是跑grunt任务编译生成最终的js、css https://github.com/sdc-alibaba/SUI-Mobile/blob/dev/Gruntfile.js
