### ISSUE TITLE
为什么内联页面，点击后退回，轮播停止？

### ISSUE THREAD

**Issue by silverWolf818** [sdc-alibaba/SUI-Mobile#443]

**Comment by mirrorpal** [comment]
<script type="text/javascript">
$(function() {
    var swiper = new Swiper('.swiper-container',{
        speed:2000,
        autoplay:true,
        loop : true,
        loopAdditionalSlides : 4,
        pagination : '.swiper-pagination',
        autoplayDisableOnInteraction : false
    });
    $.init();
});
</script>
我单独用的swiper，sui提供的轮播BUG太多用不了

**Comment by silverWolf818** [comment]
<script type="text/javascript">
$(function() {
    var swiper = new Swiper('.swiper-container',{
        speed:2000,
        autoplay:true,
        loop : true,
        loopAdditionalSlides : 4,
        pagination : '.swiper-pagination',
        autoplayDisableOnInteraction : false
    });
    $.init();
});
</script>

我单独用的swiper，sui提供的轮播BUG太多用不了
