### ISSUE TITLE
无限滚动报错，完全不知所以然

### ISSUE THREAD

**Issue by lk125454242** [sdc-alibaba/SUI-Mobile#448]
###### #######################错误

错误类型：
Uncaught TypeError: Cannot read property 'apply' of undefined
错误代码：
return c&&c.scroller?c.scrollTop(a,b):d.scrollTop.apply(this,arguments)}}})
###### #######################HTML

cotentDIVclass类：content infinite-scroll infinite-scroll-bottom native-scroll
 
            <div class="content infinite-scroll infinite-scroll-bottom native-scroll" data-distance="50">
                <div class="content-block">
                    <ul id="buttons-tab" class="navList mar-0">
                        
                    </ul>
                   <div class="list-block">
                        <ul id="listView" class="listView mar-0 list-container">
                        </ul>
                    </div>
                </div>
                <div class="infinite-scroll-preloader">
                    <div class="preloader"></div>
                </div>
            </div>
###### #########################JS

$('#page').on('pageInit',function(){
                $(document).on('infinite', '.infinite-scroll-bottom',function() {
                    console.log($('.infinite-scroll-bottom'));
                    if (that.loading) {return}// 如果正在加载，则退出
                    that.loading = true;
                    that.page++;
                    that.get_list(that.cid);//发送AJAX
                });
            });
            $.init();

**Comment by Rockergmail** [comment]
我看到有issue说是zepto版本问题，你换个试试看

**Comment by lk125454242** [comment]
恩恩，我把SUI mobile和zepto一起换成新版之后问题确实解决了。谢谢~ Rockergmail
