### ISSUE TITLE
请问下如果我只需要用picker.js，还依赖哪些文件

### ISSUE THREAD

**Issue by NotGeekAtAll** [sdc-alibaba/SUI-Mobile#449]
我导入了device.js 和 modal.js 还是报错

**Comment by wormcc** [comment]
引入zepto了？

**Comment by NotGeekAtAll** [comment]
@wormcc 当然引入了 
还有刚才用gulp编译picker.less也编译不了

**Comment by NotGeekAtAll** [comment]
可以了 是这个原因 [https://github.com/sdc-alibaba/SUI-Mobile/blob/dev/develop.md#dom7](url)
