### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by leesx** [sdc-alibaba/SUI-Mobile#45]
点击连接报这个错，怎么回事。

**Comment by Mickey-** [comment]
没遇到过，具体描述+截图说明一下吧

**Comment by Mickey-** [comment]
有种可能是，你通过 http://m.sui.taobao.org/components/#router 这里的ajax加载新页面的路由方式时，新页面里不是完整的HTML文档。其实你只要保证远端页面里有 `<body>`的成对标签就可以了

**Comment by leesx** [comment]
我也发现了 ，匹配的是body标签。但是你浏览器刷新的时候，页面就乱了。没有加载公共模版的css,js

**Comment by leesx** [comment]
你们给的demo中每个页面的有------layout社么意思。是加载公共模版么

**Comment by Mickey-** [comment]
```
 但是你浏览器刷新的时候，页面就乱了。没有加载公共模版的css,js
```

是的，一个方案是提前ajax加载远端资源进入口页面的各个`.page`里，之后路由调整时便是xxx/yyy#routerx的形式，再刷新就不会地址path不同的问题了。

```
你们给的demo中每个页面的有------layout社么意思
```

这个具体指的是哪里？可以截图说下吗

**Comment by leesx** [comment]
日历在MX5 和 三星note3中 都表现成这个样子。GITHUB 没法上传照片，反正 就是日历 变形很厉害

**Comment by leesx** [comment]
SUI中用的css3属性 display:flex；在移动端有些浏览器中支持并不好。像QQ浏览器中，日历一块变形比较厉害。

**Comment by Mickey-** [comment]
日历在android问题之后单独处理

**Comment by Mickey-** [comment]
@windbell2live 可以参考

**Comment by windbell2live** [comment]
收到
@leesx flex在移动端支持还是不错的
除了老版本的iphone上 flex不支持wrap，以及weixin浏览上 flex下的img不法正常设置width height外(可能是这样的）
