### ISSUE TITLE
图片浏览器不能重复打开

### ISSUE THREAD

**Issue by bigbencat** [sdc-alibaba/SUI-Mobile#453]
问题1:
扩展组建   http://m.sui.taobao.org/extends/
图片浏览器 点击默认模式，关闭，再点击，就关闭不了了。

问题2: 像我这样的没错浏览不同组图片，第二次就失败。
想了一些办法，比如delete对象，也不成功。
$scope.onShowPhoto = function(filename){
            var photo = [];
            for (f in filename) photo.push(filename[f]);
            $scope.myPhotoBrowserStandalone = $.photoBrowser({
                  photos : photo
              });
            $scope.myPhotoBrowserStandalone.open();
        }

**Comment by bigbencat** [comment]
已经看到修复：

 pb.attachEvents(true);
              // Delete from DOM
              if (pb.params.type === 'standalone') {
-                pb.container.removeClass('photo-browser-in').addClass('photo-browser-out').transitionEnd(function () {
-                pb.container.removeClass('photo-browser-in').addClass('photo-browser-out').animationEnd(function () {
                    pb.container.remove();
                });
            }

**Comment by liadbiz** [comment]
@bigbencat  
hi
我也遇到同样的问题。在哪里看到的修复代码？ 这里的pb是指photoBrowser的一个实例吗？

**Comment by liadbiz** [comment]
我的解决方式....
在每一次点击事件开始就把之前的实例移除掉

`
somelink.on('click', function(e){
    $('.photo-browser').remove();
     // other code here
})
`
