### ISSUE TITLE
请问，列表能增加点击标题展开二次点击收缩吗？

### ISSUE THREAD

**Issue by ynioba** [sdc-alibaba/SUI-Mobile#471]
类似的通讯录，如果里面的明细很多。默认A展开，B-Z都是收缩的，找到对方的首字母例如：P，再点击展开，同时A会自动收缩。

非常感谢，这个功能会用到很多地方，特别是超长超大列表的项目中。

**Comment by ynioba** [comment]
哎，不用了，自己搞定了。
加了图标之后，加入以下代码：

<div class="content-block-title">
                    <span class="pull-left">待办事宜</span><span class="icon icon-up pull-right"></span>
                </div>

$(function () {
            $(".content-block-title .icon").click(function () {
                if ($(this).hasClass("icon-up")) {
                    $(this).removeClass("icon-up").addClass("icon-down");
                } else {
                    $(this).removeClass("icon-down").addClass("icon-up");
                }
                $(this).parent("div").next("div").toggle();
            });
        });

**Comment by ynioba** [comment]
请问，相关的API没有吗？我想知道隐藏一个div，带动画的接口有吗？有没有显示一个div一类的接口？

**Comment by ynioba** [comment]
已经没事了，因为我是jquery过来的，对zepto不熟，找到了相关API了。感谢。

**Comment by steavengong** [comment]
@ynioba  请问SUI团队心里阴影面积是多少？
