### ISSUE TITLE
dom树很大切换很卡，有什么优化方案嘛

### ISSUE THREAD

**Issue by QzhouZ** [sdc-alibaba/SUI-Mobile#48]
app首页的dom树很大，这就会造成页面切换很卡，
原因应该是新的页面插入到dom里面，造成了回流，由于dom树大，回流的过程中要重现计算和渲染，所以造成切换动画卡顿，请问有什么优化方案吗？？

**Comment by Mickey-** [comment]
可以放上Demo页地址看下吗

**Comment by QzhouZ** [comment]
@Mickey- 
http://pp.zlzkj.org/sui/
手机打开，点击轮播，切换页面
我测试的是红米note，Android4.4

**Comment by Mickey-** [comment]
身边只有红米 note2，测试感觉还是挺流畅的。你的场景可能需要针对低端机型进行一些通用dom优化了

**Comment by QzhouZ** [comment]
嗯，谢谢你的回答，我再优化优化～
