### ISSUE TITLE
swiper插件在ios浏览器中无法autoplay

### ISSUE THREAD

**Issue by KevinQiaoL** [sdc-alibaba/SUI-Mobile#481]
我把示例中 幻灯片的代码拷贝到我的项目中，发现swiper 在pc和Android的浏览器中，autoplay属性有效，但是ios中无效。请问有类似的问题发生过吗？

**Comment by imxuhao** [comment]
我遇到同样的问题  请问如何解决？  感谢！

**Comment by KevinQiaoL** [comment]
@imxuhao 解决方案就是不用框架内的swiper插件了，改用成swiper官网下载下来的swiper插件了。

**Comment by jquerycn** [comment]
同样遇到这个问题
