### ISSUE TITLE
工具栏

### ISSUE THREAD

**Issue by 396514268** [sdc-alibaba/SUI-Mobile#484]
工具栏要使用自己的图标该如何像你们这样使用？

**Comment by cipchk** [comment]
sui mobile图标都是使用iconfont，使用方法见：http://www.iconfont.cn/help/iconuse.html

**Comment by zhai13** [comment]
iconfont

**Comment by Mickey-** [comment]
参考@cipchk  和  http://m.sui.taobao.org/faq/#iconfont
