### ISSUE TITLE
关于字体大小是使用em, rem, px?

### ISSUE THREAD

**Issue by stevenkaiwang** [sdc-alibaba/SUI-Mobile#488]
大卡们，你好
如果页面中指定字体大小（不使用提供的H1-H6），为了适配不同分辨率，是使用em, rem, 还是PX？
不知在字体适配方面是怎么设计考虑的？

**Comment by lkiarest** [comment]
不考虑兼容性的话推荐rem的方式~

**Comment by stevenkaiwang** [comment]
你好，是什么平台不兼容rem吗？还是什么版本？

**Comment by Mickey-** [comment]
其实都可以用rem，比如sui-mobile。不过字体用rem有反馈说出现大小失真的情况，我们尚未遇到

**Comment by ghost** [comment]
sui-mobile 如何计算rem的。110px_110px的图片得到的是5.5rem_5.5rem吗？

**Comment by xyqfer** [comment]
@ntscs 在 SUI 的规则下是 5.5rem \* 5.5rem

**Comment by stevenkaiwang** [comment]
@ntscs 不一定是5.5rem_5.5rem, 设计师出的效果图是基于IPHONE 5 640的图，则应该2.75rem_2.75rem

**Comment by JSoon** [comment]
rem 不就是基于 root 节点的字体大小么，你的 html 字体是多大，1rem 就是多大，最终都是相对于 root 节点字体大小的倍数吧。

**Comment by stevenkaiwang** [comment]
@JSoon 是基于root html 字体大小，不同IPHONE手机 html字体大小不一样，所以，有一个倍数计算

**Comment by JSoon** [comment]
没有明白你的意思，我理解是这样的，感觉和iphone关系不大：

``` stylesheet
html {
  font-size: 20px;
}
@media only screen and (min-width: 400px) {
  html {
    font-size: 21.33333333px !important;
  }
}
@media only screen and (min-width: 414px) {
  html {
    font-size: 22.08px !important;
  }
}
@media only screen and (min-width: 480px) {
  html {
    font-size: 25.6px !important;
  }
}
```

你的意思是不是在说屏幕宽度？

**Comment by stevenkaiwang** [comment]
你说的是对的； 我们说不同的阶段，我说的是 设计图的PX转换为 REM的计算，你说的是 网页渲染时 REM计算为PX；
