### ISSUE TITLE
跳转页面后页面title没有发生变化？

### ISSUE THREAD

**Issue by Jay-Ivy** [sdc-alibaba/SUI-Mobile#49]
通过内部路由器对象跳转页面后页面的title标题没有发生变化

**Comment by Mickey-** [comment]
是的，因为主页面head里`<title>`内容没变。

可以在`pageInit`监听里在不同内联页加载时动态修改title

**Comment by Jay-Ivy** [comment]
这样做的话返回时又恢复不了title了，返回是不会再次触发pageInit事件的

**Comment by Mickey-** [comment]
sorry没说清楚，利用文档里提供的多个事件接口，针对返回场景，用的是`pageReinit`
![image](https://cloud.githubusercontent.com/assets/2062355/10720554/a2d94b5c-7bd3-11e5-94cf-32a1814b290d.png)

```
$(document).on('pageReinit', '#page-index', function() {
    //setTitle('xxx')
})
```

这个事件只在返回进入页面时触发，你可以试一下

**Comment by xuexb** [comment]
同样遇到了。为啥不根据获取的内容正则匹配出`title`额。

**Comment by Ray1993** [comment]
返回title更新不了
