### ISSUE TITLE
有没有比较好用的函数来刷新当前页面

### ISSUE THREAD

**Issue by dasheng523** [sdc-alibaba/SUI-Mobile#490]
如果我使用`window.location.reload()`来刷新页面，这就相当于全页面刷新了，用户体验不好。
而如果使用`$.router.load(window.location.href,true)`来进行刷新，但一点变化都没有。
是不是这个load函数判断入参url是当前页面就什么事情都不做呢？
我该如何正确刷新页面？

**Comment by Mickey-** [comment]
没有直接的一个函数满足你的需求，你需要的应该是更新当前路由页的数据，你可以尝试手动触发下对应路由页面的pageInit 回调；或者需要你自己封装一下后端接口的调用链路逻辑了

**Comment by cipchk** [comment]
手动触发对应页面的 `pageInit` 回调的；前提必须是你的页面都是通过ajax请求数据；然后在 `pageInit` 渲染相应html，才有效。

另一种思路：其实这个问题在表单比较复杂页面时，按常规思维就用了两个页面（一个view、一个modify）时，就会有这种纠结。其实最好的办法就是，不管表单多大查看和编辑都同一个页面完成。我觉得配合现有一些模板引擎其实很简单。

**Comment by dasheng523** [comment]
谢谢各位。用现有的模板引擎确实是不错的选择，然而目前项目的情况暂时不允许这么做，所以我采用下面的办法解决问题：

```
    $.router.refresh = function(ignoreCache) {
        var url = window.location.href;
        var context = this;

        this._saveDocumentIntoCache($(document), location.href);
        this._loadDocument(url, {
            success: function($doc) {
                try {
                    context._parseDocument(url, $doc);
                    context._doSwitchDocument(url, false,'from-left-to-right');
                } catch (e) {
                    location.href = url;
                }
            },
            error: function() {
                location.href = url;
            }
        });
    };
    $.router.refresh(true);
```

不过，这么做还是不太妥。
