### ISSUE TITLE
how to make page back to the position where i go in?

### ISSUE THREAD

**Issue by sunnyyeyuzhu** [sdc-alibaba/SUI-Mobile#50]
Our team want to write web page just like native effect.And i think this source is closer to what we want.

when apply the router features, form a page to another page ,the sliding effect  is great.

But when i scan a page of news-list, and i find one list to go in.I want when i go back to the news-list, the page is still the position when i go in.Because i dont want to see more news  form the beginning position everytime

**Comment by wenzhixin** [comment]
I think if you don't refresh(rebuild) the news list, the page will be still the same position.
Check out the demo: http://m.sui.taobao.org/demos/.

**Comment by JSoon** [comment]
确实在某些机型上存在这个问题（我手里两台机器，一台是MI3 安卓4.4.4 MIUI7 5.11.5，一台是海信U960Q安卓4.1.2原生浏览器）。其中MI3表现正常，而海信的原生浏览器，列表如果有滚动，进入下一级页面再返回，列表会回滚至页面顶部。marked。

**Comment by xiaran113** [comment]
除了海信还有别的机型复现么，这边试了华为酷派复现不了，没有海信的机器

**Comment by xiaran113** [comment]
#285

**Comment by xiaran113** [comment]
下版本，路由页面的返回问题，将会解决
