### ISSUE TITLE
安卓 Webkit 534.30 版本的浏览器内核下页面渲染性能的问题，极度影响用户体验

### ISSUE THREAD

**Issue by zzkaqq** [sdc-alibaba/SUI-Mobile#503]
项目地址：http://yoo.bilibili.com/html/phone/index.html

使用安卓 Webkit 534.30 内核版本的浏览器打开（如安卓4.2原生浏览器），会发现页面滚动的时候，页面上的元素飘的很厉害，元素的跟不上页面的滚动速度，看起来似乎性能非常差的样子，这个不知道是什么原因引起的？

**Comment by zzkaqq** [comment]
检查了一下原因，应该是transform:translate3d 这个css3的属性引起的，页面上出现问题的元素都有这个属性，但是如果我不引入sui.js，就不会有问题，不知道对这个属性做了什么处理？

**Comment by zhoushan1** [comment]
我也碰到了这个问题 ，暂未解决，不知道什么原因
