### ISSUE TITLE
每次ajax加载页面后都会多出一个.page的div就算

### ISSUE THREAD

**Issue by anilpixel** [sdc-alibaba/SUI-Mobile#51]
![image](https://cloud.githubusercontent.com/assets/7484425/10722932/a215766a-7bf0-11e5-8d32-3d3ecdcc089f.png)

**Comment by linayanse** [comment]
配置中的$.config.pushjs=false并没有起作用。

**Comment by Mickey-** [comment]
[更新日志]里已说明：

**Comment by linayanse** [comment]
我的意思是如果加载的是同一个URL，不会显示DOM中已加载的同ID的DIV，并且还会重新在DOM树插入一份一模一样的内容。我上面的截图可以看到有很多个相同ID的DIV。
