### ISSUE TITLE
BUG--多标签的无限滚动，获取scroller对象的方法可能出错

### ISSUE THREAD

**Issue by YangShaoyue** [sdc-alibaba/SUI-Mobile#514]
SUI版本：0.6.2
Chrome手机调试模式: chrome版本 49.0.2623.87 (64-bit)

无限滚动直接绑定在外层content上，内有4个标签。依次点击每个标签，当点击第三个标签时，浏览器报错：
![image](https://cloud.githubusercontent.com/assets/12428824/13902836/a98db780-ee97-11e5-81a3-2455d8d0ffc6.png)
报错的代码部分：

```
//获取scroller对象
$.getScroller = function(content) {
    //以前默认只能有一个无限滚动，因此infinitescroll都是加在content上，现在允许里面有多个，因此要判断父元素是否有content
    content = content.hasClass('content') ? content : content.parents('.content');
    if (content) {
        return $(content).data('scroller');
    } else {
        return $('.content.javascript-scroll').data('scroller');
    }
};
```

此时log出的`content`：
![image](https://cloud.githubusercontent.com/assets/12428824/13902840/cd4f4120-ee97-11e5-8631-a36bf33f69f9.png)

试了下在`content.hasClass..`的`content`外加上`$(...)`就不再报错。

不知道为什么点击前两个tab获取到的content都是DOM结构，第三个tab获取到的却是个选择器字符串。
希望能尽快修复这个bug

**Comment by Mickey-** [comment]
#569
