### ISSUE TITLE
picker控件的setValue方法不生效

### ISSUE THREAD

**Issue by jayn1985** [sdc-alibaba/SUI-Mobile#525]
目前在做的一个项目使用到了SUI，使用起来得心应手，首先要感谢各位大大的无私奉献精神~
言归正传，在项目中有很多处地方使用到了picker控件，但是发现一个问题就是，picker的setValue方法没有生效，无法动态为picker赋予一个初始值，不知道这是一个bug还是我的使用问题，如果在控件绑定的input节点上显式的使用value属性赋予一个初始值，是可以正常显示出来的，但是这个显然不符合项目的实际使用，烦请看下这个问题，谢谢！

**Comment by wormcc** [comment]
文档中已经写到了，可以在初始化参数中指定value，http://m.sui.taobao.org/components/#picker  
setValue不是用来指定初始值的

**Comment by jayn1985** [comment]
@wormcc
非常感谢，问题已经已经解决了，但是还有个额外的问题是：这个setValue方法究竟是使用在什么样的场景里的？

**Comment by wormcc** [comment]
@jayn1985 http://codepen.io/wormcc/pen/LNyrMj 在初始化后可以进行setValue设置值

**Comment by 347830076** [comment]
请问下你是怎么解决动态初始化值了？可以教下吗？

**Comment by wggCode** [comment]
初始化后调用setValue 不工作,经测试只有open过后的picker, setValue才工作

**Comment by shayupi** [comment]
@jayn1985 你好请问动态初始化picker 的value值这个问题你是怎样解决的？

**Comment by HiJesson** [comment]
可以通过直接对input value赋值+初始化picker时候设置value值来达到效果。

$('#monthPicker').val(“2018-9”);   //未点击时候显示
$('#monthPicker').picker({
				value:['2018','9'],  //数组，在第一次点开时候，被赋值上去
				cols:[
					{
						textAlign:'center',
						values:['2017','2018','2019']
					},{
						textAlign:'center',
						values:['1','2','3','4','5','6','7','8','9','10','11','12'],
					}
				],
				formatValue:function (p,value,displayValue){
					return displayValue[0]+"-"+displayValue[1]
				}
			});
