### ISSUE TITLE
正常引入css和js

### ISSUE THREAD

**Issue by phillipxu** [sdc-alibaba/SUI-Mobile#530]
在引用了<link rel="stylesheet" type="text/css" href="common/css/sm.css"/> sm.css后  $(window).scroll(function(){
            alert("ddddddddd")
        })
scroll事件不能执行。。。。

**Comment by xyqfer** [comment]
```
$(".content").scroll(/**/)
```

记得区分 `page`

**Comment by phillipxu** [comment]
$(".content").scroll(function () {
            /*var sTop = $(window).scrollTop();
            var sTop = parseInt(sTop);

```
        var silde = parseInt($("#slide3").height());
        $(".common-nav").css("opacity",sTop/silde);*/
    alert(".......")
    });
```

然而并没有执行。。。什么都没有

**Comment by phillipxu** [comment]
$(".content").scroll(function () {
        var sTop = $(".content").scrollTop();
        var sTop = parseInt(sTop);
        var silde = parseInt($(".topImg").height());
        $(".common-nav").css("opacity",sTop/silde);
    });可解决。。。window不行。得用dom对象
