### ISSUE TITLE
在ios微信浏览器中点击select后立马失去焦点。

### ISSUE THREAD

**Issue by bobhfut** [sdc-alibaba/SUI-Mobile#542]
在微信平台开发中ios系统select控件点击后失去焦点或者焦点错乱
应该是click事件的处理问题，请求修复

**Comment by dqmmpb** [comment]
失焦问题好我也遇到了，感觉可能是fastclick引起的

**Comment by Gcaufy** [comment]
@dqmmpb 
请问这个问题有结论没有, 我也碰到了这个问题.  IOS + 微信浏览器 + fastclick.
非必现, 但是问题比较难定位.

**Comment by luoyjx** [comment]
#581 说明了这个问题

**Comment by Gcaufy** [comment]
@luoyjx 问题过去太久了，最后直接不使用原生SELECT去防止此问题，何不给fastclick提个pr?
