### ISSUE TITLE
Picker的问题

### ISSUE THREAD

**Issue by smanor** [sdc-alibaba/SUI-Mobile#55]
1、通过路由放问到一个新页面，第一次Picker不起作用，需要刷新下才能点击触发
2、如果Picker只有一列时，在IOS上点开Picker之后，触摸空白处时，存在兼容性问题，会整屏幕往上移动了

**Comment by smanor** [comment]
http://web.cnvp.com.cn/cbd/2015/sui
做好的demo，日期选择时，经常出现错误调至1950去了

**Comment by Mickey-** [comment]
多谢，请保持Demo可访问
