### ISSUE TITLE
你好，一个页面的标签页切换，各标签里面的无限滚动实现应该怎么搞定呢？

### ISSUE THREAD

**Issue by yaochenfeng** [sdc-alibaba/SUI-Mobile#56]
你好，一个页面的标签页切换，各标签里面的无限滚动实现应该怎么搞定呢？

**Comment by wenzhixin** [comment]
现在应该不支持，你可以考虑用 [router](http://m.sui.taobao.org/components/#router) 的方式来实现。

**Comment by xiaran113** [comment]
@yaochenfeng  楼上正解
