### ISSUE TITLE
在微信中使用router进行页面跳转，会导致jssdk校验失败

### ISSUE THREAD

**Issue by gostop54** [sdc-alibaba/SUI-Mobile#564]
如题，目前看是因为微信内置的浏览器不支持pushstate

所以jssdk获取的url和签名使用的url不一致

有没有什么好的解决办法?

**Comment by gostop54** [comment]
做成SPA了，这个问题暂时这样解决了...

**Comment by chaotianwww** [comment]
@xttanwei spa是什么鬼？能解释一下吗？

**Comment by jacobcyl** [comment]
@xttanwei 请问你是怎么解决的

**Comment by bingzheyuan** [comment]
估计是Single Page Application,单页应用，啥都放在一页上面，没跳转
