### ISSUE TITLE
sui mobile的icon怎么显示不了？？？

### ISSUE THREAD

**Issue by elsonwx** [sdc-alibaba/SUI-Mobile#568]
加载了半天，然后显示一个大口？？
按照例子做了一个demo,但是图标都显示不了？

**Comment by dqmmpb** [comment]
你的css中是不是用了*{ font-family: }？自己的字体把sui的字体覆盖掉了

**Comment by elsonwx** [comment]
没有啊，我把demo保存下来里面的icon也显示不了 @dqmmpb

**Comment by dqmmpb** [comment]
项目demo没问题的，是不是你的过程不对
1.git clone源码到本地
2.安装nodejs grunt 请自行百度
3.安装jekyll [请见官网](http://jekyll.bootcss.com/)
4.grunt构建项目
5.执行jekyll serve启动本地server
6.浏览器中敲地址

**Comment by elsonwx** [comment]
@dqmmpb 应该是我的过程不对，我只想先做一个demo放到本地看下效果，没有用到nodejs也没有用到jekyll.就引用了几个css和js，然后做的html demo，icon都不显示。不过把网页放到服务器上本地用网址访问又可以显示icon, 总之谢谢你啦

**Comment by dqmmpb** [comment]
@elsonwx 浏览器调试下看，应该font的字体有没有加载，或被自己的font覆盖掉了，再有就是构建的时候css的引用路径什么的有问题
