### ISSUE TITLE
picker displayvalues问题

### ISSUE THREAD

**Issue by xexojay** [sdc-alibaba/SUI-Mobile#58]
设置了displayvalue后，选项里面显示的是displayvalue，但在选择了选项后，input直接显示的是value，这样就没法达到选中后在input里面显示displayvalue的效果

**Comment by howelin** [comment]
本地不能重现问题，请加群1278550944具体描述下，还有用了什么终端？

**Comment by Mickey-** [comment]
这是特性如此。

picker展示时用displayValues，选择完后将value值置入input，而input组件的值和展示是相同的，所以有这种情况。

你的需求可能需要在业务里封装一下，将input隐藏，弄个div覆盖上去，在`onchange`的时候更新input值后，改变div上的内容
