### ISSUE TITLE
toast左右不居中

### ISSUE THREAD

**Issue by p-zhan** [sdc-alibaba/SUI-Mobile#592]
SUI版本：v0.6.2
备注：按照[Github Issue#143](https://github.com/sdc-alibaba/SUI-Mobile/issues/143)中的解决方案，将Zepto替换成了jQuery
问题描述：$.toast(text) 左右不居中
console报错信息：Cannot read property '0' of undefined
具体描述：错误位置在sm.min.js:formatted第3500行，b.targetTouches[0].pageX:b.pageX,此处b.targetTouches值为undefined

PS：
查看更新日志，貌似在v0.3.0修复过这个问题，不知道是不是代码又改回去了？

PPS：将Zepto换成jQuery真的会出问题吗？可能是哪种问题？严重吗？

**Comment by p-zhan** [comment]
更新：jQuery冲突
找到原因了，确实是因为将Zepto换成jQuery造成的，jQuery中的event没有targetTouches这个属性

**Comment by xyqfer** [comment]
建议使用 [Light7](http://light7.cn/)，`Zepto` 、`jQuery` 均支持

**Comment by p-zhan** [comment]
@xyqfer 谢谢，仔细比对了一下，light7确实不错。
不过因为现在做的项目是在微信里面的，所以打算使用weui了，有一个weui的扩展做的还不错[jQuery WEUI](http://lihongxun945.github.io/jquery-weui/)

**Comment by xyqfer** [comment]
@arange `jQuery WEUI` 跟 `Light7` 是同一个作者

**Comment by JSoon** [comment]
看你们说了半天，其实都在说一个人， @lihongxun945 要不您就为何出light7和sui-mobile除了依赖的dom库不同其他都一样的问题，出来回应一下![lol](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by sulishibaobei** [comment]
文字过多超出屏幕居然不换行也不居中
