### ISSUE TITLE
微信中的返回按钮按下去后，前页面的 JS 不会运行

### ISSUE THREAD

**Issue by grantchen** [sdc-alibaba/SUI-Mobile#594]
如果我在微信里面，通过下面的工具栏，从 A 页切换到 B 页面，A 页面，B 页面都能正常工作，在 B 页面这时，点击微信里面的左上角的返回按钮回退到 A 页面，A 页面的 JS 就失效了。

我在 chrome 里面测试返回按钮是没有问题的，不太清楚微信浏览器是怎么工作的？ 有大神也遇到类似问题吗？

**Comment by JSoon** [comment]
用代码简单描述一下页面的DOM结构，然后再描述一下场景。

**Comment by grantchen** [comment]
自己通过尝试扩大监听范围解决了这个问题，但原因不是很清楚。

```
$(".xxx").on('click', function(e){ ... })
```

将监听的扩展范围变大之后就解决这个问题了。

```
$("body").on('click', '.xxx')
```

**Comment by rainbowzx** [comment]
我发现 把js代码块放到 page-group里面就可以

**Comment by Jude214** [comment]
确实是，我不是在微信中，但扩大监听范围后返回上一页面点击按钮还生效。@grantchen 有人知道原理吗？
