### ISSUE TITLE
微信浏览器，input type 为date，没有日期选择框

### ISSUE THREAD

**Issue by qiao2818** [sdc-alibaba/SUI-Mobile#6]
使用此ui作为web.
在微信中打开，按照官网加载所有css与js。
<input required="required" placeholder="请输入出生日期" type="date" name="patient[birth]" id="patient_birth">
没有日期选择框。

设备：android

**Comment by Mickey-** [comment]
文档里并没有input type 为date 的日期选择框用法，请使用 http://m.sui.taobao.org/components/#calendar 或 http://m.sui.taobao.org/components/#datetime-picker 的方案
