### ISSUE TITLE
【日历】点击选择在安卓手机中会出现输入法

### ISSUE THREAD

**Issue by muchard** [sdc-alibaba/SUI-Mobile#60]
<input type="text" value="2014-04-30" data-toggle="date" readonly="readonly">
加了readonly也会出现。

**Comment by Jay-Ivy** [comment]
是的呢，目前我也遇到这个问题，正在找办法呢，不过还没找到，谁来解决解决！

**Comment by mingxing** [comment]
一样，出现了！加了readonly没有作用

**Comment by Mickey-** [comment]
具体的系统、版本号、浏览器信息麻烦都贴一下吧    @muchard  @474188765 @mingxing

**Comment by muchard** [comment]
@Mickey-  手机型号：魅族MX4，安卓版本：5.0.1，flyme系统 4.5.4A，浏览器微信，UC都一样，输入法：百度输入法。我明天找一下别人的机器也试一下，用Framework7 demo也有这个问题。可能是Framework7 本身有这样的bug，有人说安卓的都会，但没试过太多机器。 使用小米4测试没事。

**Comment by mingxing** [comment]
@Mickey- ,手机型号：Oppo 700，安卓版本，4.4.4，ColorOS系统V2.0.1

**Comment by njleonzhang** [comment]
一下手机也有这个问题：
小米4，Miui 7, android 4.4.4 ,最新版本的微信内置浏览器。
中兴手机，android 4.3，最新版本的微信内置浏览器。

update：
我找到了一个workaroud: 从fastclick.js里删除 FastClick.prototype.onTouchEnd 函数就可以解决这个问题了。我希望有助于维护人员对位问题

**Comment by mingxing** [comment]
亲，这个问题依然存在，你们呢？
期待能有所更新，多谢

**Comment by suhaotian** [comment]
建议使用 div 替代 input 标签

**Comment by Mickey-** [comment]
#12
