### ISSUE TITLE
点击链接显示左侧边栏时，有时出现2个

### ISSUE THREAD

**Issue by shuiyuee** [sdc-alibaba/SUI-Mobile#64]
在点击显示左侧边栏链接时，有时出现2个
code：<a class="icon icon-me pull-left open-panel">pull left</a> 
点击侧边栏的关闭时，主页面逐渐向左移动，侧边栏逐渐变小，但在到了某个宽度时会侧边栏会突然全关闭，没有了渐进的过程
![sui-pullleft-bug](https://cloud.githubusercontent.com/assets/15197204/10988391/d17b191c-8476-11e5-97bb-72ab7a5d07d1.jpg)

**Comment by smanor** [comment]
侧边栏需要单独写的，不能每个页面都存在

**Comment by Mickey-** [comment]
请说明何时出现2个，最好贴代码出来展示一下 http://jsbin.com/?html,output
