### ISSUE TITLE
如何手动触发日历组件？

### ISSUE THREAD

**Issue by Array-Huang** [sdc-alibaba/SUI-Mobile#647]
在文档里看到的都是通过点击<input />来触发的，而在我的app里为了保持UI风格一致，希望能通过一个按钮来触发。

我试过用zepto来手动trigger该input框的click事件和focus事件：focus事件根本无效；click事件则不知怎的直接把默认日期填到inpunt框里就了事，整个日历根本都没打开界面。

**Comment by wggCode** [comment]
大兄弟,如下:

`$("#inputCalendar").triggerHandler("click");`

**Comment by Array-Huang** [comment]
@wggCode trigger和triggerHandler我都试过了，没有任何反应。当初是试出来会把默认日期填上去的，现在连这个效果也没有了

**Comment by wggCode** [comment]
经测试没有问题,请注意你的代码是否符合SUI标准. 比如各个js 的引用位置等.

可以下载看此动图,http://pan.baidu.com/s/1c2igmL6
