### ISSUE TITLE
demo报错 Uncaught Error: can't find .page element

### ISSUE THREAD

**Issue by djfly** [sdc-alibaba/SUI-Mobile#65]
http://m.sui.taobao.org/extends/#browser

`Uncaught Error: can't find .page element`

**Comment by djfly** [comment]
顺便问下，我这样写为什么报错,我想实现单击图片的时候关闭图片浏览器，文档里应该写明怎么关闭图片浏览器吧？只有个`myPhotoBrowserStandalone.open();`

``` js
var myPhotoBrowserStandalone = $.photoBrowser({
      photos : arr,
      theme : 'dark',
      toolbarTemplate : '<nav class="bar" style="background:none;color:#fff"><center><span class="photo-browser-current"></span>/<span class="photo-browser-total"></span></center></nav>',
      navbarTemplate : '.',
      onClick: function(swiper, e){myPhotoBrowserStandalone.close();} //就这句报错
    });
```

错误
`Uncaught TypeError: Cannot read property 'emitterEventListeners' of null`

**Comment by Mickey-** [comment]
`myPhotoBrowserStandalone.close` 接口调用方式没错，相信你的demo应该可以正常执行。

`Cannot read property 'emitterEventListeners' of null`报错信息是图片浏览器连带的幻灯片组件的处理问题，目前不影响组件功能，下个版本会修复这个报错问题，同时更新文档说明

至于官网文档的报错是因为PC页面引用了SUI-Mobile的资源，但文档页并没有按移动端html布局编写造成的，这个先忽略吧~

感谢提醒！

**Comment by Mickey-** [comment]
幻灯片详细配置参数已补充到文档。不影响功能的报错会在0.5.3修正发布

**Comment by 627565157** [comment]
我使用的type: 'popup' 方式来打开图片浏览器。close方法对于这种打开方式确实不起作用。我的关闭方式是：
if(myPhotoBrowserStandalone.opened){
        myPhotoBrowserStandalone.opened=false;
        $.closeModal(".photo-browser-popup");
    }
