### ISSUE TITLE
chrome下 router 返回 似乎有问题？

### ISSUE THREAD

**Issue by falconlux** [sdc-alibaba/SUI-Mobile#66]
RT

**Comment by wenzhixin** [comment]
就不能加点详细描述吗？是什么问题，什么情况下出现。

**Comment by zhengnz** [comment]
我测试后发现chrome下点击一次加载新页面，再点击一次返回无反应，但是点击浏览器的向前，再来点击返回，就开始正常了

**Comment by jzlxiaohei** [comment]
同样表示有问题，示例中，点击任意一个列表项，再点返回，我这边都有问题

几乎用了所有功能（拓展组件除外），就觉得路由这块非常不爽

比如router的back功能: 如果点击 `class='back' href='#page-main'`,很明显是想跳回`#page-main`，把动效做出来就好。但是刷新之后，点击返回键，url中有`#page-main`,但是任何效果都没有。

个人认为路由应该根据url来执行逻辑，`back`和`forward`只是页面的动画效果而已

**Comment by Mickey-** [comment]
前言：**以下说明均基于 0.5.1 版本，并且大部分视图切换属于SPA应用**

目前的前进后退功能是按照历史栈的顺序执行的，会忽略可选的 url 参数。  
如果希望直接跳到主页之类非上一页的视图，可以给链接加`.external`的class。此时相当于在重新加载对应页面。

有个注意点，如果在非入口页刷新页面， **点击返回会直接回到入口页。**

其他具体问题直接开一个带有详细说明的issue吧
