### ISSUE TITLE
请问 Light7 和 SUI-Mobile 两者之间有什么联系么？

### ISSUE THREAD

**Issue by shery** [sdc-alibaba/SUI-Mobile#671]
近期尝试了一下SUI-Mobile，偶然发现Light7和 SUI-Mobile几乎一模一样，这个项目有什么联系么？？？

**Comment by xinconan** [comment]
感觉Light7是模仿SUI-Mobile的，例子都是抄SUI的

**Comment by zxzhgk** [comment]
我也想问，而且Light7支持jquery版本的js

**Comment by hhun** [comment]
Light7应该是在SUI的基础上完善的，算是第三方的分支版本吧！

**Comment by ArcRain** [comment]
其实Light7的作者有声明过这个关系：https://github.com/lihongxun945/light7/blob/master/README-CN.md

**Comment by shery** [comment]
@ArcRain 了解了，谢谢
