### ISSUE TITLE
ajax回调函数里面怎么使用对话框？

### ISSUE THREAD

**Issue by sensexjw** [sdc-alibaba/SUI-Mobile#68]
在ajax的回调函数中无法正常弹出对话框，但绑定页面元素点击事件中是可以的。ajax调用代码如下：
$.ajax({
    url : "dosomething",
    async : false,
    dataType : 'json',
    data : {
        type : 'json'
    },
    success : function(obj) {
        $.alert("调用成功");
    },
    error : function(obj) {
        $.alert("调用失败");
    }
});

**Comment by Mickey-** [comment]
这个问题和sui-mobile 本身无关吧… 

另外我将你的代码在一个我们的使用了MSUI的页面里执行后，是可以弹出对话框的，所以请检查下你的代码吧，可能是哪里写错了

![screenshot](http://img2.tbcdn.cn/L1/461/1/bf43774329a8a501889a0e7e219e7da09694a53f)

**Comment by sensexjw** [comment]
原因已经查明，ajax方法的async属性必须设为true，告警框、toast、加载提示框都会随着ajax方法结束而销毁。
