### ISSUE TITLE
请问可以结合使用f7的router吗？

### ISSUE THREAD

**Issue by zhengnz** [sdc-alibaba/SUI-Mobile#69]
目前msui的router使用后感觉有问题，之前有在一个issue里反馈过，可是答案看起来解决不了，所以想请问下能否结合msui使用f7的router

**Comment by Mickey-** [comment]
之前有过更新发布， 0.5.1 版本解决了路由的已知问题。不知道你说的问题是什么，另外 MSUI会下个小版本会支持默认不使用Router的配置

**Comment by Mickey-** [comment]
0.5.2 已发布，可以通过配置项关闭默认启用的router，然后你可以自选任何路由系统使用
http://m.sui.taobao.org/changelog/

**Comment by zhengnz** [comment]
测试后发现router可以了，谢谢Mickey
