### ISSUE TITLE
关于无限滚动不能用的问题

### ISSUE THREAD

**Issue by TenOneD** [sdc-alibaba/SUI-Mobile#72]
在做web app的时候，添加了infinite容器，事件以及对应的Js库文件，但是依旧无法侦听到滚动事件
// 注册'infinite'事件处理函数
$(document).on('infinite', '.infinite-scroll', function() {
  alert("hello");
}
发现在页面上会有'application/x-shockwave-flash'这个mimetype为null，不知道是不是chrome在模拟手机端的时候并没有flash插件.也不知道是不是这个错误会阻塞到infinite的js代码，也不知道是sm.js是不是有一种判定来靠flash来表现什么。
页面中已经添加了 容器的content和infinite-scroll

**Comment by TenOneD** [comment]
解决了，两个地方
1：infinite事件要在pageInit里面
2：要执行$.init方法才能生效

**Comment by Mickey-** [comment]
感谢，作为tips了提醒大家了

**Comment by TenOneD** [comment]
不知道是不是这个产品是一个附属产品，总感觉作为作者没有好好去写文档

**Comment by Mickey-** [comment]
初始化、入口相关说明 在这里有说  http://m.sui.taobao.org/components/#init
还是不够醒目吧

**Comment by TenOneD** [comment]
没，当我没说吧。我再理解理解，也许是太着急了，没统筹把握好就开始用的缘故

**Comment by yunnian** [comment]
唉，我也遇到这样的问题了！！！！  要是没翻到 这里，真不知道怎么解决。

**Comment by yunnian** [comment]
我的照着你做了 还是不行 和Demo 也没什么不一样啊

**Comment by xiaocai-rookie** [comment]
我就把网站上的demo复制到本地都不能运行

**Comment by xiaocai-rookie** [comment]
无限滚动 的事件根本出发不了  而且放在 pageInit 事件里面 pageInit 也触发不了

**Comment by xiaocai-rookie** [comment]
无限滚动 不能触发  https://jsfiddle.net/rookie_xiaocai/7r5xr87d/1/

**Comment by carroll0911** [comment]
content  加上两个class    infinite-scroll native-scroll   就正常了
