### ISSUE TITLE
拓展组件：幻灯片，IOS 自动播放失效

### ISSUE THREAD

**Issue by shery** [sdc-alibaba/SUI-Mobile#724]
拓展组件：幻灯片，
手动初始化配置，开启自动播放，在安卓端可以自动播放，IOS 无法自动播放

**Comment by upshan** [comment]
JS 中加入代码
$(".lunbo").swiper({
            autoplay: 3000  //可选选项，自动滑动
        });
lunbo 为轮播图片的样式

**Comment by shery** [comment]
$(".swiper-container").swiper({
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: 2500,
        autoplayDisableOnInteraction: false
    });
我是这么配置，但是没有生效  @upshan

**Comment by edge2012** [comment]
自己写了一个定时器滚动，swiper 的相关方法都是有效的

**Comment by shery** [comment]
@edge2012 看来暂时只有这样了。
