### ISSUE TITLE
searchbar中的searchbar-cancel的click事件有时候不响应。间歇性的不响应

### ISSUE THREAD

**Issue by feitiana03120** [sdc-alibaba/SUI-Mobile#729]
$(document).on("click", ".searchbar-cancel", function(e) {
            console.log(1)
           //$('input[type="search"]').val('').trigger('change');//取消搜索
            var $btn = $(e.target);
            $btn.parents(".searchbar").removeClass("searchbar-active");
        });

**Comment by 1402445822** [comment]
...先生/小姐：
　　您好！感谢您的来信，我暂时没空，稍后回复您！
