### ISSUE TITLE
0.5.1中$.router.loadPage()加载页面问题

### ISSUE THREAD

**Issue by mhyailz** [sdc-alibaba/SUI-Mobile#73]
Hello guy：

场景：app主页（pageId为index）中一个登录按钮跳转到登录页面（pageId为login），需要当输入完登录信息跳转到app主页并刷新主页html内容。

1、如果通过内联标签的形式，在login页面中调用$.router.loadPage('#index')，可以回主页但不能刷新
2、如果通过ajax形式，在login页面中调用主页的url地址：$.router.loadPage('/app/index')，可以回主页，但当前容器就生成两个id为index的页面，而且回退事件会出错。
![image](https://cloud.githubusercontent.com/assets/2506136/11059509/1e326a06-87d5-11e5-83bf-83ca06937bc0.png)

建议：在loadPage加载ajax的时候，如果容器中有同样id的page时，用最新.page内的内容替换而不是直接在容器中再插入一个page。

或者有不修改可以解决办法吗？

Best regards!

**Comment by Mickey-** [comment]
http://m.sui.taobao.org/components/#router
![screenshot](http://img1.tbcdn.cn/L1/461/1/5dcefbae81f030caf4b6c2ea568a3dc49bf67c5d)

内联形式就可以满足需求。你的场景可以监听返回到主页的事件，事件句柄里查询登录状态并条件更新主页视图的内容

**Comment by mhyailz** [comment]
@Mickey- 明白你的意思。但这种方式需要在主页init后再与服务器交互获取登录信息，然后js修改主页内容，可以实现感觉有点绕。想了一下，我还是修改下场景模型，在登录页面的服务器端做逻辑判断。
thx
