### ISSUE TITLE
路由问题 - ajax跳转页面js执行正常，但是刷新此页面后js就不执行了，求助，项目很急，附有测试地址。

### ISSUE THREAD

**Issue by WormGirl** [sdc-alibaba/SUI-Mobile#733]
ajax跳转页面js执行正常，但是刷新此页面后js就不执行了，刷新后后退到首页，首页pageinit里的js也不执行，求助，项目很急，附有测试地址。
测试地址：test.hqb2c.com，从首页到商品详情页，详情页js正常执行，刷新详情页pageinte里的代码就不执行了。在console可以看到此页面js有没有执行的日志。
还有另外一个问题：下面这段代码必须放到页面里才能执行，放到外部js里就不执行了，好像是pageinite绑定不上，我在后面执行了$.init 。
$(document).on("pageInit","#index", function(e, id, page) {
              $("#contain").on("scroll",function(){ //绑定滚动条事件
                  var p = $(this).scrollTop();
                  p >= 50 ? $("#my-bar").addClass('fixed'): $("#my-bar").removeClass('fixed');
              });
      });

**Comment by guohuihot** [comment]
应该是要路由的页面里要把所有的js都加载才对，只有普通的跳转才是各是各的js

**Comment by WormGirl** [comment]
问题已经解决，是我自己的问题，$.init()少写了括号，希望不要有人再犯我这种傻逼错误，sui还是很不错的。

**Comment by Niofh** [comment]
你是ajax跳转由js执行啊，我这个不行啊，路由过去了，js没有执行啊！求帮助

**Comment by cqgsm** [comment]
我的是 路由跳转正常，刷新当前页面就不执行了，搞了好久，原来要把$.init()写到 js最下面就ok了
