### ISSUE TITLE
通过其他按钮 操作$("input[type='file']").click()失败

### ISSUE THREAD

**Issue by limingxinleo** [sdc-alibaba/SUI-Mobile#748]
这里是测试地址：http://sui.tp5.lmx0536.cn/wap/test/upload

简单说一下，之前的解决办法是调用两次click()时间：如下
`function test() {
        $("#file_addr_pic").click();
        $("#file_addr_pic").click();
 }`
但是PC版和有的机型 却会连续成功执行两次，所以根本无法这样解决。
但是我后来发现，如果在调用函数前，先点击一次checkbox后。执行如下函数，就没有任何问题
`function test() {
        $("#file_addr_pic").click();
 }`
如果官方还继续维护此项目，希望可以尽快修正这个问题。
谢谢

**Comment by limingxinleo** [comment]
官方都不看的么？？

**Comment by ACzero** [comment]
原因是sui引入了FastClick，看这里
http://www.2cto.com/kf/201509/442506.html

**Comment by c9n** [comment]
解决方法：

```html
<div id="file_addr_pic" class="needsclick"></div>
```

增加类 `class="needsclick"`
