### ISSUE TITLE
Fixed tab顶部滚动异常

### ISSUE THREAD

**Issue by edge2012** [sdc-alibaba/SUI-Mobile#749]
fixed tab 在顶部的时候 ，点击列表中的项，再返回回列表，顶部的tab无法再正常回到原来位置

**Comment by anyone-yuren** [comment]
有在线实例吗

**Comment by edge2012** [comment]
@niyg   重现办法发你 1003473088@qq.com  了

**Comment by edge2012** [comment]
修改 Tabs 代码，在FixedTab Plugin 中重新初始化，并设置fixedTop值为初始状态是的高度

**Comment by phonet** [comment]
@edge2012 你好,请问下你的这个问题,最后解决了吗?解决的代码能不能贴出来看看,谢谢

**Comment by edge2012** [comment]
@phonet  一直没上来看，问题处理了么，我在上面结贴发了处理办法
