### ISSUE TITLE
手机号码显示为链接-only ios

### ISSUE THREAD

**Issue by mingxing** [sdc-alibaba/SUI-Mobile#75]
遇到一个奇怪的问题，页面的手机号，显示为链接的样式，可以点击，但是提示“加载失败”；是不是ios认为是手机号，想点击调用拨号，但是SUI不做处理，于是显示加载失败？

有人遇到类似的问题么？

多谢

**Comment by Mickey-** [comment]
你页面里手机号那块的HTML结构是怎样的，贴图或者fiddle看下吧

**Comment by mingxing** [comment]
直接在item-after的div里显示
![phonenumber](https://cloud.githubusercontent.com/assets/797557/11174708/293f0034-8c63-11e5-939f-7cee0e13bee2.png)

**Comment by jzlxiaohei** [comment]
我之前遇到过：
class里加external, 然后 href='tel:11111'

**Comment by Mickey-** [comment]
@jzlxiaohei 感谢提供实践。

另外最佳方法是在HTML的<head>里添加如下 meta属性，即可关闭IOS默认的format逻辑

```
<meta name="format-detection" content="telephone=no">
```

**Comment by laodaobazi** [comment]
该问题我也是遇到了，不仅仅是电话号码点击的时候会提示“加载失败”，日期格式也是允许点击，点击之后同样的提示。
