### ISSUE TITLE
SUI alert确定按钮乱码问题

### ISSUE THREAD

**Issue by tangj1206** [sdc-alibaba/SUI-Mobile#759]
不知道是我设置的不对还是什么情况 在使用$.alert时确定按钮始终是乱码
纭畾

**Comment by tangj1206** [comment]
解决了：
1.每个页面都设置<meta charset='utf-8'/>

**Comment by 13269074211** [comment]
？？？？？？？？？怎么解决的？？？？？？？？

**Comment by sulishibaobei** [comment]
怎么解决急求

**Comment by tangj1206** [comment]
@sulishibaobei  因为很长时间没用了  SUI 的alert有许多基础配置项 在你用到的页面都要配置一下 把配置项都写一下
