### ISSUE TITLE
用Router加载新页面，POPUP弹出层会移动到所有Page元素外面

### ISSUE THREAD

**Issue by laoxubuer** [sdc-alibaba/SUI-Mobile#76]
用Router加载新页面，POPUP会有问题，比如现有页面B是从页面A通过路由点击进来的，页面B底部有一个fixed层，需要它永远保留在最顶层，但是，路由进来的页面点击.open-popup之后，.popup会被移动到page同一层级，导致fixed层无法盖在.popup层之上。
![image](https://cloud.githubusercontent.com/assets/7135991/11088580/62208ba2-889e-11e5-8683-e21f6e822177.png)

**Comment by Mickey-** [comment]
http://m.sui.taobao.org/demos/ 可以在Demo页审查元素，不仅popup，panel组件也是，都和page节点是同级元素

**Comment by laoxubuer** [comment]
事实上我是不想让它变成同级元素

**Comment by Mickey-** [comment]
SUI-Mobile里的popup都是全局弹出的，你的需求需要你在业务模块里实现了
