### ISSUE TITLE
Github中LESS源码在安卓版微信中的问题[useless]

### ISSUE THREAD

**Issue by laoxubuer** [sdc-alibaba/SUI-Mobile#77]
本来是希望直接修改LESS文件，减少代码冗余的，但是一开始上手的时候发现这里的源码flexbox的mixins顺序不太正确(把旧版本写法放在后面就正常了)，导致在安卓（4.4.2）版微信中不起作用，其他自带浏览器一切正常。置于其他坑不太清楚。所以直接调用了CDN......

**Comment by Mickey-** [comment]
你好，如果有代码冗余的问题，我们也是需要解决的。然后你说的

```
源码flexbox的mixins顺序不太正确(把旧版本写法放在后面就正常了)，导致在安卓（4.4.2）版微信中不起作用
```

具体是指什么，可以举例说明或发个pull request说明下吗

**Comment by laoxubuer** [comment]
不好意思，这个是我设置的Autoprefixer的错误，设置了last 2 version,会自动清除display: -webkit-box;之类的旧版本样式，但是不知道为什么我改成下面的顺序又不会忽略-webkit-box
.flexbox() {
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
 display: -webkit-box;
}
