### ISSUE TITLE
页面重复加载[useless]

### ISSUE THREAD

**Issue by sensexjw** [sdc-alibaba/SUI-Mobile#78]
以下页面加载后，访问历史中会出现两条相同的信息。这导致用路由或者浏览器自带的回退按钮都必须点两次才能回到上一个页面。目前可以肯定的是由于page init引起的。如果去掉div的page page-current类，问题就会消失。
这个问题在chrome和猎豹上都能复现

&lt;HTML lang="en"&gt;
&lt;HEAD&gt;
    &lt;LINK href="http://g.alicdn.com/sui-mobile/sm/0.5.0/css/sm.min.css" rel="stylesheet"&gt; 
    &lt;LINK href="http://g.alicdn.com/sui-mobile/sm/0.5.0/css/sm-extend.min.css"&gt; 
&lt;/HEAD&gt; 
&lt;BODY&gt;
    &lt;DIV class="page page-current"&gt;1&lt;/DIV&gt;
    &lt;SCRIPT src="http://g.alicdn.com/sj/lib/zepto/zepto.min.js" type="text/javascript" charset="utf-8"&gt;&lt;/SCRIPT&gt;
    &lt;SCRIPT src="http://g.alicdn.com/sui-mobile/sm/0.5.0/js/sm.min.js" type="text/javascript" charset="utf-8"&gt;&lt;/SCRIPT&gt;
    &lt;SCRIPT src="http://g.alicdn.com/sui-mobile/sm/0.5.0/js/sm-extend.min.js" type="text/javascript" charset="utf-8"&gt;&lt;/SCRIPT&gt;
&lt;/BODY&gt;
&lt;/HTML&gt;

**Comment by Mickey-** [comment]
SUI-Mobile你用的哪个版本？是在移动浏览器上发现的吗

**Comment by sensexjw** [comment]
用的0.5.0版本，pc浏览器和移动浏览器表现一样

**Comment by Mickey-** [comment]
那先升级到0.5.2 版本再试一下吧 

注意资源的路径有点小变化，在 http://m.sui.taobao.org/changelog/ 这里有说明

**Comment by sensexjw** [comment]
升级到0.5.2问题解决
