### ISSUE TITLE
左边栏里面有input的时候 在ios下面 点击输入框 侧边栏就错位了 谁碰到过 如何解决？

### ISSUE THREAD

**Issue by bihongbin3027** [sdc-alibaba/SUI-Mobile#79]
左边栏里面有input的时候 在ios下面 点击输入框 侧边栏就错位了 谁碰到过 如何解决？

**Comment by njleonzhang** [comment]
我在ios 9的微信内置浏览器里用datepicker的时候就会出现这样的情况。求解决方法

**Comment by Mickey-** [comment]
来放个fiddle例子或你们的页面Demo吧
