### ISSUE TITLE
if (layer.style.msTouchAction === 'none' || layer.style.touchAction === 'manipulation') {}

### ISSUE THREAD

**Issue by xiaoqiang730730** [sdc-alibaba/SUI-Mobile#8]
Uncaught TypeError: Cannot read property 'style' of null 
我在chrome里面 模拟手机的时候 layer是undefined

**Comment by opendever** [comment]
同样的问题

**Comment by Mickey-** [comment]
这是[fastclick](https://github.com/ftlabs/fastclick)的判断脚本，通常是因为在`document`未加载时就引入了sm.js导致。  
将库脚本引用放在`</body>`结束标签前。
