### ISSUE TITLE
 data-transition='slide-out' 为什么不管用？

### ISSUE THREAD

**Issue by djfly** [sdc-alibaba/SUI-Mobile#80]
在a标签设置这个动画效果，为什么不管用了？ data-transition='slide-in'  data-transition='slide-out'  data-transition='fade' 都用不了啊

**Comment by Mickey-** [comment]
文档哪里有说这种用法？贴个链接或截图吧

**Comment by djfly** [comment]
http://m.sui.taobao.org/getting-started/ 这里 使用组件

``` html
<a class="button button-link button-nav pull-left" href="/demos/card" data-transition='slide-out'>
      <span class="icon icon-left"></span>
      返回
    </a>
```

push文档里有，https://github.com/sdc-alibaba/SUI-Mobile/blob/26929fd2be7ec34229526ecc6cd64a66cf411be4/docs/_includes/_components/push.html

**Comment by djfly** [comment]
我觉的应该加上fade动画效果，或者说去掉左右翻页的动画，有些地方不适合使用这种效果

**Comment by Mickey-** [comment]
哦是这样的，http://m.sui.taobao.org/changelog/  

因为push.js的一些问题以及过于的臃肿，0.5.0 开始我们就放弃了push.js。  
然后为了方便某些用户自己选择路由系统，0.5.2版本我们增加了配置可以默认不启用MSUI自带的路由系统，你依然可以额外引入push.js来使用他。

这些都可以在changelog里查看。官网文档遗漏了一些部分，没有完全更新

**Comment by djfly** [comment]
@Mickey- 那现在的router如何控制这个特效啊，可以使用fade么，或者干脆关闭

**Comment by Mickey-** [comment]
现在想使用fade或其他任何特效的话，可以自己实现/重写 sui-mobile 控制动画相关class的属性。你可以阅读 js/router.js 和其css 的源码了解

**Comment by djfly** [comment]
thanks，我去看看
