### ISSUE TITLE
Switch (Checkbox)在android微信浏览器里不能用。

### ISSUE THREAD

**Issue by njleonzhang** [sdc-alibaba/SUI-Mobile#81]
点击之后不会打开。

小米4，Miui 7, android 4.4.4 ,最新版本的微信内置浏览器。
中兴手机，android 4.3，最新版本的微信内置浏览器。

**Comment by njleonzhang** [comment]
调试了一下在fastclick.js里报了异常

// Some old versions of Android don't have Function.prototype.bind
function bind(method, context) {
            return function() { return method.apply(context, arguments); };
}

# 

Uncaught TypeError: Cannot call method 'apply' of undefined sm.js:608

fastclick.js好像对老版本浏览器和android微信浏览器支持不太好。

**Comment by Mickey-** [comment]
我看下
