### ISSUE TITLE
增加version字段

### ISSUE THREAD

**Issue by jzlxiaohei** [sdc-alibaba/SUI-Mobile#82]
不知道有没有字段 表明sui的版本。
类似$.sui.version

**Comment by Mickey-** [comment]
版本号已经在资源的链接上表明了，类似 `g.alicdn.com/msui/sm/0.5.2/css/sm.min.css`

你是有什么特殊需求吗

**Comment by jzlxiaohei** [comment]
路由加载ajax新页面，新页面的返回，0.5.0是OK的，0.5.2我之前跑通的东西就不行。。但是官网的组件还是能跑通的，我看了一下官网引用的js和css，地址没有表明版本，我想先自己排除版本的问题。
另外加一个version，应该是惯例

**Comment by Mickey-** [comment]
g.alicdn.com/msui/sm/0.5.2/css/sm.min.css  这里的0.5.2不是表明版本了么。

版本号我们也可以挂出来方便使用，会随0.5.3版本发布：）

**Comment by jzlxiaohei** [comment]
文档里是有的。示例里，看加载的静态文件，path 是这样的 `/dist/js/sm.js`.
ok，赞一下维护力度

**Comment by Mickey-** [comment]
额，文档里为了方便调试，直接引用的本地文件，我们使用都是引用阿里覆盖在全球的CDN 资源,这里有示例：http://m.sui.taobao.org/getting-started/

**Comment by jzlxiaohei** [comment]
恩，这个我知道。我是因为出来点问题，但是官网的示例是ok的，所以想先搞清楚版本的问题。
另外文档中版本不一致的地方，比较多，比如[http://m.sui.taobao.org/examples/getting-started/](http://m.sui.taobao.org/examples/getting-started/)

至于其他的问题，我暂时用其他方式绕开了。适当的时候，把最近遇到的问题汇总，再来说明。

非常感谢回答。
