### ISSUE TITLE
sui mobile有没有离线版，CDN连接使用过程中有很多功能用不了

### ISSUE THREAD

**Issue by gongstring** [sdc-alibaba/SUI-Mobile#83]
sui mobile有没有离线版，CDN使用过程中有很多功能用不了。例如侧边栏，popop功能等，谢谢!

**Comment by Mickey-** [comment]
在github上clone源码编译即可。不过还是建议使用稳定的阿里CDN服务。

另外你说的问题我们并没有遇到，如果cdn版本有，离线版本一样有，所以直接贴出你发现的错误吧，我们一起改进

**Comment by gongstring** [comment]
```
$(document).on('click','#searchKey', function () {
  $.popup('.popup-about');
});
```

我在使用这段代码的时候，报错，显示

Uncaught TypeError: $.popup is not a function(anonymous function) @ index.html:59
$.fn.on.$this.each.delegator @ zepto.js:1082
events.split.forEach.handler.proxy @ zepto.js:951

**Comment by Mickey-** [comment]
这很比较明显是资源加载相关的问题，请先自行解决。然后认真阅读文档http://m.sui.taobao.org/components/#popup 

我们在 文档demo页 http://m.sui.taobao.org/demos/  执行

```
$.popup('<b class="popup">sadf</b>')
```

是可以正常弹出popup的，看起来需要再仔细阅读下文档

**Comment by gongstring** [comment]
好的，我先认真阅读下，谢谢解答。

**Comment by Mickey-** [comment]
无虾米，我们也有一些不完善的地方，测试使用后如果真有什么问题，再开issue反馈哈
