### ISSUE TITLE
带箭头的列表在安卓上微信、QQ 里（QQ 浏览器 X5内核）显示不正常

### ISSUE THREAD

**Issue by anchoretics** [sdc-alibaba/SUI-Mobile#84]
如图：
![image](https://cloud.githubusercontent.com/assets/4724115/11174302/95edfc5a-8c5c-11e5-8b3f-f5d74e076a6c.png)

**Comment by Mickey-** [comment]
我这边在安卓4.4里测试，qqx5内核浏览器和微信扫码进去验证，都是OK的

是不是你的测试机型版本过旧？

**Comment by anchoretics** [comment]
不旧，是今年的 MX5，我再试试

**Comment by jzlxiaohei** [comment]
我也遇到了相同的问题。我调试了一下，个人认为可能是 background-position的`calc`的问题。可能不支持这个吧

```
.list-block .item-link .item-inner {
    padding-right: 1.5rem;
    background-image: url(../img/i-list-chevron-right.png);
    background-repeat: no-repeat;
    background-position: calc(100% - .5rem) center; //here
    -webkit-background-size: .7rem .7rem;
    background-size: .7rem;
}
```

**Comment by anchoretics** [comment]
我又测了一下各种机型的显示效果
测试地址：http://7bv9b3.com1.z0.glb.clouddn.com/a.html
截图如下：
黑莓10：
![image](https://cloud.githubusercontent.com/assets/4724115/11201309/e74ae958-8d17-11e5-9164-6b2182611d4d.png)

小米3：
![image](https://cloud.githubusercontent.com/assets/4724115/11201321/04db069c-8d18-11e5-91e3-42ede503fda2.png)

iPhone5s：
![image](https://cloud.githubusercontent.com/assets/4724115/11201390/b6e5f9f0-8d18-11e5-87e5-5062b231dd78.png)

**Comment by whyliam** [comment]
是 background-position的calc的问题，因为qq内核不支持calc，所以我用其他方法弄了
