### ISSUE TITLE
0.5.2 内联page，返回有问题

### ISSUE THREAD

**Issue by jzlxiaohei** [sdc-alibaba/SUI-Mobile#85]
我线上写了个小demo，跳到内联页后，就返回不了了

[http://dapigu.wallstcn.com/sui-0.5.2.html](http://dapigu.wallstcn.com/sui-0.5.2.html)

**Comment by Mickey-** [comment]
页面访问不了。提示“502 Bad Gateway”

**Comment by jzlxiaohei** [comment]
不好意思。已经ok了

**Comment by Mickey-** [comment]
好那先关了，有其他问题在再另开issue吧

**Comment by jzlxiaohei** [comment]
不是功能ok了，是网址ok了。。。

**Comment by Mickey-** [comment]
额好，我看下

**Comment by jzlxiaohei** [comment]
确认了吗。。把这条open吧

**Comment by Mickey-** [comment]
0.5.3（还没发布）的第一个commit就是解决这个问题的，可以在源码里看到，我一会把commit关联到这个issue
