### ISSUE TITLE
幻灯片swiper-pagination 在多次点击其他页面返回后会出现过个，我总共只有俩张图，

### ISSUE THREAD

**Issue by djfly** [sdc-alibaba/SUI-Mobile#86]
在多次点击页面后，就会出现这情况

``` html
<div class="swiper-pagination" style="bottom:0rem">
<span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>
<span class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet">
</span><span class="swiper-pagination-bullet"></span>
<span class="swiper-pagination-bullet"></span>
</div>
```

本来应该是俩个

``` html
<div class="swiper-pagination" style="bottom:0rem">
<span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span>
<span class="swiper-pagination-bullet"></span>
</div>
```

**Comment by djfly** [comment]
知道怎么回事了，是因为多个页面都有swiper的话，好像就会获取多个swiper下的图片个数，所以不对，应该获取当前页面下的图片个数

**Comment by djfly** [comment]
这是个大bug啊 @Mickey-

**Comment by Mickey-** [comment]
贴个Demo链接我们看下吧，放个fiddle或其他链接

**Comment by djfly** [comment]
很简单的，就是你弄俩个页面都有幻灯片，a页面有个俩张图片的幻灯片，b页面有三张图片的幻灯片，由a页面进入b页面，然后点返回(back)，a页面的swiper-pagination 里面span个数是b页面里面span的个，是三个数，就是幻灯片下面那个点点个数

**Comment by djfly** [comment]
这个bug还没修复啊？swiper-init.js 里面 

这句有问题吧，`$.Swiper.prototype.defaults.pagination = '.swiper-pagination';`  这个会查找所有page里面的swiper-pagination，应该限定到page-current

@Mickey-

**Comment by djfly** [comment]
@Mickey-  我已经描述了bug了，有时间看下这个bug吧，应该很好修复， `$.Swiper.prototype.defaults.pagination = '.page-current .swiper-pagination';` 这样应该就行了

**Comment by Mickey-** [comment]
@djfly 非常感谢这两周来的追踪定位！

你已经分析到修复方案了，麻烦你直接fork仓库修改、提交一个PR吧，我们会review后合并，也记录下你的贡献。

**Comment by djfly** [comment]
还是没修复，在后退的情况下不正常...

**Comment by djfly** [comment]
方便的话我提供url，你看下这个bug吧，加个微信，url目前不能公开

**Comment by Mickey-** [comment]
```
在后退的情况下不正常
```

是路由问题还是幻灯片的问题？

**Comment by djfly** [comment]
幻灯片导航的那个点个数不对

**Comment by Mickey-** [comment]
好，麻烦提供一个稳定复现问题的Demo链接吧，我们看下

**Comment by djfly** [comment]
只能在微信上看，url不方便公开，你加我微信863155629

**Comment by Mickey-** [comment]
在后续有幻灯片的页面初始化(pageInit)后，执行 `$.reinitSwiper('#page-index')`
