### ISSUE TITLE
datetimepicker可以选择格式吗？比如我只想取年月日，或者是小时分钟。而且还不想用calendar的样式。

### ISSUE THREAD

**Issue by 18940818955** [sdc-alibaba/SUI-Mobile#861]
datetimepicker可以选择格式吗？比如我只想取年月日，或者是小时分钟。而且还不想用calendar的样式。

**Comment by MatthewKuo93** [comment]
对于你的问题，我的解决办法就是找到sm.js的源代码方法，然后改一下源码，把不想要的时分秒给删除掉就行了。逻辑要核对下，调试下就OK了。
