### ISSUE TITLE
CDN file Missing Quotes

### ISSUE THREAD

**Issue by justQing00** [sdc-alibaba/SUI-Mobile#87]
In this file http://g.alicdn.com/msui/sm/0.5.2/js/sm.js,  This sentence is wrong "var panel = $(e.target).data(panel)", need to change this sentence "var panel = $(e.target).data('panel')"。Otherwise, you will not find the right 'panel'

**Comment by Mickey-** [comment]
thank you

we have already fix this in commit 71c894,we'll publish this patch in V0.5.3

**Comment by Mickey-** [comment]
#94
