### ISSUE TITLE
swiper 数据渲染 observer:true 报错，重新更新数据报错

### ISSUE THREAD

**Issue by jifengdehao** [sdc-alibaba/SUI-Mobile#891]
$(".swiper-container","#index").swiper({
			autoplay: 5000,
			direction: "horizontal",
			loop:true,
			observer:true
		});
 $.reinitSwiper("#index");
//swiper_1
		$.getJSON("api/getImgADList/idxAd1",function(data){
			console.log(data);
			if(data.list !=null){
				$("#swiper_1").html(readSwiperFrame(data.list));
			}
			
		});
		
		//swiper_2
		$.getJSON("api/getImgADList/idxAd2",function(data){
			console.log(data);
			if(data.list !=null){
				$("#swiper_2").html(readSwiperFrame(data.list));
			}
		});

**Comment by MovingbricksInIT** [comment]
请问您这边loop：true的问题解决了么
