### ISSUE TITLE
多个页面跳转时很卡顿，loading图标消失几秒后才跳转到另一个页面

### ISSUE THREAD

**Issue by whistlesun** [sdc-alibaba/SUI-Mobile#90]
RT

**Comment by whistlesun** [comment]
如何禁止点击另一个页面时转菊花？

**Comment by Mickey-** [comment]
链接转场时，如果是内联页面，是不会有loading的，如果是ajax异步载入的，有loading就说明页面数据没加载进来。

额外的，如果还有loading，可能是你的下个页面里可能有异步加载数据的部分.

所以有loading那一定是有数据没有加载完成，这点是合理的。要么你把你的例子Demo地址贴出来看一下

**Comment by whistlesun** [comment]
不是 下一页面没有异步加载的 现在的问题是 菊花隐藏后还需要1~2s新页面才出现 就是有一个白屏的过程
