### ISSUE TITLE
关于移动端1px像素问题 为什么sui的1px也是偶尔出问题

### ISSUE THREAD

**Issue by Unlimitedtang** [sdc-alibaba/SUI-Mobile#902]
以demo里面的卡片-列表卡片为例 在安卓手机（苹果还没测试）里面看 卡头和卡内容下面的1px线是没问题的  线很细 可以看到
 但是如果把列表卡片里面的卡片增加几个 超过高度100%的话 就看不到线了 怎么解决？ 
如果把transform: scaleY(0.5);改成0.6就可以看到了 这是什么bug
目前有没有兼容性比较好的解决办法?用最简单少量的css3代码搞定的？

**Comment by JSoon** [comment]
楼上最好截图并附加机型|系统等信息，大家才好帮忙解答。

**Comment by Unlimitedtang** [comment]
@JSoon 几乎所有安卓都是不显示 我用的测试机是魅族 版本是5.1 不需要截图呀 就是用sui的demo里面的列表卡片页面 代码一模一样的 http://m.sui.taobao.org/demos/card/list-card 
现在官网上不是3个卡片吗 这个在安卓机里也是可以显示线的 因为3个卡片还没超过屏幕高度100% 但是增加几个卡片变成5个6个以上 在安卓机就看不到那条线了

**Comment by JSoon** [comment]
刚看了下，确实很奇怪，自己打补丁吧，或者将描边定义到card-content:before中，可以解决。
