### ISSUE TITLE
sessionStorage保存的url与id对不上号，刷新之后用浏览器的back或者forward都存在问题

### ISSUE THREAD

**Issue by lujunwei** [sdc-alibaba/SUI-Mobile#91]
sessionStorage保存的back跟forward，url与id没有一一对应，刷新之后由于stateid跟currentStateID的变化，根本无法forward，当然back也是错的。
页面过场动画有时候起效，有时候不起效

**Comment by laoxubuer** [comment]
0.5.3版本好像也有这个问题，pageA--(router)--pageB--(router)--pageC--(external)--pageD，然后从pageD(全部都加了back)一路返回，到pageC这里点返回就出问题了。

**Comment by vpersie** [comment]
@lujunwei   @laoxubuer  @liunian ，您们好，我今天做项目也遇到这个问题，请问您们遇到的这个问题解决了吗？如果已解决的话，请问是怎么解决的？谢谢了

**Comment by tinhour** [comment]
Uncaught TypeError: Cannot read property 'id' of undefined @sm.js 我也是路由出报错。不知道什么原因

**Comment by lujunwei** [comment]
我自己重构了路由，删除了back跟forward，自己写了一套逻辑，不管back跟forward，直接使用浏览器的路由机制

**Comment by tinhour** [comment]
用最新版本就解决了这个问题了。
