### ISSUE TITLE
picker的值保存在哪里？

### ISSUE THREAD

**Issue by yzp0112** [sdc-alibaba/SUI-Mobile#919]
![qq 20170207171918](https://cloud.githubusercontent.com/assets/19768750/22685022/b1ab0410-ed59-11e6-9f95-54d3506f1b6e.png)

**Comment by zzwen6** [comment]
可以在这个选择器下面放一个input[type=hidden]，存在这就行；  上下滑动调用的是onchange方法，可以在onchange时，set input[type=hidden]的值
