### ISSUE TITLE
拖动头部或者尾部的bug

### ISSUE THREAD

**Issue by justQing00** [sdc-alibaba/SUI-Mobile#93]
在ios 6s以及6s plus中，
拖动头部<header class=“bar-nav”>或者尾部< nav  class="bar-tab">的时候，
由此产生整个网页的“橡皮筋效果”，导致内容区中的列表列表不能上下滑动的bug。

单纯拖动内容区content也存在这个问题，到底部或者头部的时候，拖动content，引起整个页面的滚动，从而使得列表不能正常滚动。

不知道这个问题描述清楚没？然后下面这种解决方法不知是否合适？大神不知道有什么更好的解决方法，说说看咯？

我这边是禁用了头部、尾部的touchmove事件，并且ScrollFix 变通解决内容区到底部/头部时的拖动（不是滚动）带来的整个页面的滚动。https://github.com/joelambert/ScrollFix
下面的这个是使用relative布局，直接避免了这个问题
http://hi.dearb.me/build/

**Comment by Mickey-** [comment]
感谢指正！能否协作修改源码，并提交一个PR贡献？

**Comment by qizhanyu** [comment]
iphone6 iphone4s 在前两个月的时候就遇到了相同的问题，苦于工期限制，最终放弃sui ，Ratchet 也存在相同的问题。今天又开始了一个新的项目，于是又想起了sui 可试验之后发现问题还是没有解决，希望此问题解决后发送一个公告或者通知。万分感谢！

**Comment by qizhanyu** [comment]
大神可否详细讲一下针对原有项目做了什么改动？刚接触sui时间不久。

**Comment by falconlux** [comment]
我是在 body上加了个 ontouchmove="return false" 然后 content ontouchstart的时候把这个属性去掉 ontouchend的时候 再加上。。。

**Comment by justQing00** [comment]
@Mickey，可以，只不过我的方案是一种变向解决,当时因为项目时间需要，就选择了这个解决方案。天猫手机网页也应该是通过合适的relative布局解决的，应当可以参考，当时感觉会改动很多SUI布局,也就没有动了。不过会试着用relative,解决的哈，不敢打包票，也是刚用SUI几天。

然后@dami2933，头部、尾部，在绑定的touchmove事件中，通过evt.prventDefault()阻止拖动。然后ScrollFix用于解决<div class="content">含有overflow的滚动带来的页面整体拖动，防止变成橡皮筋效果。ScrollFix本身的代码很少，原理是这样的，在触摸开始时，如果发现滚动区域已经处于极限状态时，就手工设置 scrollTop的值，将滚动内容向边缘方向偏移 1px（这实际上改变了滚动区域的极限状态），从而诱使浏览器对滚动区块使用橡皮筋效果，而不会把触摸事件向上传播到 DOM 树（引起整页滚动）

**Comment by xiaran113** [comment]
@justQing00 拖动头部或者尾部的时候，在头部或者尾部未弹回原位之前，滚动页面会导致整个页面滚动，若等它弹回原位之后再滚动页面则恢复正常，不知道我理解的这个问题对么？http://hi.dearb.me/build/        这个页面我在iphone6s下试了下，好像也有这个问题，在该页面的contacts下测试比较明显

**Comment by justQing00** [comment]
@xiaran113 ，对就是这个问题。弹回原位之后再滚动页面则恢复正常

**Comment by xiaran113** [comment]
@justQing00 其实这个不是布局的问题，IOS惯性滚动无法触发 scroll 事件的问题，解决办法就是用JS滚动条。手淘用的是js滚动条，所以和布局无关。不过这个体验的确不是太好，所以我们采用了你的建议，在下个版本里会禁止对顶部和底部touchmove事件。采用原生滚动条的页面基本都会有这个问题，鉴于原生的滚动条性能比js好很多，所以暂且先这么改着，等以后有更好的解决方法了我们再改进

**Comment by xiaran113** [comment]
@justQing00 本来的页面如果在class="content" 后加data-type="js" ，将滚动条手动设置成js的，应该就没有这个问题了

**Comment by justQing00** [comment]
@xiaran113 原来如此，很有一种恍然大悟的感觉。先试一试咯
