### ISSUE TITLE
路由后页面的click事件失效

### ISSUE THREAD

**Issue by jl1014171068** [sdc-alibaba/SUI-Mobile#936]
点击的时候一直提示：
Unable to preventDefault inside passive event listener due to target being treated as passive.
刷新页面后则会正常

**Comment by MJPiero** [comment]
我这边现在也会有这个错误，这个你现在是有解决办法了么

**Comment by ghost** [comment]
+1

**Comment by Ceeson** [comment]
我是页面预览的时候双击就会出现，然后input框都无法获取到焦点了。。。

**Comment by yang123789** [comment]
> 点击的时候一直提示：
> Unable to preventDefault inside passive event listener due to target being treated as passive.
> 刷新页面后则会正常

解决了吗？？
