### ISSUE TITLE
使用官网提供的CDN文件，侧边栏的打开出现错误

### ISSUE THREAD

**Issue by xugege** [sdc-alibaba/SUI-Mobile#94]
我按照官网开始使用的步骤，侧栏不能通过open-panel打开。
只能通过鼠标拖动打开

下面是通过open-panel点击出现的错误
![image](https://cloud.githubusercontent.com/assets/10491416/11204075/e9bfbaf6-8d35-11e5-8bd2-3e166d64e087.png)

通过鼠标拖拽打开侧边栏也会出现错误
![image](https://cloud.githubusercontent.com/assets/10491416/11204094/3d4d8842-8d36-11e5-899c-f84a5b786afa.png)

然后我把官网demo里的sm.css,sm-extend.css,sm.js,sm-extend.js导出来，在页面上使用导出来的文件替换官网的cdn，可以通过open-panel点击打开侧栏

**Comment by Mickey-** [comment]
耽误了你这么多时间非常抱歉。 这个问题已经修复了，但还没有发布，所以会有这个现象。

这周0.5.3 版本会尽快发布！
