### ISSUE TITLE
【无限滚动】间隔线位置变化问题

### ISSUE THREAD

**Issue by muchard** [sdc-alibaba/SUI-Mobile#98]
按住向上拖的时候，间隔线和内容的位置会有所变化，虽然关系不大，不知道可否解决？
![s51119-114356](https://cloud.githubusercontent.com/assets/12826059/11261832/7b8b4224-8eb3-11e5-9216-00f0de8d8951.jpg)
![s51119-114353](https://cloud.githubusercontent.com/assets/12826059/11261852/9572f880-8eb3-11e5-9d2b-322ebbc0a930.jpg)

**Comment by Mickey-** [comment]
刚试了下没有复现，麻烦提供下系统、机型、浏览器型号等信息。

**Comment by muchard** [comment]
微信自带浏览器，系统都是安卓5.0，试过小米4、魅族MX4都有这问题，试过，自带浏览器没有这个问题。

**Comment by xiaran113** [comment]
你好，我测试了mx3和米4,系统安卓4.4.4，没复现这个问题，我的测试地址是http://m.sui.taobao.org/demos/list/contacts-list  ，  你试试看这个地址在你的手机中是否还有问题，如果没有，你可以放出你的demo地址，我去帮你看下定位问题，如果这个地址也有问题，麻烦也告诉我们一下，我去找一样的机型系统重测，谢谢～

**Comment by xiaran113** [comment]
红米note2 ，5.0也是好的～

**Comment by muchard** [comment]
@xiaran113 可以试试看用微信会不会？我用uc也是没问题的，开始微信一打开就这样了，同样地址，无限滚动那个。http://m.sui.taobao.org/demos/infinite-scroll

**Comment by xiaran113** [comment]
你好，发现了，安卓5.0版本以上都有问题，5.0以下没有问题，这个问题我后面定位下原因，有进展了告诉你，谢谢～
