### ISSUE TITLE
请问下 怎么可以实现不刷新的返回上一页？求解！

### ISSUE THREAD

**Issue by changbb** [sdc-alibaba/SUI-Mobile#980]
如题。我从内联页面A 转到B  B页面输入了一些数据，想要在保存的时候返回到页面A 同时把B的数据赋值到A页面  但是用.back返回上一页的时候 页面会刷新 数据也就没了  请问要怎么做？

**Comment by MatthewKuo93** [comment]
这个问题的解决方法就是在page-group下面的每个子页面page盒子上都加上一个特有的id，因为这个里面的原生路由跳转是根据page盒子的id走，然后把page-current类切换到当前显示的page上。在点击back的时候，也是根据page的id来跳转。在这里你的页面B有id，但是页面A上要是没有id，点击返回后。框架会自动随机生成一个数字的id添加到A页面（就是A页面的page盒子上）。这个时候A页面就会刷新。

解决：每个page盒子都赋值id。
