### ISSUE TITLE
picker没法设置默认值吗？

### ISSUE THREAD

**Issue by fishenal** [sdc-alibaba/SUI-Mobile#983]
picker没法设置默认值吗？

**Comment by feishaozhang** [comment]
$('#picker-name').val("郑")
    $("#picker-name").picker({
      toolbarTemplate: '<header class="bar bar-nav">\
      <button class="button button-link pull-right close-picker">确定</button>\
      <h1 class="title">请选择称呼</h1>\
      </header>',
	  ### **value:['郑'],**
      cols: [
        {
          textAlign: 'center',
          values: ['赵', '钱', '孙', '李', '周', '吴', '郑', '王']
        }

      ]
    });
