### ISSUE TITLE
乱码问题，怎么解决

### ISSUE THREAD

**Issue by hello-word-12138** [sdc-alibaba/SUI-Mobile#989]
![default](https://user-images.githubusercontent.com/17819428/30101810-43640f2a-9320-11e7-8c68-ee6f051cd6cf.png)
confirm框乱码！

**Comment by changbb** [comment]
看下你的编码格式 是不是 utf-8

**Comment by hello-word-12138** [comment]
问题原因找到了，并不是UTF-8的原因，是下载sm.min.js的时候网页就显示乱码。到gihub上下载的js就没问题了，这个估计是设计之初没考虑完善吧！
