### ISSUE TITLE
安卓微信浏览器内 js滚动模式下 input date 不能弹出时间选择器 native滚动模式下可以弹出

### ISSUE THREAD

**Issue by crazylin** [sdc-alibaba/SUI-Mobile#99]

**Comment by Mickey-** [comment]
是日期时期的Picker组件还是日历组件？

**Comment by xiaran113** [comment]
@crazylin 请问操作系统版本号是多少，有 demo吗，我测试了sui-m的日期选择器和时间选择器均无该问题

**Comment by qizhanyu** [comment]
@Mickey-  安卓4.3 微信版本6.3.8 三星NOTE 2 示例 http://m.sui.taobao.org/demos/form/layout
安卓微信浏览器中，日期选择框无法弹出，而是弹出系统输入法

**Comment by xiaran113** [comment]
@damichn 这是因为部分安卓浏览器不支持type=date这个h5属性，这个demo主要是用来介绍表单布局的，所以里面的例子写的比较简单，如果要使用日期选择器，建议使用http://m.sui.taobao.org/demos/datetime-picker 这个。就不会有上述问题

**Comment by qizhanyu** [comment]
@xiaran113 经过反复测试得出的结果:在页面中去掉`<script type='text/javascript' src='//g.alicdn.com/msui/sm/0.5.7/js/sm.js' charset='utf-8'></script>`日期选择框正常弹出，加上`<script type='text/javascript' src='//g.alicdn.com/msui/sm/0.5.7/js/sm.js' charset='utf-8'></script>`则无法正常弹出。 之前在boostrap 中使用 type=date 这个属性是没有问题的，所以你们还是看一下吧，应该是框架的问题。

**Comment by xiaran113** [comment]
@damichn 你好，非常感谢，测试了下是fastclick影响了type=date的效果，已经修复，下版本会发，谢谢～

**Comment by xiaran113** [comment]
#171
